// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checks.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteVoiceCheck = `-- name: DeleteVoiceCheck :exec
DELETE FROM voice_checks WHERE id = ? AND user_id = ?
`

type DeleteVoiceCheckParams struct {
	ID     string
	UserID string
}

// A check whose enqueue failed leaves no result (VOICE-44).
func (q *Queries) DeleteVoiceCheck(ctx context.Context, arg DeleteVoiceCheckParams) error {
	_, err := q.db.ExecContext(ctx, deleteVoiceCheck, arg.ID, arg.UserID)
	return err
}

const failVoiceCheck = `-- name: FailVoiceCheck :execrows
UPDATE voice_checks SET status = 'failed', error_reason = ?, error_params = ?, technical_detail = ?, updated_at = ?
WHERE id = ? AND user_id = ? AND status IN ('queued', 'running')
`

type FailVoiceCheckParams struct {
	ErrorReason     sql.NullString
	ErrorParams     sql.NullString
	TechnicalDetail sql.NullString
	UpdatedAt       string
	ID              string
	UserID          string
}

func (q *Queries) FailVoiceCheck(ctx context.Context, arg FailVoiceCheckParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failVoiceCheck,
		arg.ErrorReason,
		arg.ErrorParams,
		arg.TechnicalDetail,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finishVoiceCheck = `-- name: FinishVoiceCheck :execrows
UPDATE voice_checks SET status = 'done', piece = ?, updated_at = ?
WHERE id = ? AND user_id = ? AND status = 'running'
`

type FinishVoiceCheckParams struct {
	Piece     sql.NullString
	UpdatedAt string
	ID        string
	UserID    string
}

func (q *Queries) FinishVoiceCheck(ctx context.Context, arg FinishVoiceCheckParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishVoiceCheck,
		arg.Piece,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getVoiceCheck = `-- name: GetVoiceCheck :one
SELECT id, voice_id, prompt_key, material_id, analysis_created_at, projection, write_model, status,
       piece, error_reason, error_params, technical_detail, created_at, updated_at
FROM voice_checks
WHERE id = ? AND user_id = ?
`

type GetVoiceCheckParams struct {
	ID     string
	UserID string
}

type GetVoiceCheckRow struct {
	ID                string
	VoiceID           string
	PromptKey         string
	MaterialID        string
	AnalysisCreatedAt string
	Projection        string
	WriteModel        string
	Status            string
	Piece             sql.NullString
	ErrorReason       sql.NullString
	ErrorParams       sql.NullString
	TechnicalDetail   sql.NullString
	CreatedAt         string
	UpdatedAt         string
}

func (q *Queries) GetVoiceCheck(ctx context.Context, arg GetVoiceCheckParams) (GetVoiceCheckRow, error) {
	row := q.db.QueryRowContext(ctx, getVoiceCheck, arg.ID, arg.UserID)
	var i GetVoiceCheckRow
	err := row.Scan(
		&i.ID,
		&i.VoiceID,
		&i.PromptKey,
		&i.MaterialID,
		&i.AnalysisCreatedAt,
		&i.Projection,
		&i.WriteModel,
		&i.Status,
		&i.Piece,
		&i.ErrorReason,
		&i.ErrorParams,
		&i.TechnicalDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertVoiceCheck = `-- name: InsertVoiceCheck :exec
INSERT INTO voice_checks (id, user_id, voice_id, prompt_key, material_id, analysis_created_at, projection, write_model, status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'queued', ?, ?)
`

type InsertVoiceCheckParams struct {
	ID                string
	UserID            string
	VoiceID           string
	PromptKey         string
	MaterialID        string
	AnalysisCreatedAt string
	Projection        string
	WriteModel        string
	CreatedAt         string
	UpdatedAt         string
}

// One row per check (VOICE-43): its frozen inputs, then its piece or its failure.
func (q *Queries) InsertVoiceCheck(ctx context.Context, arg InsertVoiceCheckParams) error {
	_, err := q.db.ExecContext(ctx, insertVoiceCheck,
		arg.ID,
		arg.UserID,
		arg.VoiceID,
		arg.PromptKey,
		arg.MaterialID,
		arg.AnalysisCreatedAt,
		arg.Projection,
		arg.WriteModel,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listVoiceChecks = `-- name: ListVoiceChecks :many
SELECT id, voice_id, prompt_key, material_id, analysis_created_at, CAST('' AS TEXT) AS projection, write_model, status,
       piece, error_reason, error_params, technical_detail, created_at, updated_at
FROM voice_checks
WHERE voice_id = ? AND user_id = ?
ORDER BY created_at DESC, id DESC
`

type ListVoiceChecksParams struct {
	VoiceID string
	UserID  string
}

type ListVoiceChecksRow struct {
	ID                string
	VoiceID           string
	PromptKey         string
	MaterialID        string
	AnalysisCreatedAt string
	Projection        string
	WriteModel        string
	Status            string
	Piece             sql.NullString
	ErrorReason       sql.NullString
	ErrorParams       sql.NullString
	TechnicalDetail   sql.NullString
	CreatedAt         string
	UpdatedAt         string
}

// The list never shows the frozen projection, so it is not read; it comes back empty only so the
// row keeps GetVoiceCheck's shape.
func (q *Queries) ListVoiceChecks(ctx context.Context, arg ListVoiceChecksParams) ([]ListVoiceChecksRow, error) {
	rows, err := q.db.QueryContext(ctx, listVoiceChecks, arg.VoiceID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVoiceChecksRow
	for rows.Next() {
		var i ListVoiceChecksRow
		if err := rows.Scan(
			&i.ID,
			&i.VoiceID,
			&i.PromptKey,
			&i.MaterialID,
			&i.AnalysisCreatedAt,
			&i.Projection,
			&i.WriteModel,
			&i.Status,
			&i.Piece,
			&i.ErrorReason,
			&i.ErrorParams,
			&i.TechnicalDetail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markVoiceCheckRunning = `-- name: MarkVoiceCheckRunning :execrows
UPDATE voice_checks SET status = 'running', updated_at = ?
WHERE id = ? AND user_id = ? AND status IN ('queued', 'running')
`

type MarkVoiceCheckRunningParams struct {
	UpdatedAt string
	ID        string
	UserID    string
}

func (q *Queries) MarkVoiceCheckRunning(ctx context.Context, arg MarkVoiceCheckRunningParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markVoiceCheckRunning, arg.UpdatedAt, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
