// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type VoicePhotoUpload struct {
	ID        string
	UserID    string
	VoiceID   string
	PromptKey string
	ObjectKey string
	ExpiresAt string
	CreatedAt string
}
