// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type Voice struct {
	ID             string
	UserID         string
	Name           string
	IsDefault      int64
	DeletedAt      sql.NullString
	CreatedAt      string
	UpdatedAt      string
	SourceLanguage string
}

type VoiceManualOverride struct {
	VoiceID   string
	UserID    string
	Layer     string
	Field     string
	Value     string
	UpdatedAt string
}

type VoiceProfileVersion struct {
	ID                  string
	UserID              string
	VoiceID             string
	Version             int64
	Snapshot            string
	Origin              string
	RestoredFromVersion sql.NullInt64
	CreatedAt           string
}

type VoiceVersionSample struct {
	VoiceID   string
	UserID    string
	Version   int64
	Content   string
	CreatedAt string
}
