// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: voice.sql

package sqlc

import (
	"context"
	"database/sql"
)

const bumpCorpusVersion = `-- name: BumpCorpusVersion :exec
INSERT INTO voice_profiles (voice_id, user_id, corpus_version, updated_at)
VALUES (?, ?, 1, ?)
ON CONFLICT(voice_id) DO UPDATE SET
    corpus_version = voice_profiles.corpus_version + 1,
    updated_at = excluded.updated_at
`

type BumpCorpusVersionParams struct {
	VoiceID   string
	UserID    string
	UpdatedAt string
}

func (q *Queries) BumpCorpusVersion(ctx context.Context, arg BumpCorpusVersionParams) error {
	_, err := q.db.ExecContext(ctx, bumpCorpusVersion, arg.VoiceID, arg.UserID, arg.UpdatedAt)
	return err
}

const claimCorpusVersion = `-- name: ClaimCorpusVersion :execrows
UPDATE voice_profiles
SET updated_at = ?
WHERE voice_id = ? AND user_id = ? AND corpus_version = ?
`

type ClaimCorpusVersionParams struct {
	UpdatedAt     string
	VoiceID       string
	UserID        string
	CorpusVersion int64
}

// The concurrency guard, and nothing else. It used to write the analysis text into a
// `styleguide` column; that column is gone (VOICE-6) and the analysis text now reaches the
// profile only through the structured version this claim gates. Zero rows means the corpus
// moved while the provider was working, so the finished analysis is stale and must not publish.
func (q *Queries) ClaimCorpusVersion(ctx context.Context, arg ClaimCorpusVersionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimCorpusVersion,
		arg.UpdatedAt,
		arg.VoiceID,
		arg.UserID,
		arg.CorpusVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearDefaultVoice = `-- name: ClearDefaultVoice :exec
UPDATE voices SET is_default = 0, updated_at = ? WHERE user_id = ? AND is_default = 1
`

type ClearDefaultVoiceParams struct {
	UpdatedAt string
	UserID    string
}

func (q *Queries) ClearDefaultVoice(ctx context.Context, arg ClearDefaultVoiceParams) error {
	_, err := q.db.ExecContext(ctx, clearDefaultVoice, arg.UpdatedAt, arg.UserID)
	return err
}

const countSamples = `-- name: CountSamples :one
SELECT count(*) FROM voice_samples WHERE voice_id = ? AND user_id = ?
`

type CountSamplesParams struct {
	VoiceID string
	UserID  string
}

func (q *Queries) CountSamples(ctx context.Context, arg CountSamplesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSamples, arg.VoiceID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteManualOverride = `-- name: DeleteManualOverride :execrows
DELETE FROM voice_manual_overrides WHERE voice_id=? AND user_id=? AND layer=? AND field=?
`

type DeleteManualOverrideParams struct {
	VoiceID string
	UserID  string
	Layer   string
	Field   string
}

func (q *Queries) DeleteManualOverride(ctx context.Context, arg DeleteManualOverrideParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteManualOverride,
		arg.VoiceID,
		arg.UserID,
		arg.Layer,
		arg.Field,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSample = `-- name: DeleteSample :execrows
DELETE FROM voice_samples WHERE id = ? AND voice_id = ? AND user_id = ?
`

type DeleteSampleParams struct {
	ID      string
	VoiceID string
	UserID  string
}

func (q *Queries) DeleteSample(ctx context.Context, arg DeleteSampleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSample, arg.ID, arg.VoiceID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCorpusVersion = `-- name: GetCorpusVersion :one
SELECT corpus_version FROM voice_profiles WHERE voice_id = ? AND user_id = ?
`

type GetCorpusVersionParams struct {
	VoiceID string
	UserID  string
}

func (q *Queries) GetCorpusVersion(ctx context.Context, arg GetCorpusVersionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCorpusVersion, arg.VoiceID, arg.UserID)
	var corpus_version int64
	err := row.Scan(&corpus_version)
	return corpus_version, err
}

const getProfile = `-- name: GetProfile :one
SELECT voice_id, user_id, current_version, corpus_version, updated_at
FROM voice_profiles
WHERE voice_id = ? AND user_id = ?
`

type GetProfileParams struct {
	VoiceID string
	UserID  string
}

type GetProfileRow struct {
	VoiceID        string
	UserID         string
	CurrentVersion int64
	CorpusVersion  int64
	UpdatedAt      string
}

func (q *Queries) GetProfile(ctx context.Context, arg GetProfileParams) (GetProfileRow, error) {
	row := q.db.QueryRowContext(ctx, getProfile, arg.VoiceID, arg.UserID)
	var i GetProfileRow
	err := row.Scan(
		&i.VoiceID,
		&i.UserID,
		&i.CurrentVersion,
		&i.CorpusVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileVersion = `-- name: GetProfileVersion :one
SELECT id, user_id, voice_id, version, snapshot, origin, restored_from_version, created_at FROM voice_profile_versions WHERE voice_id=? AND user_id=? AND version=?
`

type GetProfileVersionParams struct {
	VoiceID string
	UserID  string
	Version int64
}

func (q *Queries) GetProfileVersion(ctx context.Context, arg GetProfileVersionParams) (VoiceProfileVersion, error) {
	row := q.db.QueryRowContext(ctx, getProfileVersion, arg.VoiceID, arg.UserID, arg.Version)
	var i VoiceProfileVersion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VoiceID,
		&i.Version,
		&i.Snapshot,
		&i.Origin,
		&i.RestoredFromVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getSampleBody = `-- name: GetSampleBody :one
SELECT id, label, body, created_at
FROM voice_samples
WHERE id = ? AND voice_id = ? AND user_id = ?
`

type GetSampleBodyParams struct {
	ID      string
	VoiceID string
	UserID  string
}

type GetSampleBodyRow struct {
	ID        string
	Label     string
	Body      string
	CreatedAt string
}

func (q *Queries) GetSampleBody(ctx context.Context, arg GetSampleBodyParams) (GetSampleBodyRow, error) {
	row := q.db.QueryRowContext(ctx, getSampleBody, arg.ID, arg.VoiceID, arg.UserID)
	var i GetSampleBodyRow
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const getVersionSample = `-- name: GetVersionSample :one
SELECT voice_id, user_id, version, content, created_at
FROM voice_version_samples
WHERE voice_id = ? AND user_id = ? AND version = ?
`

type GetVersionSampleParams struct {
	VoiceID string
	UserID  string
	Version int64
}

func (q *Queries) GetVersionSample(ctx context.Context, arg GetVersionSampleParams) (VoiceVersionSample, error) {
	row := q.db.QueryRowContext(ctx, getVersionSample, arg.VoiceID, arg.UserID, arg.Version)
	var i VoiceVersionSample
	err := row.Scan(
		&i.VoiceID,
		&i.UserID,
		&i.Version,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getVoice = `-- name: GetVoice :one
SELECT v.id, v.user_id, v.name, v.is_default, v.deleted_at, v.created_at, v.updated_at,
       CAST(EXISTS (
           SELECT 1 FROM voice_profiles p
           WHERE p.voice_id = v.id AND p.user_id = v.user_id AND p.current_version > 0
       ) AS INTEGER) AS made,
       CAST((
           SELECT count(*) FROM voice_samples s
           WHERE s.voice_id = v.id AND s.user_id = v.user_id
       ) AS INTEGER) AS sample_count,
       CAST(coalesce((
           SELECT pv.created_at FROM voice_profiles p
           JOIN voice_profile_versions pv
             ON pv.voice_id = p.voice_id AND pv.user_id = p.user_id AND pv.version = p.current_version
           WHERE p.voice_id = v.id AND p.user_id = v.user_id
       ), '') AS TEXT) AS analyzed_at
FROM voices v WHERE v.id = ? AND v.user_id = ?
`

type GetVoiceParams struct {
	ID     string
	UserID string
}

type GetVoiceRow struct {
	ID          string
	UserID      string
	Name        string
	IsDefault   int64
	DeletedAt   sql.NullString
	CreatedAt   string
	UpdatedAt   string
	Made        int64
	SampleCount int64
	AnalyzedAt  string
}

func (q *Queries) GetVoice(ctx context.Context, arg GetVoiceParams) (GetVoiceRow, error) {
	row := q.db.QueryRowContext(ctx, getVoice, arg.ID, arg.UserID)
	var i GetVoiceRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsDefault,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Made,
		&i.SampleCount,
		&i.AnalyzedAt,
	)
	return i, err
}

const insertEmptyProfile = `-- name: InsertEmptyProfile :exec
INSERT INTO voice_profiles (voice_id, user_id, updated_at)
VALUES (?, ?, ?)
ON CONFLICT(voice_id) DO UPDATE SET updated_at = excluded.updated_at
`

type InsertEmptyProfileParams struct {
	VoiceID   string
	UserID    string
	UpdatedAt string
}

// Written with the directory row so a read never has to create a profile. It is the ONLY
// insert path for this table now that both free-text editors are gone.
func (q *Queries) InsertEmptyProfile(ctx context.Context, arg InsertEmptyProfileParams) error {
	_, err := q.db.ExecContext(ctx, insertEmptyProfile, arg.VoiceID, arg.UserID, arg.UpdatedAt)
	return err
}

const insertProfileVersion = `-- name: InsertProfileVersion :exec
INSERT INTO voice_profile_versions
    (id, user_id, voice_id, version, snapshot, origin, restored_from_version, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertProfileVersionParams struct {
	ID                  string
	UserID              string
	VoiceID             string
	Version             int64
	Snapshot            string
	Origin              string
	RestoredFromVersion sql.NullInt64
	CreatedAt           string
}

func (q *Queries) InsertProfileVersion(ctx context.Context, arg InsertProfileVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertProfileVersion,
		arg.ID,
		arg.UserID,
		arg.VoiceID,
		arg.Version,
		arg.Snapshot,
		arg.Origin,
		arg.RestoredFromVersion,
		arg.CreatedAt,
	)
	return err
}

const insertSample = `-- name: InsertSample :exec
INSERT INTO voice_samples (id, voice_id, user_id, label, body, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertSampleParams struct {
	ID        string
	VoiceID   string
	UserID    string
	Label     string
	Body      string
	CreatedAt string
}

func (q *Queries) InsertSample(ctx context.Context, arg InsertSampleParams) error {
	_, err := q.db.ExecContext(ctx, insertSample,
		arg.ID,
		arg.VoiceID,
		arg.UserID,
		arg.Label,
		arg.Body,
		arg.CreatedAt,
	)
	return err
}

const insertVoice = `-- name: InsertVoice :exec

INSERT INTO voices (id, user_id, name, is_default, deleted_at, created_at, updated_at)
VALUES (?, ?, ?, ?, NULL, ?, ?)
`

type InsertVoiceParams struct {
	ID        string
	UserID    string
	Name      string
	IsDefault int64
	CreatedAt string
	UpdatedAt string
}

// Voices. The account owns the directory; every profile row below belongs to exactly one
// voice, and every query names both so a same-account id from another voice cannot reach
// this one's aggregate.
// NOTE: keep this file ASCII. sqlc's SELECT * rewriting uses byte offsets where it means
// rune offsets, so one multibyte character here corrupts every later expansion.
func (q *Queries) InsertVoice(ctx context.Context, arg InsertVoiceParams) error {
	_, err := q.db.ExecContext(ctx, insertVoice,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.IsDefault,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listManualOverrides = `-- name: ListManualOverrides :many
SELECT voice_id, user_id, layer, field, value, updated_at FROM voice_manual_overrides WHERE voice_id=? AND user_id=? ORDER BY layer, field
`

type ListManualOverridesParams struct {
	VoiceID string
	UserID  string
}

func (q *Queries) ListManualOverrides(ctx context.Context, arg ListManualOverridesParams) ([]VoiceManualOverride, error) {
	rows, err := q.db.QueryContext(ctx, listManualOverrides, arg.VoiceID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VoiceManualOverride
	for rows.Next() {
		var i VoiceManualOverride
		if err := rows.Scan(
			&i.VoiceID,
			&i.UserID,
			&i.Layer,
			&i.Field,
			&i.Value,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfileVersions = `-- name: ListProfileVersions :many
SELECT v.id, v.user_id, v.voice_id, v.version, v.snapshot, v.origin, v.restored_from_version, v.created_at,
       s.version AS sample_version
FROM voice_profile_versions v
LEFT JOIN voice_version_samples s
       ON s.voice_id = v.voice_id AND s.user_id = v.user_id AND s.version = v.version
WHERE v.voice_id=? AND v.user_id=? ORDER BY v.version DESC
`

type ListProfileVersionsParams struct {
	VoiceID string
	UserID  string
}

type ListProfileVersionsRow struct {
	ID                  string
	UserID              string
	VoiceID             string
	Version             int64
	Snapshot            string
	Origin              string
	RestoredFromVersion sql.NullInt64
	CreatedAt           string
	SampleVersion       sql.NullInt64
}

// `has_sample` rather than the snapshot itself: the list must be able to say whether a version
// can be previewed without carrying every post body it ever produced (VOICE-29).
func (q *Queries) ListProfileVersions(ctx context.Context, arg ListProfileVersionsParams) ([]ListProfileVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProfileVersions, arg.VoiceID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProfileVersionsRow
	for rows.Next() {
		var i ListProfileVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VoiceID,
			&i.Version,
			&i.Snapshot,
			&i.Origin,
			&i.RestoredFromVersion,
			&i.CreatedAt,
			&i.SampleVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSampleBodies = `-- name: ListSampleBodies :many
SELECT id, label, body, created_at
FROM voice_samples
WHERE voice_id = ? AND user_id = ?
ORDER BY created_at DESC, id DESC
`

type ListSampleBodiesParams struct {
	VoiceID string
	UserID  string
}

type ListSampleBodiesRow struct {
	ID        string
	Label     string
	Body      string
	CreatedAt string
}

func (q *Queries) ListSampleBodies(ctx context.Context, arg ListSampleBodiesParams) ([]ListSampleBodiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSampleBodies, arg.VoiceID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSampleBodiesRow
	for rows.Next() {
		var i ListSampleBodiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSamples = `-- name: ListSamples :many
SELECT id, label, length(body) AS chars, created_at
FROM voice_samples
WHERE voice_id = ? AND user_id = ?
ORDER BY created_at DESC, id DESC
`

type ListSamplesParams struct {
	VoiceID string
	UserID  string
}

type ListSamplesRow struct {
	ID        string
	Label     string
	Chars     sql.NullInt64
	CreatedAt string
}

func (q *Queries) ListSamples(ctx context.Context, arg ListSamplesParams) ([]ListSamplesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSamples, arg.VoiceID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSamplesRow
	for rows.Next() {
		var i ListSamplesRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Chars,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVoices = `-- name: ListVoices :many

SELECT v.id, v.user_id, v.name, v.is_default, v.deleted_at, v.created_at, v.updated_at,
       CAST(EXISTS (
           SELECT 1 FROM voice_profiles p
           WHERE p.voice_id = v.id AND p.user_id = v.user_id AND p.current_version > 0
       ) AS INTEGER) AS made,
       CAST((
           SELECT count(*) FROM voice_samples s
           WHERE s.voice_id = v.id AND s.user_id = v.user_id
       ) AS INTEGER) AS sample_count,
       CAST(coalesce((
           SELECT pv.created_at FROM voice_profiles p
           JOIN voice_profile_versions pv
             ON pv.voice_id = p.voice_id AND pv.user_id = p.user_id AND pv.version = p.current_version
           WHERE p.voice_id = v.id AND p.user_id = v.user_id
       ), '') AS TEXT) AS analyzed_at
FROM voices v WHERE v.user_id = ?
ORDER BY v.deleted_at IS NOT NULL, v.is_default DESC, v.name, v.id
`

type ListVoicesRow struct {
	ID          string
	UserID      string
	Name        string
	IsDefault   int64
	DeletedAt   sql.NullString
	CreatedAt   string
	UpdatedAt   string
	Made        int64
	SampleCount int64
	AnalyzedAt  string
}

// Every directory read carries made (a published analysis exists, POST-23), the sample count
// and the current analysis's publication time for the row's meta line (VOICE-52). The two
// reads select the same columns, so their rows convert to one another.
func (q *Queries) ListVoices(ctx context.Context, userID string) ([]ListVoicesRow, error) {
	rows, err := q.db.QueryContext(ctx, listVoices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVoicesRow
	for rows.Next() {
		var i ListVoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.IsDefault,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Made,
			&i.SampleCount,
			&i.AnalyzedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameVoice = `-- name: RenameVoice :execrows
UPDATE voices SET name = ?, updated_at = ? WHERE id = ? AND user_id = ?
`

type RenameVoiceParams struct {
	Name      string
	UpdatedAt string
	ID        string
	UserID    string
}

func (q *Queries) RenameVoice(ctx context.Context, arg RenameVoiceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renameVoice,
		arg.Name,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const restoreVoice = `-- name: RestoreVoice :execrows
UPDATE voices SET deleted_at = NULL, updated_at = ?
WHERE id = ? AND user_id = ? AND deleted_at IS NOT NULL
`

type RestoreVoiceParams struct {
	UpdatedAt string
	ID        string
	UserID    string
}

func (q *Queries) RestoreVoice(ctx context.Context, arg RestoreVoiceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, restoreVoice, arg.UpdatedAt, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setDefaultVoice = `-- name: SetDefaultVoice :execrows
UPDATE voices SET is_default = 1, updated_at = ?
WHERE id = ? AND user_id = ? AND deleted_at IS NULL
`

type SetDefaultVoiceParams struct {
	UpdatedAt string
	ID        string
	UserID    string
}

func (q *Queries) SetDefaultVoice(ctx context.Context, arg SetDefaultVoiceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setDefaultVoice, arg.UpdatedAt, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setProfileHead = `-- name: SetProfileHead :exec
INSERT INTO voice_profiles(voice_id, user_id, corpus_version, current_version, updated_at)
VALUES (?, ?, 0, ?, ?)
ON CONFLICT(voice_id) DO UPDATE SET current_version=excluded.current_version, updated_at=excluded.updated_at
`

type SetProfileHeadParams struct {
	VoiceID        string
	UserID         string
	CurrentVersion int64
	UpdatedAt      string
}

func (q *Queries) SetProfileHead(ctx context.Context, arg SetProfileHeadParams) error {
	_, err := q.db.ExecContext(ctx, setProfileHead,
		arg.VoiceID,
		arg.UserID,
		arg.CurrentVersion,
		arg.UpdatedAt,
	)
	return err
}

const softDeleteVoice = `-- name: SoftDeleteVoice :execrows
UPDATE voices SET deleted_at = ?, updated_at = ?, is_default = 0
WHERE id = ? AND user_id = ? AND deleted_at IS NULL
`

type SoftDeleteVoiceParams struct {
	DeletedAt sql.NullString
	UpdatedAt string
	ID        string
	UserID    string
}

// Deleting the default leaves the account with none (VOICE-13): a tombstone is never it.
func (q *Queries) SoftDeleteVoice(ctx context.Context, arg SoftDeleteVoiceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteVoice,
		arg.DeletedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertManualOverride = `-- name: UpsertManualOverride :exec
INSERT INTO voice_manual_overrides(voice_id, user_id, layer, field, value, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(voice_id,layer,field) DO UPDATE SET value=excluded.value, updated_at=excluded.updated_at
`

type UpsertManualOverrideParams struct {
	VoiceID   string
	UserID    string
	Layer     string
	Field     string
	Value     string
	UpdatedAt string
}

func (q *Queries) UpsertManualOverride(ctx context.Context, arg UpsertManualOverrideParams) error {
	_, err := q.db.ExecContext(ctx, upsertManualOverride,
		arg.VoiceID,
		arg.UserID,
		arg.Layer,
		arg.Field,
		arg.Value,
		arg.UpdatedAt,
	)
	return err
}

const upsertVersionSample = `-- name: UpsertVersionSample :exec
INSERT INTO voice_version_samples (voice_id, user_id, version, content, created_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(voice_id, version) DO UPDATE SET
    content = excluded.content,
    created_at = excluded.created_at
`

type UpsertVersionSampleParams struct {
	VoiceID   string
	UserID    string
	Version   int64
	Content   string
	CreatedAt string
}

// One snapshot per version: a later generation under the same head REPLACES it.
func (q *Queries) UpsertVersionSample(ctx context.Context, arg UpsertVersionSampleParams) error {
	_, err := q.db.ExecContext(ctx, upsertVersionSample,
		arg.VoiceID,
		arg.UserID,
		arg.Version,
		arg.Content,
		arg.CreatedAt,
	)
	return err
}
