// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memories.sql

package sqlc

import (
	"context"
)

const countMemories = `-- name: CountMemories :one
SELECT count(*) FROM memories WHERE user_id = ?
`

func (q *Queries) CountMemories(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMemories, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMemory = `-- name: DeleteMemory :execrows
DELETE FROM memories WHERE id = ? AND user_id = ?
`

type DeleteMemoryParams struct {
	ID     string
	UserID string
}

// The schema cascades this memory's own tags and source links. No post row is ever touched.
func (q *Queries) DeleteMemory(ctx context.Context, arg DeleteMemoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMemory, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteMemoryIfUnsourced = `-- name: DeleteMemoryIfUnsourced :execrows
DELETE FROM memories
WHERE memories.id = ? AND memories.user_id = ?
  AND NOT EXISTS (
    SELECT 1 FROM memory_sources AS remaining WHERE remaining.memory_id = memories.id
  )
`

type DeleteMemoryIfUnsourcedParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteMemoryIfUnsourced(ctx context.Context, arg DeleteMemoryIfUnsourcedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMemoryIfUnsourced, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteMemorySourcesForPost = `-- name: DeleteMemorySourcesForPost :exec
DELETE FROM memory_sources WHERE user_id = ? AND post_slug = ?
`

type DeleteMemorySourcesForPostParams struct {
	UserID   string
	PostSlug string
}

func (q *Queries) DeleteMemorySourcesForPost(ctx context.Context, arg DeleteMemorySourcesForPostParams) error {
	_, err := q.db.ExecContext(ctx, deleteMemorySourcesForPost, arg.UserID, arg.PostSlug)
	return err
}

const deleteMemoryTags = `-- name: DeleteMemoryTags :exec
DELETE FROM memory_tags WHERE memory_id = ? AND user_id = ?
`

type DeleteMemoryTagsParams struct {
	MemoryID string
	UserID   string
}

func (q *Queries) DeleteMemoryTags(ctx context.Context, arg DeleteMemoryTagsParams) error {
	_, err := q.db.ExecContext(ctx, deleteMemoryTags, arg.MemoryID, arg.UserID)
	return err
}

const getMemory = `-- name: GetMemory :one
SELECT id, user_id, text, kind, created_at, updated_at, last_seen_at
FROM memories
WHERE id = ? AND user_id = ?
`

type GetMemoryParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetMemory(ctx context.Context, arg GetMemoryParams) (Memory, error) {
	row := q.db.QueryRowContext(ctx, getMemory, arg.ID, arg.UserID)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Text,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const insertMemory = `-- name: InsertMemory :exec

INSERT INTO memories (id, user_id, text, kind, created_at, updated_at, last_seen_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertMemoryParams struct {
	ID         string
	UserID     string
	Text       string
	Kind       string
	CreatedAt  string
	UpdatedAt  string
	LastSeenAt string
}

// ASCII only: sqlc slices these statements by byte offset but counts in runes, so a
// multi-byte character anywhere above rotates every generated query text.
//
// Writing memories. The account owns them; every statement names user_id, so a same-shaped
// id from another account reaches nothing rather than someone else's facts.
//
// posts is another context's table and is never joined here: a source link carries the
// post's slug and nothing else, and the post context tells this one when a post is gone
// (ARCHITECTURE section 2.2). The list ordering is the INJECTION order: most recently used
// first, then most recently created, so the management screen and the write prompt cannot
// disagree about which fact the writer sees first.
func (q *Queries) InsertMemory(ctx context.Context, arg InsertMemoryParams) error {
	_, err := q.db.ExecContext(ctx, insertMemory,
		arg.ID,
		arg.UserID,
		arg.Text,
		arg.Kind,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastSeenAt,
	)
	return err
}

const insertMemorySource = `-- name: InsertMemorySource :exec
INSERT OR IGNORE INTO memory_sources (memory_id, user_id, post_slug, created_at)
VALUES (?, ?, ?, ?)
`

type InsertMemorySourceParams struct {
	MemoryID  string
	UserID    string
	PostSlug  string
	CreatedAt string
}

// Re-approving a fact from a post it is already linked to is not an error and not a second
// link: the pair is the primary key, and the create's own last_seen_at bump is the record
// that it was seen again.
func (q *Queries) InsertMemorySource(ctx context.Context, arg InsertMemorySourceParams) error {
	_, err := q.db.ExecContext(ctx, insertMemorySource,
		arg.MemoryID,
		arg.UserID,
		arg.PostSlug,
		arg.CreatedAt,
	)
	return err
}

const insertMemoryTag = `-- name: InsertMemoryTag :exec
INSERT INTO memory_tags (memory_id, user_id, tag) VALUES (?, ?, ?)
`

type InsertMemoryTagParams struct {
	MemoryID string
	UserID   string
	Tag      string
}

func (q *Queries) InsertMemoryTag(ctx context.Context, arg InsertMemoryTagParams) error {
	_, err := q.db.ExecContext(ctx, insertMemoryTag, arg.MemoryID, arg.UserID, arg.Tag)
	return err
}

const listMemories = `-- name: ListMemories :many
SELECT id, user_id, text, kind, created_at, updated_at, last_seen_at
FROM memories
WHERE user_id = ?
ORDER BY last_seen_at DESC, created_at DESC, id
`

func (q *Queries) ListMemories(ctx context.Context, userID string) ([]Memory, error) {
	rows, err := q.db.QueryContext(ctx, listMemories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Memory
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Text,
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoryIDsForPost = `-- name: ListMemoryIDsForPost :many

SELECT memory_id FROM memory_sources WHERE user_id = ? AND post_slug = ?
`

type ListMemoryIDsForPostParams struct {
	UserID   string
	PostSlug string
}

// The post-delete rule (MEM-17) in three statements over one transaction: read which
// memories the post fed, drop the links, then delete exactly those that just lost their
// last one. A memory written by hand has no links at all and is untouched by the third
// statement, because it never appears in the first.
func (q *Queries) ListMemoryIDsForPost(ctx context.Context, arg ListMemoryIDsForPostParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listMemoryIDsForPost, arg.UserID, arg.PostSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var memory_id string
		if err := rows.Scan(&memory_id); err != nil {
			return nil, err
		}
		items = append(items, memory_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemorySources = `-- name: ListMemorySources :many
SELECT memory_id, post_slug
FROM memory_sources
WHERE user_id = ?
ORDER BY memory_id, created_at, post_slug
`

type ListMemorySourcesRow struct {
	MemoryID string
	PostSlug string
}

func (q *Queries) ListMemorySources(ctx context.Context, userID string) ([]ListMemorySourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMemorySources, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMemorySourcesRow
	for rows.Next() {
		var i ListMemorySourcesRow
		if err := rows.Scan(&i.MemoryID, &i.PostSlug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoryTags = `-- name: ListMemoryTags :many
SELECT memory_id, tag
FROM memory_tags
WHERE user_id = ?
ORDER BY memory_id, rowid
`

type ListMemoryTagsRow struct {
	MemoryID string
	Tag      string
}

func (q *Queries) ListMemoryTags(ctx context.Context, userID string) ([]ListMemoryTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMemoryTags, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMemoryTagsRow
	for rows.Next() {
		var i ListMemoryTagsRow
		if err := rows.Scan(&i.MemoryID, &i.Tag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourcesOfMemory = `-- name: ListSourcesOfMemory :many
SELECT post_slug
FROM memory_sources
WHERE memory_id = ? AND user_id = ?
ORDER BY created_at, post_slug
`

type ListSourcesOfMemoryParams struct {
	MemoryID string
	UserID   string
}

func (q *Queries) ListSourcesOfMemory(ctx context.Context, arg ListSourcesOfMemoryParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSourcesOfMemory, arg.MemoryID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var post_slug string
		if err := rows.Scan(&post_slug); err != nil {
			return nil, err
		}
		items = append(items, post_slug)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsOfMemory = `-- name: ListTagsOfMemory :many
SELECT tag FROM memory_tags WHERE memory_id = ? AND user_id = ? ORDER BY rowid
`

type ListTagsOfMemoryParams struct {
	MemoryID string
	UserID   string
}

func (q *Queries) ListTagsOfMemory(ctx context.Context, arg ListTagsOfMemoryParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTagsOfMemory, arg.MemoryID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const memoryByText = `-- name: MemoryByText :one
SELECT id, user_id, text, kind, created_at, updated_at, last_seen_at
FROM memories
WHERE user_id = ? AND text = ?
`

type MemoryByTextParams struct {
	UserID string
	Text   string
}

func (q *Queries) MemoryByText(ctx context.Context, arg MemoryByTextParams) (Memory, error) {
	row := q.db.QueryRowContext(ctx, memoryByText, arg.UserID, arg.Text)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Text,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const touchMemory = `-- name: TouchMemory :execrows

UPDATE memories SET last_seen_at = ? WHERE id = ? AND user_id = ?
`

type TouchMemoryParams struct {
	LastSeenAt string
	ID         string
	UserID     string
}

// A re-approval advances last_seen_at and NOTHING else: updated_at belongs to an authored
// edit, and retrieval breaks its ties on the former.
func (q *Queries) TouchMemory(ctx context.Context, arg TouchMemoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchMemory, arg.LastSeenAt, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchMemoryUpdatedAt = `-- name: TouchMemoryUpdatedAt :execrows
UPDATE memories SET updated_at = ? WHERE id = ? AND user_id = ?
`

type TouchMemoryUpdatedAtParams struct {
	UpdatedAt string
	ID        string
	UserID    string
}

func (q *Queries) TouchMemoryUpdatedAt(ctx context.Context, arg TouchMemoryUpdatedAtParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchMemoryUpdatedAt, arg.UpdatedAt, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateMemoryKind = `-- name: UpdateMemoryKind :execrows
UPDATE memories SET kind = ?, updated_at = ? WHERE id = ? AND user_id = ?
`

type UpdateMemoryKindParams struct {
	Kind      string
	UpdatedAt string
	ID        string
	UserID    string
}

func (q *Queries) UpdateMemoryKind(ctx context.Context, arg UpdateMemoryKindParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMemoryKind,
		arg.Kind,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateMemoryText = `-- name: UpdateMemoryText :execrows

UPDATE memories SET text = ?, updated_at = ? WHERE id = ? AND user_id = ?
`

type UpdateMemoryTextParams struct {
	Text      string
	UpdatedAt string
	ID        string
	UserID    string
}

// A text edit, a kind edit and a tag replacement are separate statements run in one
// transaction, so an edit that carries only one of them never names the others at all and
// two tabs editing two halves cannot overwrite each other.
func (q *Queries) UpdateMemoryText(ctx context.Context, arg UpdateMemoryTextParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMemoryText,
		arg.Text,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
