// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type Memory struct {
	ID         string
	UserID     string
	Text       string
	Kind       string
	CreatedAt  string
	UpdatedAt  string
	LastSeenAt string
}
