// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guidelines.sql

package sqlc

import (
	"context"
	"database/sql"
)

const bumpCandidate = `-- name: BumpCandidate :execrows
UPDATE guideline_candidates
SET occurrences = occurrences + 1, last_seen_at = ?
WHERE id = ? AND user_id = ?
`

type BumpCandidateParams struct {
	LastSeenAt string
	ID         string
	UserID     string
}

// A repeat. post_slug is deliberately NOT rewritten: the candidate names where it was first
// seen, and rewriting it would make the link jump between posts on every repeat.
func (q *Queries) BumpCandidate(ctx context.Context, arg BumpCandidateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, bumpCandidate, arg.LastSeenAt, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const candidateByText = `-- name: CandidateByText :one

SELECT id, user_id, text, post_slug, status, occurrences, first_seen_at, last_seen_at
FROM guideline_candidates
WHERE user_id = ? AND text = ?
`

type CandidateByTextParams struct {
	UserID string
	Text   string
}

// Guideline candidates (change 26). A candidate is one completed revision's instruction,
// recorded verbatim. Rows in every state are kept: 'approved' and 'dismissed' rows are what
// stop the same instruction from being recorded again, so nothing here deletes one.
func (q *Queries) CandidateByText(ctx context.Context, arg CandidateByTextParams) (GuidelineCandidate, error) {
	row := q.db.QueryRowContext(ctx, candidateByText, arg.UserID, arg.Text)
	var i GuidelineCandidate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Text,
		&i.PostSlug,
		&i.Status,
		&i.Occurrences,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}

const countGuidelines = `-- name: CountGuidelines :one
SELECT count(*) FROM guidelines WHERE user_id = ?
`

func (q *Queries) CountGuidelines(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGuidelines, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingCandidates = `-- name: CountPendingCandidates :one
SELECT count(*) FROM guideline_candidates WHERE user_id = ? AND status = 'pending'
`

func (q *Queries) CountPendingCandidates(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingCandidates, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteGuideline = `-- name: DeleteGuideline :execrows
DELETE FROM guidelines WHERE id = ? AND user_id = ?
`

type DeleteGuidelineParams struct {
	ID     string
	UserID string
}

// The schema cascades this guideline's own scope links. No template row is ever touched.
func (q *Queries) DeleteGuideline(ctx context.Context, arg DeleteGuidelineParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteGuideline, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteGuidelineScope = `-- name: DeleteGuidelineScope :exec
DELETE FROM guideline_templates WHERE guideline_id = ? AND user_id = ?
`

type DeleteGuidelineScopeParams struct {
	GuidelineID string
	UserID      string
}

func (q *Queries) DeleteGuidelineScope(ctx context.Context, arg DeleteGuidelineScopeParams) error {
	_, err := q.db.ExecContext(ctx, deleteGuidelineScope, arg.GuidelineID, arg.UserID)
	return err
}

const dropCandidatePostSlug = `-- name: DropCandidatePostSlug :exec
UPDATE guideline_candidates SET post_slug = NULL WHERE user_id = ? AND post_slug = ?
`

type DropCandidatePostSlugParams struct {
	UserID   string
	PostSlug sql.NullString
}

// Post deletion drops the link and keeps the text: nothing references a candidate's origin.
func (q *Queries) DropCandidatePostSlug(ctx context.Context, arg DropCandidatePostSlugParams) error {
	_, err := q.db.ExecContext(ctx, dropCandidatePostSlug, arg.UserID, arg.PostSlug)
	return err
}

const getGuideline = `-- name: GetGuideline :one
SELECT id, user_id, text, scope, created_at, updated_at
FROM guidelines
WHERE id = ? AND user_id = ?
`

type GetGuidelineParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetGuideline(ctx context.Context, arg GetGuidelineParams) (Guideline, error) {
	row := q.db.QueryRowContext(ctx, getGuideline, arg.ID, arg.UserID)
	var i Guideline
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Text,
		&i.Scope,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const guidelineByText = `-- name: GuidelineByText :one
SELECT id FROM guidelines WHERE user_id = ? AND text = ?
`

type GuidelineByTextParams struct {
	UserID string
	Text   string
}

func (q *Queries) GuidelineByText(ctx context.Context, arg GuidelineByTextParams) (string, error) {
	row := q.db.QueryRowContext(ctx, guidelineByText, arg.UserID, arg.Text)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertCandidate = `-- name: InsertCandidate :exec
INSERT INTO guideline_candidates (id, user_id, text, post_slug, status, occurrences, first_seen_at, last_seen_at)
VALUES (?, ?, ?, ?, ?, 1, ?, ?)
`

type InsertCandidateParams struct {
	ID          string
	UserID      string
	Text        string
	PostSlug    sql.NullString
	Status      string
	FirstSeenAt string
	LastSeenAt  string
}

func (q *Queries) InsertCandidate(ctx context.Context, arg InsertCandidateParams) error {
	_, err := q.db.ExecContext(ctx, insertCandidate,
		arg.ID,
		arg.UserID,
		arg.Text,
		arg.PostSlug,
		arg.Status,
		arg.FirstSeenAt,
		arg.LastSeenAt,
	)
	return err
}

const insertGuideline = `-- name: InsertGuideline :exec

INSERT INTO guidelines (id, user_id, text, scope, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertGuidelineParams struct {
	ID        string
	UserID    string
	Text      string
	Scope     string
	CreatedAt string
	UpdatedAt string
}

// ASCII only: sqlc slices these statements by byte offset but counts in runes, so a
// multi-byte character anywhere above rotates every generated query text.
//
// Writing guidelines. The account owns them; every statement names user_id, so a
// same-shaped id from another account reaches nothing rather than someone else's rule.
//
// templates is another context's table and is never joined here: the scope links carry only
// ids, and the names shown on screen are projected through the template directory port
// (ARCHITECTURE section 2.2). The ordering below is the INJECTION order: the global group
// first, then the scoped group, each by creation time. So the list, the prompt, and the
// experiment snapshot cannot disagree about what the writer sees first.
func (q *Queries) InsertGuideline(ctx context.Context, arg InsertGuidelineParams) error {
	_, err := q.db.ExecContext(ctx, insertGuideline,
		arg.ID,
		arg.UserID,
		arg.Text,
		arg.Scope,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertGuidelineScopeLink = `-- name: InsertGuidelineScopeLink :exec
INSERT INTO guideline_templates (guideline_id, template_id, user_id) VALUES (?, ?, ?)
`

type InsertGuidelineScopeLinkParams struct {
	GuidelineID string
	TemplateID  string
	UserID      string
}

func (q *Queries) InsertGuidelineScopeLink(ctx context.Context, arg InsertGuidelineScopeLinkParams) error {
	_, err := q.db.ExecContext(ctx, insertGuidelineScopeLink, arg.GuidelineID, arg.TemplateID, arg.UserID)
	return err
}

const listApplicableGuidelineTexts = `-- name: ListApplicableGuidelineTexts :many
SELECT g.text
FROM guidelines g
WHERE g.user_id = ?
  AND (
    g.scope = 'global'
    OR EXISTS (
      SELECT 1 FROM guideline_templates gt
      WHERE gt.guideline_id = g.id AND gt.user_id = g.user_id AND gt.template_id = ?
    )
  )
ORDER BY CASE g.scope WHEN 'global' THEN 0 ELSE 1 END, g.created_at, g.id
`

type ListApplicableGuidelineTextsParams struct {
	UserID     string
	TemplateID string
}

// The texts that apply to one post, in injection order. An empty template id is a post with
// no template: it matches no link row, so the result is the global group alone.
func (q *Queries) ListApplicableGuidelineTexts(ctx context.Context, arg ListApplicableGuidelineTextsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listApplicableGuidelineTexts, arg.UserID, arg.TemplateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var text string
		if err := rows.Scan(&text); err != nil {
			return nil, err
		}
		items = append(items, text)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuidelineScope = `-- name: ListGuidelineScope :many
SELECT template_id
FROM guideline_templates
WHERE guideline_id = ? AND user_id = ?
ORDER BY template_id
`

type ListGuidelineScopeParams struct {
	GuidelineID string
	UserID      string
}

func (q *Queries) ListGuidelineScope(ctx context.Context, arg ListGuidelineScopeParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listGuidelineScope, arg.GuidelineID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var template_id string
		if err := rows.Scan(&template_id); err != nil {
			return nil, err
		}
		items = append(items, template_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuidelineTemplateLinks = `-- name: ListGuidelineTemplateLinks :many
SELECT guideline_id, template_id
FROM guideline_templates
WHERE user_id = ?
ORDER BY guideline_id, template_id
`

type ListGuidelineTemplateLinksRow struct {
	GuidelineID string
	TemplateID  string
}

func (q *Queries) ListGuidelineTemplateLinks(ctx context.Context, userID string) ([]ListGuidelineTemplateLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, listGuidelineTemplateLinks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGuidelineTemplateLinksRow
	for rows.Next() {
		var i ListGuidelineTemplateLinksRow
		if err := rows.Scan(&i.GuidelineID, &i.TemplateID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuidelines = `-- name: ListGuidelines :many
SELECT id, user_id, text, scope, created_at, updated_at
FROM guidelines
WHERE user_id = ?
ORDER BY CASE scope WHEN 'global' THEN 0 ELSE 1 END, created_at, id
`

func (q *Queries) ListGuidelines(ctx context.Context, userID string) ([]Guideline, error) {
	rows, err := q.db.QueryContext(ctx, listGuidelines, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Guideline
	for rows.Next() {
		var i Guideline
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Text,
			&i.Scope,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingCandidates = `-- name: ListPendingCandidates :many
SELECT id, user_id, text, post_slug, status, occurrences, first_seen_at, last_seen_at
FROM guideline_candidates
WHERE user_id = ? AND status = 'pending'
ORDER BY occurrences DESC, last_seen_at DESC, id
`

// Review order: the most-repeated correction first, then the most recent. Exactly the order
// idx_guideline_candidates_review serves.
func (q *Queries) ListPendingCandidates(ctx context.Context, userID string) ([]GuidelineCandidate, error) {
	rows, err := q.db.QueryContext(ctx, listPendingCandidates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GuidelineCandidate
	for rows.Next() {
		var i GuidelineCandidate
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Text,
			&i.PostSlug,
			&i.Status,
			&i.Occurrences,
			&i.FirstSeenAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCandidateStatus = `-- name: SetCandidateStatus :execrows
UPDATE guideline_candidates
SET status = ?
WHERE id = ? AND user_id = ? AND status = 'pending'
`

type SetCandidateStatusParams struct {
	Status string
	ID     string
	UserID string
}

// Only a PENDING row moves. A candidate the user already ruled on is terminal: without this
// guard a stale tab could approve one twice, or dismiss one that was already approved.
func (q *Queries) SetCandidateStatus(ctx context.Context, arg SetCandidateStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setCandidateStatus, arg.Status, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setCandidateStatusByText = `-- name: SetCandidateStatusByText :exec
UPDATE guideline_candidates
SET status = ?
WHERE user_id = ? AND text = ? AND status = 'pending'
`

type SetCandidateStatusByTextParams struct {
	Status string
	UserID string
	Text   string
}

// Approval by text, which is what marks the candidate a just-completed revision recorded
// without the client having to learn its id. Only a pending row is moved: an already
// dismissed one stays dismissed.
func (q *Queries) SetCandidateStatusByText(ctx context.Context, arg SetCandidateStatusByTextParams) error {
	_, err := q.db.ExecContext(ctx, setCandidateStatusByText, arg.Status, arg.UserID, arg.Text)
	return err
}

const updateGuidelineScope = `-- name: UpdateGuidelineScope :execrows
UPDATE guidelines SET scope = ?, updated_at = ? WHERE id = ? AND user_id = ?
`

type UpdateGuidelineScopeParams struct {
	Scope     string
	UpdatedAt string
	ID        string
	UserID    string
}

func (q *Queries) UpdateGuidelineScope(ctx context.Context, arg UpdateGuidelineScopeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateGuidelineScope,
		arg.Scope,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateGuidelineText = `-- name: UpdateGuidelineText :execrows

UPDATE guidelines SET text = ?, updated_at = ? WHERE id = ? AND user_id = ?
`

type UpdateGuidelineTextParams struct {
	Text      string
	UpdatedAt string
	ID        string
	UserID    string
}

// A text edit and a scope replacement are separate statements run in one transaction, so an
// edit that carries only one of them never names the other at all, and two tabs editing the two
// halves cannot overwrite each other, and no read-modify-write can put a stale value back.
func (q *Queries) UpdateGuidelineText(ctx context.Context, arg UpdateGuidelineTextParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateGuidelineText,
		arg.Text,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
