// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type Guideline struct {
	ID        string
	UserID    string
	Text      string
	Scope     string
	CreatedAt string
	UpdatedAt string
}
