// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: purposes.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countPostsForPurpose = `-- name: CountPostsForPurpose :one
SELECT count(*) FROM posts WHERE purpose_id = ? AND user_id = ?
`

type CountPostsForPurposeParams struct {
	PurposeID sql.NullString
	UserID    string
}

func (q *Queries) CountPostsForPurpose(ctx context.Context, arg CountPostsForPurposeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPostsForPurpose, arg.PurposeID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePurpose = `-- name: DeletePurpose :execrows
DELETE FROM purposes WHERE id = ? AND user_id = ?
`

type DeletePurposeParams struct {
	ID     string
	UserID string
}

// The schema's BEFORE DELETE trigger detaches the posts that named it, in this statement's
// transaction. The posts themselves are never touched from here.
func (q *Queries) DeletePurpose(ctx context.Context, arg DeletePurposeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePurpose, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPurpose = `-- name: GetPurpose :one
SELECT p.id, p.user_id, p.name, p.description, p.instructions, p.created_at, p.updated_at,
       (SELECT count(*) FROM posts po WHERE po.purpose_id = p.id AND po.user_id = p.user_id) AS post_count
FROM purposes p
WHERE p.id = ? AND p.user_id = ?
`

type GetPurposeParams struct {
	ID     string
	UserID string
}

type GetPurposeRow struct {
	ID           string
	UserID       string
	Name         string
	Description  string
	Instructions string
	CreatedAt    string
	UpdatedAt    string
	PostCount    int64
}

func (q *Queries) GetPurpose(ctx context.Context, arg GetPurposeParams) (GetPurposeRow, error) {
	row := q.db.QueryRowContext(ctx, getPurpose, arg.ID, arg.UserID)
	var i GetPurposeRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Instructions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PostCount,
	)
	return i, err
}

const insertPurpose = `-- name: InsertPurpose :exec

INSERT INTO purposes (id, user_id, name, description, instructions, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertPurposeParams struct {
	ID           string
	UserID       string
	Name         string
	Description  string
	Instructions string
	CreatedAt    string
	UpdatedAt    string
}

// Purposes. The account owns the directory; every statement names user_id, so a
// same-shaped id from another account reaches nothing rather than someone else's brief.
//
// posts is another context's table and is never joined here for its own sake: the reads
// below touch only posts.purpose_id, the foreign key posts itself declares, which is what
// the count and the detach are about (ARCHITECTURE section 2.2).
func (q *Queries) InsertPurpose(ctx context.Context, arg InsertPurposeParams) error {
	_, err := q.db.ExecContext(ctx, insertPurpose,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Instructions,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listPurposes = `-- name: ListPurposes :many
SELECT p.id, p.user_id, p.name, p.description, p.instructions, p.created_at, p.updated_at,
       (SELECT count(*) FROM posts po WHERE po.purpose_id = p.id AND po.user_id = p.user_id) AS post_count
FROM purposes p
WHERE p.user_id = ?
ORDER BY p.name, p.id
`

type ListPurposesRow struct {
	ID           string
	UserID       string
	Name         string
	Description  string
	Instructions string
	CreatedAt    string
	UpdatedAt    string
	PostCount    int64
}

func (q *Queries) ListPurposes(ctx context.Context, userID string) ([]ListPurposesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPurposes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPurposesRow
	for rows.Next() {
		var i ListPurposesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Instructions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PostCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePurposeDescription = `-- name: UpdatePurposeDescription :execrows
UPDATE purposes SET description = ?, updated_at = ? WHERE id = ? AND user_id = ?
`

type UpdatePurposeDescriptionParams struct {
	Description string
	UpdatedAt   string
	ID          string
	UserID      string
}

func (q *Queries) UpdatePurposeDescription(ctx context.Context, arg UpdatePurposeDescriptionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePurposeDescription,
		arg.Description,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePurposeInstructions = `-- name: UpdatePurposeInstructions :execrows
UPDATE purposes SET instructions = ?, updated_at = ? WHERE id = ? AND user_id = ?
`

type UpdatePurposeInstructionsParams struct {
	Instructions string
	UpdatedAt    string
	ID           string
	UserID       string
}

func (q *Queries) UpdatePurposeInstructions(ctx context.Context, arg UpdatePurposeInstructionsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePurposeInstructions,
		arg.Instructions,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePurposeName = `-- name: UpdatePurposeName :execrows

UPDATE purposes SET name = ?, updated_at = ? WHERE id = ? AND user_id = ?
`

type UpdatePurposeNameParams struct {
	Name      string
	UpdatedAt string
	ID        string
	UserID    string
}

// An edit is one statement PER PRESENT FIELD, run together in one transaction, rather than
// one statement that writes all three. A field the request did not send is then never named
// by any statement at all, so two fields edited from two tabs cannot overwrite each other
// and no read-modify-write can put a stale value back. (A single COALESCE statement would
// say the same thing, but sqlc types a NOT NULL column's parameter as a plain string, which
// leaves no way to express "absent".)
func (q *Queries) UpdatePurposeName(ctx context.Context, arg UpdatePurposeNameParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePurposeName,
		arg.Name,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
