// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package sqlc

import (
	"context"
	"database/sql"
)

const activateClip = `-- name: ActivateClip :execrows
UPDATE generation_jobs SET dispatch_ready=1 WHERE user_id=? AND id=? AND kind IN ('generate_clip','render_clip') AND status='queued' AND dispatch_ready=0 AND cancel_requested_at IS NULL
`

type ActivateClipParams struct {
	UserID string
	ID     string
}

func (q *Queries) ActivateClip(ctx context.Context, arg ActivateClipParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, activateClip, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const activeForClip = `-- name: ActiveForClip :one
SELECT id, post_slug, user_id, voice_id, kind, status, stage, progress_done, progress_total, error, observe_model, write_model, payload, created_at, updated_at, started_at, finished_at, target_language, error_reason, error_params, technical_detail, clip_project_id, dispatch_ready, cancel_requested_at, cancellation_policy_version FROM generation_jobs WHERE user_id=? AND clip_project_id=? AND status IN ('queued','running') LIMIT 1
`

type ActiveForClipParams struct {
	UserID        string
	ClipProjectID sql.NullString
}

func (q *Queries) ActiveForClip(ctx context.Context, arg ActiveForClipParams) (GenerationJob, error) {
	row := q.db.QueryRowContext(ctx, activeForClip, arg.UserID, arg.ClipProjectID)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.PostSlug,
		&i.UserID,
		&i.VoiceID,
		&i.Kind,
		&i.Status,
		&i.Stage,
		&i.ProgressDone,
		&i.ProgressTotal,
		&i.Error,
		&i.ObserveModel,
		&i.WriteModel,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.TargetLanguage,
		&i.ErrorReason,
		&i.ErrorParams,
		&i.TechnicalDetail,
		&i.ClipProjectID,
		&i.DispatchReady,
		&i.CancelRequestedAt,
		&i.CancellationPolicyVersion,
	)
	return i, err
}

const activeForPost = `-- name: ActiveForPost :one
SELECT id, post_slug, user_id, voice_id, kind, status, stage, progress_done, progress_total, error, observe_model, write_model, payload, created_at, updated_at, started_at, finished_at, target_language, error_reason, error_params, technical_detail, clip_project_id, dispatch_ready, cancel_requested_at, cancellation_policy_version FROM generation_jobs
WHERE post_slug = ? AND status IN ('queued', 'running')
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) ActiveForPost(ctx context.Context, postSlug sql.NullString) (GenerationJob, error) {
	row := q.db.QueryRowContext(ctx, activeForPost, postSlug)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.PostSlug,
		&i.UserID,
		&i.VoiceID,
		&i.Kind,
		&i.Status,
		&i.Stage,
		&i.ProgressDone,
		&i.ProgressTotal,
		&i.Error,
		&i.ObserveModel,
		&i.WriteModel,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.TargetLanguage,
		&i.ErrorReason,
		&i.ErrorParams,
		&i.TechnicalDetail,
		&i.ClipProjectID,
		&i.DispatchReady,
		&i.CancelRequestedAt,
		&i.CancellationPolicyVersion,
	)
	return i, err
}

const activeForPostUser = `-- name: ActiveForPostUser :one
SELECT id, post_slug, user_id, voice_id, kind, status, stage, progress_done, progress_total, error, observe_model, write_model, payload, created_at, updated_at, started_at, finished_at, target_language, error_reason, error_params, technical_detail, clip_project_id, dispatch_ready, cancel_requested_at, cancellation_policy_version FROM generation_jobs
WHERE post_slug = ? AND user_id = ? AND status IN ('queued', 'running')
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type ActiveForPostUserParams struct {
	PostSlug sql.NullString
	UserID   string
}

func (q *Queries) ActiveForPostUser(ctx context.Context, arg ActiveForPostUserParams) (GenerationJob, error) {
	row := q.db.QueryRowContext(ctx, activeForPostUser, arg.PostSlug, arg.UserID)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.PostSlug,
		&i.UserID,
		&i.VoiceID,
		&i.Kind,
		&i.Status,
		&i.Stage,
		&i.ProgressDone,
		&i.ProgressTotal,
		&i.Error,
		&i.ObserveModel,
		&i.WriteModel,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.TargetLanguage,
		&i.ErrorReason,
		&i.ErrorParams,
		&i.TechnicalDetail,
		&i.ClipProjectID,
		&i.DispatchReady,
		&i.CancelRequestedAt,
		&i.CancellationPolicyVersion,
	)
	return i, err
}

const activeForUserKind = `-- name: ActiveForUserKind :one
SELECT id, post_slug, user_id, voice_id, kind, status, stage, progress_done, progress_total, error, observe_model, write_model, payload, created_at, updated_at, started_at, finished_at, target_language, error_reason, error_params, technical_detail, clip_project_id, dispatch_ready, cancel_requested_at, cancellation_policy_version FROM generation_jobs
WHERE user_id = ? AND kind = ? AND post_slug IS NULL AND clip_project_id IS NULL
  AND status IN ('queued', 'running')
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type ActiveForUserKindParams struct {
	UserID string
	Kind   string
}

func (q *Queries) ActiveForUserKind(ctx context.Context, arg ActiveForUserKindParams) (GenerationJob, error) {
	row := q.db.QueryRowContext(ctx, activeForUserKind, arg.UserID, arg.Kind)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.PostSlug,
		&i.UserID,
		&i.VoiceID,
		&i.Kind,
		&i.Status,
		&i.Stage,
		&i.ProgressDone,
		&i.ProgressTotal,
		&i.Error,
		&i.ObserveModel,
		&i.WriteModel,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.TargetLanguage,
		&i.ErrorReason,
		&i.ErrorParams,
		&i.TechnicalDetail,
		&i.ClipProjectID,
		&i.DispatchReady,
		&i.CancelRequestedAt,
		&i.CancellationPolicyVersion,
	)
	return i, err
}

const activeForVoice = `-- name: ActiveForVoice :one
SELECT id, post_slug, user_id, voice_id, kind, status, stage, progress_done, progress_total, error, observe_model, write_model, payload, created_at, updated_at, started_at, finished_at, target_language, error_reason, error_params, technical_detail, clip_project_id, dispatch_ready, cancel_requested_at, cancellation_policy_version FROM generation_jobs
WHERE voice_id = ? AND status IN ('queued', 'running')
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// Anything queued or running that was frozen to this voice, post-backed or not: its result
// would land in the voice, so a soft delete has to wait for it.
func (q *Queries) ActiveForVoice(ctx context.Context, voiceID sql.NullString) (GenerationJob, error) {
	row := q.db.QueryRowContext(ctx, activeForVoice, voiceID)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.PostSlug,
		&i.UserID,
		&i.VoiceID,
		&i.Kind,
		&i.Status,
		&i.Stage,
		&i.ProgressDone,
		&i.ProgressTotal,
		&i.Error,
		&i.ObserveModel,
		&i.WriteModel,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.TargetLanguage,
		&i.ErrorReason,
		&i.ErrorParams,
		&i.TechnicalDetail,
		&i.ClipProjectID,
		&i.DispatchReady,
		&i.CancelRequestedAt,
		&i.CancellationPolicyVersion,
	)
	return i, err
}

const activeForVoiceKind = `-- name: ActiveForVoiceKind :one
SELECT id, post_slug, user_id, voice_id, kind, status, stage, progress_done, progress_total, error, observe_model, write_model, payload, created_at, updated_at, started_at, finished_at, target_language, error_reason, error_params, technical_detail, clip_project_id, dispatch_ready, cancel_requested_at, cancellation_policy_version FROM generation_jobs
WHERE voice_id = ? AND kind = ?
  AND status IN ('queued', 'running')
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type ActiveForVoiceKindParams struct {
	VoiceID sql.NullString
	Kind    string
}

// Voice-owned work is guarded per voice: two voices may analyze at the same time, while one
// voice still cannot run two of the same kind. Learning/comparison jobs may carry a post.
func (q *Queries) ActiveForVoiceKind(ctx context.Context, arg ActiveForVoiceKindParams) (GenerationJob, error) {
	row := q.db.QueryRowContext(ctx, activeForVoiceKind, arg.VoiceID, arg.Kind)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.PostSlug,
		&i.UserID,
		&i.VoiceID,
		&i.Kind,
		&i.Status,
		&i.Stage,
		&i.ProgressDone,
		&i.ProgressTotal,
		&i.Error,
		&i.ObserveModel,
		&i.WriteModel,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.TargetLanguage,
		&i.ErrorReason,
		&i.ErrorParams,
		&i.TechnicalDetail,
		&i.ClipProjectID,
		&i.DispatchReady,
		&i.CancelRequestedAt,
		&i.CancellationPolicyVersion,
	)
	return i, err
}

const activeModelExperiment = `-- name: ActiveModelExperiment :one
SELECT id, post_slug, user_id, voice_id, kind, status, stage, progress_done, progress_total, error, observe_model, write_model, payload, created_at, updated_at, started_at, finished_at, target_language, error_reason, error_params, technical_detail, clip_project_id, dispatch_ready, cancel_requested_at, cancellation_policy_version FROM generation_jobs
WHERE kind = 'model_experiment' AND payload = ? AND status IN ('queued', 'running')
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) ActiveModelExperiment(ctx context.Context, payload string) (GenerationJob, error) {
	row := q.db.QueryRowContext(ctx, activeModelExperiment, payload)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.PostSlug,
		&i.UserID,
		&i.VoiceID,
		&i.Kind,
		&i.Status,
		&i.Stage,
		&i.ProgressDone,
		&i.ProgressTotal,
		&i.Error,
		&i.ObserveModel,
		&i.WriteModel,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.TargetLanguage,
		&i.ErrorReason,
		&i.ErrorParams,
		&i.TechnicalDetail,
		&i.ClipProjectID,
		&i.DispatchReady,
		&i.CancelRequestedAt,
		&i.CancellationPolicyVersion,
	)
	return i, err
}

const authorizeClipDispatch = `-- name: AuthorizeClipDispatch :execrows
UPDATE generation_jobs SET updated_at=updated_at
WHERE id=? AND user_id=? AND kind='generate_clip' AND status='running' AND cancel_requested_at IS NULL
`

type AuthorizeClipDispatchParams struct {
	ID     string
	UserID string
}

func (q *Queries) AuthorizeClipDispatch(ctx context.Context, arg AuthorizeClipDispatchParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, authorizeClipDispatch, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const failQueuedJob = `-- name: FailQueuedJob :execrows
UPDATE generation_jobs
SET status = 'failed', error = NULL, error_reason = ?, error_params = ?, technical_detail = ?,
    finished_at = ?, updated_at = ?
WHERE id = ? AND user_id = ? AND status = 'queued' AND cancel_requested_at IS NULL
`

type FailQueuedJobParams struct {
	ErrorReason     sql.NullString
	ErrorParams     sql.NullString
	TechnicalDetail sql.NullString
	FinishedAt      sql.NullString
	UpdatedAt       string
	ID              string
	UserID          string
}

func (q *Queries) FailQueuedJob(ctx context.Context, arg FailQueuedJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failQueuedJob,
		arg.ErrorReason,
		arg.ErrorParams,
		arg.TechnicalDetail,
		arg.FinishedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finishJob = `-- name: FinishJob :execrows
UPDATE generation_jobs
SET status = CASE WHEN cancel_requested_at IS NOT NULL THEN 'cancelled' ELSE ?1 END,
    error = NULL,
    error_reason = CASE WHEN cancel_requested_at IS NULL THEN ?2 ELSE NULL END,
    error_params = CASE WHEN cancel_requested_at IS NULL THEN ?3 ELSE NULL END,
    technical_detail = CASE WHEN cancel_requested_at IS NULL THEN ?4 ELSE NULL END,
    finished_at = ?5, updated_at = ?6
WHERE id = ?7 AND status = 'running'
`

type FinishJobParams struct {
	Status          string
	ErrorReason     sql.NullString
	ErrorParams     sql.NullString
	TechnicalDetail sql.NullString
	FinishedAt      sql.NullString
	UpdatedAt       string
	ID              string
}

func (q *Queries) FinishJob(ctx context.Context, arg FinishJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishJob,
		arg.Status,
		arg.ErrorReason,
		arg.ErrorParams,
		arg.TechnicalDetail,
		arg.FinishedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, post_slug, user_id, voice_id, kind, status, stage, progress_done, progress_total, error, observe_model, write_model, payload, created_at, updated_at, started_at, finished_at, target_language, error_reason, error_params, technical_detail, clip_project_id, dispatch_ready, cancel_requested_at, cancellation_policy_version FROM generation_jobs WHERE id = ?
`

func (q *Queries) GetJobByID(ctx context.Context, id string) (GenerationJob, error) {
	row := q.db.QueryRowContext(ctx, getJobByID, id)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.PostSlug,
		&i.UserID,
		&i.VoiceID,
		&i.Kind,
		&i.Status,
		&i.Stage,
		&i.ProgressDone,
		&i.ProgressTotal,
		&i.Error,
		&i.ObserveModel,
		&i.WriteModel,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.TargetLanguage,
		&i.ErrorReason,
		&i.ErrorParams,
		&i.TechnicalDetail,
		&i.ClipProjectID,
		&i.DispatchReady,
		&i.CancelRequestedAt,
		&i.CancellationPolicyVersion,
	)
	return i, err
}

const insertJob = `-- name: InsertJob :exec
INSERT INTO generation_jobs (
    id, post_slug, user_id, voice_id, clip_project_id, dispatch_ready, cancellation_policy_version, kind, status, stage, progress_done, progress_total,
    error, observe_model, write_model, target_language, payload, created_at, updated_at,
    started_at, finished_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'queued', NULL, 0, 0, NULL, ?, ?, ?, ?, ?, ?, NULL, NULL)
`

type InsertJobParams struct {
	ID                        string
	PostSlug                  sql.NullString
	UserID                    string
	VoiceID                   sql.NullString
	ClipProjectID             sql.NullString
	DispatchReady             int64
	CancellationPolicyVersion int64
	Kind                      string
	ObserveModel              sql.NullString
	WriteModel                sql.NullString
	TargetLanguage            sql.NullString
	Payload                   string
	CreatedAt                 string
	UpdatedAt                 string
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) error {
	_, err := q.db.ExecContext(ctx, insertJob,
		arg.ID,
		arg.PostSlug,
		arg.UserID,
		arg.VoiceID,
		arg.ClipProjectID,
		arg.DispatchReady,
		arg.CancellationPolicyVersion,
		arg.Kind,
		arg.ObserveModel,
		arg.WriteModel,
		arg.TargetLanguage,
		arg.Payload,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const latestForClip = `-- name: LatestForClip :one
SELECT id, post_slug, user_id, voice_id, kind, status, stage, progress_done, progress_total, error, observe_model, write_model, payload, created_at, updated_at, started_at, finished_at, target_language, error_reason, error_params, technical_detail, clip_project_id, dispatch_ready, cancel_requested_at, cancellation_policy_version FROM generation_jobs WHERE user_id=? AND clip_project_id=? ORDER BY created_at DESC,id DESC LIMIT 1
`

type LatestForClipParams struct {
	UserID        string
	ClipProjectID sql.NullString
}

func (q *Queries) LatestForClip(ctx context.Context, arg LatestForClipParams) (GenerationJob, error) {
	row := q.db.QueryRowContext(ctx, latestForClip, arg.UserID, arg.ClipProjectID)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.PostSlug,
		&i.UserID,
		&i.VoiceID,
		&i.Kind,
		&i.Status,
		&i.Stage,
		&i.ProgressDone,
		&i.ProgressTotal,
		&i.Error,
		&i.ObserveModel,
		&i.WriteModel,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.TargetLanguage,
		&i.ErrorReason,
		&i.ErrorParams,
		&i.TechnicalDetail,
		&i.ClipProjectID,
		&i.DispatchReady,
		&i.CancelRequestedAt,
		&i.CancellationPolicyVersion,
	)
	return i, err
}

const pickNextQueued = `-- name: PickNextQueued :one
UPDATE generation_jobs
SET status = 'running',
    stage = CASE kind
        WHEN 'generate_clip' THEN 'prepare'
        WHEN 'analyze_voice' THEN 'analyze'
        WHEN 'learn_voice' THEN 'learn'
        WHEN 'compare_voice_rule' THEN 'compare_rule'
        WHEN 'validate_voice_profile' THEN 'validate_profile'
        WHEN 'revise' THEN 'write'
        ELSE 'observe'
    END,
    error = NULL,
    error_reason = NULL,
    error_params = NULL,
    technical_detail = NULL,
    started_at = ?,
    updated_at = ?
WHERE id = (
    SELECT id FROM generation_jobs
    WHERE status = 'queued' AND dispatch_ready=1 AND cancel_requested_at IS NULL
    ORDER BY created_at, id
    LIMIT 1
)
RETURNING id, post_slug, user_id, voice_id, kind, status, stage, progress_done, progress_total, error, observe_model, write_model, payload, created_at, updated_at, started_at, finished_at, target_language, error_reason, error_params, technical_detail, clip_project_id, dispatch_ready, cancel_requested_at, cancellation_policy_version
`

type PickNextQueuedParams struct {
	StartedAt sql.NullString
	UpdatedAt string
}

func (q *Queries) PickNextQueued(ctx context.Context, arg PickNextQueuedParams) (GenerationJob, error) {
	row := q.db.QueryRowContext(ctx, pickNextQueued, arg.StartedAt, arg.UpdatedAt)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.PostSlug,
		&i.UserID,
		&i.VoiceID,
		&i.Kind,
		&i.Status,
		&i.Stage,
		&i.ProgressDone,
		&i.ProgressTotal,
		&i.Error,
		&i.ObserveModel,
		&i.WriteModel,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.TargetLanguage,
		&i.ErrorReason,
		&i.ErrorParams,
		&i.TechnicalDetail,
		&i.ClipProjectID,
		&i.DispatchReady,
		&i.CancelRequestedAt,
		&i.CancellationPolicyVersion,
	)
	return i, err
}

const recoverClipCancellations = `-- name: RecoverClipCancellations :execrows
UPDATE generation_jobs SET status='cancelled',finished_at=?1,updated_at=?1,
 error=NULL,error_reason=NULL,error_params=NULL,technical_detail=NULL
WHERE status IN ('queued','running') AND cancel_requested_at IS NOT NULL
 AND kind IN ('generate_clip','render_clip')
`

func (q *Queries) RecoverClipCancellations(ctx context.Context, now sql.NullString) (int64, error) {
	result, err := q.db.ExecContext(ctx, recoverClipCancellations, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const requestClipCancellation = `-- name: RequestClipCancellation :execrows
UPDATE generation_jobs SET cancel_requested_at=?1, updated_at=?1,
 status=CASE WHEN status='queued' THEN 'cancelled' ELSE status END,
 finished_at=CASE WHEN status='queued' THEN ?1 ELSE finished_at END
WHERE id=?2 AND user_id=?3 AND clip_project_id=?4
 AND status IN ('queued','running') AND cancel_requested_at IS NULL
 AND (kind='render_clip' OR (kind='generate_clip' AND cancellation_policy_version=1))
`

type RequestClipCancellationParams struct {
	Now       sql.NullString
	ID        string
	UserID    string
	ProjectID sql.NullString
}

func (q *Queries) RequestClipCancellation(ctx context.Context, arg RequestClipCancellationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, requestClipCancellation,
		arg.Now,
		arg.ID,
		arg.UserID,
		arg.ProjectID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const sweepQueuedPersonalization = `-- name: SweepQueuedPersonalization :execrows
UPDATE generation_jobs
SET status = 'failed', error = NULL, error_reason = ?, error_params = ?, technical_detail = ?,
    finished_at = ?, updated_at = ?
WHERE status = 'queued'
  AND kind IN ('learn_voice', 'compare_voice_rule', 'validate_voice_profile', 'seed_voice')
`

type SweepQueuedPersonalizationParams struct {
	ErrorReason     sql.NullString
	ErrorParams     sql.NullString
	TechnicalDetail sql.NullString
	FinishedAt      sql.NullString
	UpdatedAt       string
}

func (q *Queries) SweepQueuedPersonalization(ctx context.Context, arg SweepQueuedPersonalizationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, sweepQueuedPersonalization,
		arg.ErrorReason,
		arg.ErrorParams,
		arg.TechnicalDetail,
		arg.FinishedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const sweepRunning = `-- name: SweepRunning :execrows
UPDATE generation_jobs
SET status = 'failed', error = NULL, error_reason = ?, error_params = ?, technical_detail = ?,
    finished_at = ?, updated_at = ?
WHERE status = 'running' AND cancel_requested_at IS NULL
`

type SweepRunningParams struct {
	ErrorReason     sql.NullString
	ErrorParams     sql.NullString
	TechnicalDetail sql.NullString
	FinishedAt      sql.NullString
	UpdatedAt       string
}

func (q *Queries) SweepRunning(ctx context.Context, arg SweepRunningParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, sweepRunning,
		arg.ErrorReason,
		arg.ErrorParams,
		arg.TechnicalDetail,
		arg.FinishedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const sweepUnactivatedClips = `-- name: SweepUnactivatedClips :execrows
UPDATE generation_jobs SET status='failed', error_reason=?, error_params=?, technical_detail=?, finished_at=?, updated_at=? WHERE kind IN ('generate_clip','render_clip') AND status='queued' AND dispatch_ready=0 AND cancel_requested_at IS NULL
`

type SweepUnactivatedClipsParams struct {
	ErrorReason     sql.NullString
	ErrorParams     sql.NullString
	TechnicalDetail sql.NullString
	FinishedAt      sql.NullString
	UpdatedAt       string
}

func (q *Queries) SweepUnactivatedClips(ctx context.Context, arg SweepUnactivatedClipsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, sweepUnactivatedClips,
		arg.ErrorReason,
		arg.ErrorParams,
		arg.TechnicalDetail,
		arg.FinishedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateProgress = `-- name: UpdateProgress :exec
UPDATE generation_jobs
SET stage = ?, progress_done = ?, progress_total = ?, updated_at = ?
WHERE id = ? AND status = 'running' AND cancel_requested_at IS NULL
`

type UpdateProgressParams struct {
	Stage         sql.NullString
	ProgressDone  int64
	ProgressTotal int64
	UpdatedAt     string
	ID            string
}

func (q *Queries) UpdateProgress(ctx context.Context, arg UpdateProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateProgress,
		arg.Stage,
		arg.ProgressDone,
		arg.ProgressTotal,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
