// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type GenerationJob struct {
	ID            string
	PostSlug      sql.NullString
	UserID        string
	Kind          string
	Status        string
	Stage         sql.NullString
	ProgressDone  int64
	ProgressTotal int64
	Error         sql.NullString
	ObserveModel  sql.NullString
	WriteModel    sql.NullString
	Payload       string
	CreatedAt     string
	UpdatedAt     string
	StartedAt     sql.NullString
	FinishedAt    sql.NullString
}
