// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settled_charge.sql

package sqlc

import (
	"context"
)

const settledChargeForJob = `-- name: SettledChargeForJob :one
SELECT CAST(CASE WHEN COALESCE((SELECT SUM(h.credits) FROM credit_hold_lots h WHERE h.job_id=a.job_id),0)=0
 THEN 0 ELSE a.settled_credits END AS INTEGER) AS charge
FROM usage_admissions a
WHERE a.user_id=? AND a.job_id=? AND a.settled_at IS NOT NULL AND a.settled_credits IS NOT NULL
`

type SettledChargeForJobParams struct {
	UserID string
	JobID  string
}

func (q *Queries) SettledChargeForJob(ctx context.Context, arg SettledChargeForJobParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, settledChargeForJob, arg.UserID, arg.JobID)
	var charge int64
	err := row.Scan(&charge)
	return charge, err
}
