// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: units.sql

package sqlc

import (
	"context"
)

const claimBoundedUnitCall = `-- name: ClaimBoundedUnitCall :execrows
INSERT INTO usage_unit_calls(id,job_id,budget_fingerprint,created_at,input_characters,input_digest)
SELECT ?1,?2,?3,?4,?5,?6
WHERE (SELECT COUNT(*) FROM usage_unit_calls prior WHERE prior.job_id=?2 AND prior.budget_fingerprint=?3) < CAST(?7 AS INTEGER)
AND (SELECT COALESCE(SUM(input_characters),0) FROM usage_unit_calls prior WHERE prior.job_id=?2 AND prior.budget_fingerprint=?3) + CAST(?5 AS INTEGER) <= CAST(?8 AS INTEGER)
`

type ClaimBoundedUnitCallParams struct {
	ID            string
	Job           string
	Fingerprint   string
	Now           string
	Characters    int64
	InputDigest   string
	MaxCalls      int64
	MaxCharacters int64
}

func (q *Queries) ClaimBoundedUnitCall(ctx context.Context, arg ClaimBoundedUnitCallParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimBoundedUnitCall,
		arg.ID,
		arg.Job,
		arg.Fingerprint,
		arg.Now,
		arg.Characters,
		arg.InputDigest,
		arg.MaxCalls,
		arg.MaxCharacters,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const claimUnitCall = `-- name: ClaimUnitCall :execrows
INSERT INTO usage_unit_calls (id, job_id, budget_fingerprint, created_at)
SELECT ?1, ?2, ?3, ?4
WHERE (SELECT COUNT(*) FROM usage_unit_calls AS prior WHERE prior.job_id = ?2 AND prior.budget_fingerprint = ?3) < CAST(?5 AS INTEGER)
`

type ClaimUnitCallParams struct {
	ID           string
	JobID        string
	Fingerprint  string
	CreatedAt    string
	MaximumCalls int64
}

func (q *Queries) ClaimUnitCall(ctx context.Context, arg ClaimUnitCallParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimUnitCall,
		arg.ID,
		arg.JobID,
		arg.Fingerprint,
		arg.CreatedAt,
		arg.MaximumCalls,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const consumeUnitQuote = `-- name: ConsumeUnitQuote :execrows
UPDATE usage_unit_quotes SET consumed_job_id = ? WHERE id = ? AND consumed_job_id = ''
`

type ConsumeUnitQuoteParams struct {
	ConsumedJobID string
	ID            string
}

func (q *Queries) ConsumeUnitQuote(ctx context.Context, arg ConsumeUnitQuoteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeUnitQuote, arg.ConsumedJobID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getUnitAdmission = `-- name: GetUnitAdmission :one
SELECT quote_id, budgets_json FROM usage_unit_admissions WHERE job_id = ?
`

type GetUnitAdmissionRow struct {
	QuoteID     string
	BudgetsJson string
}

func (q *Queries) GetUnitAdmission(ctx context.Context, jobID string) (GetUnitAdmissionRow, error) {
	row := q.db.QueryRowContext(ctx, getUnitAdmission, jobID)
	var i GetUnitAdmissionRow
	err := row.Scan(&i.QuoteID, &i.BudgetsJson)
	return i, err
}

const getUnitClaim = `-- name: GetUnitClaim :one
SELECT c.budget_fingerprint, a.user_id, a.kind, c.job_id FROM usage_unit_calls c
JOIN usage_admissions a ON a.job_id = c.job_id WHERE c.id = ?
`

type GetUnitClaimRow struct {
	BudgetFingerprint string
	UserID            string
	Kind              string
	JobID             string
}

func (q *Queries) GetUnitClaim(ctx context.Context, id string) (GetUnitClaimRow, error) {
	row := q.db.QueryRowContext(ctx, getUnitClaim, id)
	var i GetUnitClaimRow
	err := row.Scan(
		&i.BudgetFingerprint,
		&i.UserID,
		&i.Kind,
		&i.JobID,
	)
	return i, err
}

const getUnitQuote = `-- name: GetUnitQuote :one
SELECT quote_json, consumed_job_id FROM usage_unit_quotes WHERE id = ? AND user_id = ?
`

type GetUnitQuoteParams struct {
	ID     string
	UserID string
}

type GetUnitQuoteRow struct {
	QuoteJson     string
	ConsumedJobID string
}

func (q *Queries) GetUnitQuote(ctx context.Context, arg GetUnitQuoteParams) (GetUnitQuoteRow, error) {
	row := q.db.QueryRowContext(ctx, getUnitQuote, arg.ID, arg.UserID)
	var i GetUnitQuoteRow
	err := row.Scan(&i.QuoteJson, &i.ConsumedJobID)
	return i, err
}

const insertUnitBaseEvent = `-- name: InsertUnitBaseEvent :one
INSERT INTO usage_events (user_id, kind, job_id, stage, model, prompt_tokens, completion_tokens, reasoning_tokens, reasoning_truncated, cost_microusd, cost_source, created_at)
VALUES (?, ?, ?, ?, ?, 0, 0, 0, 0, ?, ?, ?) RETURNING id
`

type InsertUnitBaseEventParams struct {
	UserID       string
	Kind         string
	JobID        string
	Stage        string
	Model        string
	CostMicrousd int64
	CostSource   string
	CreatedAt    string
}

func (q *Queries) InsertUnitBaseEvent(ctx context.Context, arg InsertUnitBaseEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertUnitBaseEvent,
		arg.UserID,
		arg.Kind,
		arg.JobID,
		arg.Stage,
		arg.Model,
		arg.CostMicrousd,
		arg.CostSource,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertUnitEvidence = `-- name: InsertUnitEvidence :exec
INSERT INTO usage_unit_events (event_id, claim_id, provider_id, supplier_request_id, budget_fingerprint, evidence_json, reported_usd, exact_usd, cost_source, chargeable)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9,
    NOT EXISTS (SELECT 1 FROM usage_unit_events WHERE supplier_request_id <> '' AND provider_id = ?3 AND supplier_request_id = ?4))
`

type InsertUnitEvidenceParams struct {
	EventID      int64
	ClaimID      string
	ProviderID   string
	RequestID    string
	Fingerprint  string
	EvidenceJson string
	ReportedUsd  string
	ExactUsd     string
	CostSource   string
}

func (q *Queries) InsertUnitEvidence(ctx context.Context, arg InsertUnitEvidenceParams) error {
	_, err := q.db.ExecContext(ctx, insertUnitEvidence,
		arg.EventID,
		arg.ClaimID,
		arg.ProviderID,
		arg.RequestID,
		arg.Fingerprint,
		arg.EvidenceJson,
		arg.ReportedUsd,
		arg.ExactUsd,
		arg.CostSource,
	)
	return err
}

const purgeExpiredUnitQuotes = `-- name: PurgeExpiredUnitQuotes :exec
DELETE FROM usage_unit_quotes WHERE expires_at <= ? AND consumed_job_id = ''
`

func (q *Queries) PurgeExpiredUnitQuotes(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, purgeExpiredUnitQuotes, expiresAt)
	return err
}

const saveUnitAdmission = `-- name: SaveUnitAdmission :exec
INSERT INTO usage_unit_admissions (job_id, admission_id, quote_id, budgets_json)
SELECT ?1, id, ?2, ?3
FROM usage_admissions WHERE job_id = ?1 AND settled_at IS NULL
`

type SaveUnitAdmissionParams struct {
	JobID       string
	QuoteID     string
	BudgetsJson string
}

func (q *Queries) SaveUnitAdmission(ctx context.Context, arg SaveUnitAdmissionParams) error {
	_, err := q.db.ExecContext(ctx, saveUnitAdmission, arg.JobID, arg.QuoteID, arg.BudgetsJson)
	return err
}

const saveUnitQuote = `-- name: SaveUnitQuote :exec
INSERT INTO usage_unit_quotes (id, user_id, kind, digest, quote_json, expires_at) VALUES (?, ?, ?, ?, ?, ?)
`

type SaveUnitQuoteParams struct {
	ID        string
	UserID    string
	Kind      string
	Digest    string
	QuoteJson string
	ExpiresAt string
}

func (q *Queries) SaveUnitQuote(ctx context.Context, arg SaveUnitQuoteParams) error {
	_, err := q.db.ExecContext(ctx, saveUnitQuote,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.Digest,
		arg.QuoteJson,
		arg.ExpiresAt,
	)
	return err
}

const unitCostsForJob = `-- name: UnitCostsForJob :many
SELECT u.exact_usd FROM usage_unit_events u JOIN usage_events e ON e.id = u.event_id
WHERE e.job_id = ? AND u.chargeable = 1 AND u.cost_source IN ('reported', 'estimated')
`

func (q *Queries) UnitCostsForJob(ctx context.Context, jobID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, unitCostsForJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var exact_usd string
		if err := rows.Scan(&exact_usd); err != nil {
			return nil, err
		}
		items = append(items, exact_usd)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unitEventRecorded = `-- name: UnitEventRecorded :one
SELECT COUNT(*) FROM usage_unit_events WHERE claim_id = ?
`

func (q *Queries) UnitEventRecorded(ctx context.Context, claimID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, unitEventRecorded, claimID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
