// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package sqlc

import (
	"context"
)

const countAdmissionsInWindow = `-- name: CountAdmissionsInWindow :one
SELECT COUNT(*) FROM usage_admissions
WHERE user_id = ? AND created_at >= ? AND created_at < ?
`

type CountAdmissionsInWindowParams struct {
	UserID      string
	CreatedAt   string
	CreatedAt_2 string
}

func (q *Queries) CountAdmissionsInWindow(ctx context.Context, arg CountAdmissionsInWindowParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdmissionsInWindow, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAdmissionForJob = `-- name: DeleteAdmissionForJob :exec
DELETE FROM usage_admissions WHERE job_id = ?
`

func (q *Queries) DeleteAdmissionForJob(ctx context.Context, jobID string) error {
	_, err := q.db.ExecContext(ctx, deleteAdmissionForJob, jobID)
	return err
}

const insertAdmission = `-- name: InsertAdmission :exec

INSERT INTO usage_admissions (user_id, kind, job_id, created_at) VALUES (?, ?, ?, ?)
`

type InsertAdmissionParams struct {
	UserID    string
	Kind      string
	JobID     string
	CreatedAt string
}

// Queries for the usage context. sqlc compiles these into internal/usage/store/sqlc;
// internal/usage/store maps the generated rows to domain types.
//
// Every window is a half-open [start, end) range so a boundary instant belongs to
// exactly one day and one month, whichever way the clock is read.
func (q *Queries) InsertAdmission(ctx context.Context, arg InsertAdmissionParams) error {
	_, err := q.db.ExecContext(ctx, insertAdmission,
		arg.UserID,
		arg.Kind,
		arg.JobID,
		arg.CreatedAt,
	)
	return err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO usage_events (
    user_id, kind, job_id, stage, model,
    prompt_tokens, completion_tokens, cost_microusd, cost_source, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEventParams struct {
	UserID           string
	Kind             string
	JobID            string
	Stage            string
	Model            string
	PromptTokens     int64
	CompletionTokens int64
	CostMicrousd     int64
	CostSource       string
	CreatedAt        string
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.UserID,
		arg.Kind,
		arg.JobID,
		arg.Stage,
		arg.Model,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.CostMicrousd,
		arg.CostSource,
		arg.CreatedAt,
	)
	return err
}

const sumCostInWindow = `-- name: SumCostInWindow :one
SELECT CAST(COALESCE(SUM(cost_microusd), 0) AS INTEGER) FROM usage_events
WHERE user_id = ? AND created_at >= ? AND created_at < ?
`

type SumCostInWindowParams struct {
	UserID      string
	CreatedAt   string
	CreatedAt_2 string
}

// COALESCE keeps the empty window a 0 rather than a NULL the row mapper would have to
// special-case; the CAST is what makes sqlc type the result int64 instead of interface{}.
func (q *Queries) SumCostInWindow(ctx context.Context, arg SumCostInWindowParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumCostInWindow, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
