// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type Voucher struct {
	ID            string
	Token         string
	Credits       int64
	ValidityDays  int64
	SaleKrw       sql.NullInt64
	PayerName     sql.NullString
	Message       string
	IssuedBy      string
	IssuedAt      string
	LinkExpiresAt string
	RedeemedBy    sql.NullString
	RedeemedAt    sql.NullString
	LotID         sql.NullString
	RevokedAt     sql.NullString
}
