package template

import (
	"encoding/json"
	"math/rand"
	"os"
	"path/filepath"
	"testing"
)

// The differential corpus: machine-generated bodies plus this parser's verdict on each. It is
// COMMITTED rather than generated at test time so the TypeScript parser can be held to the same
// bodies and the same verdicts without either side reimplementing the generator.
//
// By default this VERIFIES the committed file, so an ordinary `go test ./...` fails when the
// parser's behavior moved and the corpus was not refreshed. Set TEMPLATE_CORPUS_REGEN=1 to
// rewrite it, and read the diff before committing: every changed verdict is a behavior change.
//
// It doubles as the robustness check. 600 generated bodies over the grammar's own alphabet must
// never panic, must always terminate, and must round-trip whenever they are accepted.
func TestCorpusMatchesTheCommittedFile(t *testing.T) {
	pieces := []string{
		"<write>", "</write>", "<note>", "</note>", "<slot kind=\"photo\"/>",
		"<slot kind=\"place\" label=\"지도\"/>", "<repeat each=\"photo\">", "</repeat>",
		"<slot kind=", "kind=\"photo\"", "/>", ">", "<", "&lt;", "&amp;", "\n", " ", "가",
		"=====", "3 < 5", "<writer>", "<slot/>", "'", "\"", "<repeat>", "each=\"tag\"",
		// The characters codex's review turned up as parser disagreements: an escaped quote in
		// an attribute value, and the invisibles the two languages' trim functions disagree on.
		"&quot;", "label=\"a&quot;b\"", "\u200b", "\ufeff", "\u0085", "\u3000",
	}
	type entry struct {
		Body   string `json:"body"`
		OK     bool   `json:"ok"`
		Line   int    `json:"line,omitempty"`
		Reason string `json:"reason,omitempty"`
	}
	rng := rand.New(rand.NewSource(20260904))
	seen := map[string]bool{}
	out := make([]entry, 0, 600)
	for len(out) < 600 {
		body := ""
		for n := rng.Intn(8); n >= 0; n-- {
			body += pieces[rng.Intn(len(pieces))]
		}
		if seen[body] {
			continue
		}
		seen[body] = true
		nodes, err := Parse(body)
		if err != nil {
			parseErr := err.(*ParseError)
			out = append(out, entry{Body: body, OK: false, Line: parseErr.Line, Reason: parseErr.Reason})
			continue
		}
		if round := Serialize(nodes); round != body {
			t.Fatalf("round trip changed an accepted body: %q", body)
		}
		out = append(out, entry{Body: body, OK: true})
	}
	generated, err := json.MarshalIndent(map[string]any{
		"_comment": "Generated by TestRegenerateCorpus. Bodies plus the Go parser's verdict; " +
			"the TypeScript parser is held to the same verdicts (spec/legacy/tech/post-template-grammar.md §4).",
		"cases": out,
	}, "", " ")
	if err != nil {
		t.Fatal(err)
	}
	generated = append(generated, '\n')
	path := filepath.Join("testdata", "grammar", "corpus.json")
	if os.Getenv("TEMPLATE_CORPUS_REGEN") == "1" {
		if err := os.WriteFile(path, generated, 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	committed, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(committed) != string(generated) {
		t.Fatalf("the committed corpus is stale — the parser's behavior moved.\n"+
			"Refresh it with TEMPLATE_CORPUS_REGEN=1 go test ./internal/template/ -run TestCorpus "+
			"and read the diff: every changed verdict is a behavior change the TypeScript parser "+
			"must match too.\ncommitted %d bytes, generated %d bytes", len(committed), len(generated))
	}
}
