package template

import (
	"encoding/json"
	"math/rand"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The differential corpus: machine-generated bodies plus this parser's verdict on each. It is
// COMMITTED rather than generated at test time so the TypeScript parser can be held to the same
// bodies and the same verdicts without either side reimplementing the generator.
//
// By default this VERIFIES the committed file, so an ordinary `go test ./...` fails when the
// parser's behavior moved and the corpus was not refreshed. Set TEMPLATE_CORPUS_REGEN=1 to
// rewrite it, and read the diff before committing: every changed verdict is a behavior change.
//
// It doubles as the robustness check. 600 generated bodies over the grammar's own alphabet must
// never panic, must always terminate, and must round-trip whenever they are accepted.
func TestCorpusMatchesTheCommittedFile(t *testing.T) {
	pieces := []string{
		"<write>", "</write>", "<note>", "</note>", "<slot kind=\"photo\"/>",
		"<slot kind=\"place\" label=\"지도\"/>", "<repeat each=\"photo\">", "</repeat>",
		"<slot kind=", "kind=\"photo\"", "/>", ">", "<", "&lt;", "&amp;", "\n", " ", "가",
		"=====", "3 < 5", "<writer>", "<slot/>", "'", "\"", "<repeat>", "each=\"tag\"",
		// The characters codex's review turned up as parser disagreements: an escaped quote in
		// an attribute value, and the invisibles the two languages' trim functions disagree on.
		"&quot;", "label=\"a&quot;b\"", "\u200b", "\ufeff", "\u0085", "\u3000",
		// Photo-row counts: the bare attribute, and two whole slots — one count inside the
		// ceiling and one above it. The bare pieces mostly land as loose text, so without the
		// whole slots the corpus would never actually exercise invalid_count.
		"count=\"2\"", "count=\"9\"", "count=\"x\"",
		"<slot kind=\"photo\" count=\"2\"/>", "<slot kind=\"photo\" count=\"9\"/>",
		// Data fields (TEMPLATE-43). Both flavors as whole tags, the open/close pieces so the
		// generator can also build broken ones, and one repeated title so duplicate_ask_label
		// and too_many_asks are actually reachable. Growing this alphabet reshuffles every
		// generated body — that is inherent, and the verdicts are what the diff is read for.
		"<ask label=\"총평\"/>", "<ask label=\"총평\">별점</ask>", "<ask label=\"방문일\"/>",
		"<ask label=\"총평\">", "</ask>", "<ask/>", "<ask label=\"\"/>", "label=\"총평\"",
	}
	type entry struct {
		Body   string `json:"body"`
		OK     bool   `json:"ok"`
		Line   int    `json:"line,omitempty"`
		Reason string `json:"reason,omitempty"`
	}
	rng := rand.New(rand.NewSource(20260904))
	seen := map[string]bool{}
	out := make([]entry, 0, 600)
	for len(out) < 600 {
		body := ""
		for n := rng.Intn(8); n >= 0; n-- {
			body += pieces[rng.Intn(len(pieces))]
		}
		if seen[body] {
			continue
		}
		seen[body] = true
		nodes, err := Parse(body, fixtureParseOptions)
		if err != nil {
			parseErr := err.(*ParseError)
			out = append(out, entry{Body: body, OK: false, Line: parseErr.Line, Reason: parseErr.Reason})
			continue
		}
		if round := Serialize(nodes); round != body {
			t.Fatalf("round trip changed an accepted body: %q", body)
		}
		out = append(out, entry{Body: body, OK: true})
	}
	generated, err := json.MarshalIndent(map[string]any{
		"_comment": "Generated by TestCorpusMatchesTheCommittedFile with TEMPLATE_CORPUS_REGEN=1. Bodies plus the Go parser's verdict; " +
			"the TypeScript parser is held to the same verdicts (spec/legacy/tech/post-template-grammar.md §4).",
		"cases":      out,
		"titleCases": titleCorpus(t),
	}, "", " ")
	if err != nil {
		t.Fatal(err)
	}
	generated = append(generated, '\n')
	path := filepath.Join("testdata", "grammar", "corpus.json")
	if os.Getenv("TEMPLATE_CORPUS_REGEN") == "1" {
		if err := os.WriteFile(path, generated, 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	committed, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(committed) != string(generated) {
		t.Fatalf("the committed corpus is stale — the parser's behavior moved.\n"+
			"Refresh it with TEMPLATE_CORPUS_REGEN=1 go test ./internal/template/ -run TestCorpus "+
			"and read the diff: every changed verdict is a behavior change the TypeScript parser "+
			"must match too.\ncommitted %d bytes, generated %d bytes", len(committed), len(generated))
	}
}

// titleCorpus is the title-area half (TMPL-50): 200 generated (title area, body) pairs from a
// seed of their own, so the 600 body cases above keep every byte. The title pieces are the
// grammar's alphabet with the three tags a title refuses among them. The bodies are the few that
// make the cross-area reasons reachable: the one asking 총평 makes a cross-area duplicate, and the
// two asking three labels each make a cross-area too_many_asks, since a body alone is within the
// ceiling and any title ask overflows it — the second with the overflowing ask on a later line.
func titleCorpus(t *testing.T) []titleEntry {
	t.Helper()
	pieces := []string{
		"<write>메뉴</write>", "<write>", "</write>", "<ask label=\"가게\"/>", "<ask label=\"총평\">별점</ask>",
		"<ask label=\"총평\"/>", "<ask/>", "</ask>", "<note>톤</note>", "<slot kind=\"photo\"/>",
		"<slot kind=\"video\"></slot>", "<repeat each=\"photo\">", "</repeat>", "<writer>", " | ", " ", "\n",
		"가", "3 < 5", "&lt;",
	}
	bodies := []string{
		"", "<write>본문</write>", "<ask label=\"총평\"/>", "<ask label=\"a\"/>\n<ask label=\"b\"/>",
		"<ask label=\"a\"/>\n<ask label=\"b\"/>\n<ask label=\"c\"/>",
		"<write>본문</write>\n<ask label=\"a\"/>\n<ask label=\"b\"/>\n<ask label=\"c\"/>",
	}
	rng := rand.New(rand.NewSource(20260923))
	seen := map[[2]string]bool{}
	out := make([]titleEntry, 0, 200)
	for len(out) < 200 {
		titleArea := ""
		for n := rng.Intn(6); n >= 0; n-- {
			titleArea += pieces[rng.Intn(len(pieces))]
		}
		body := bodies[rng.Intn(len(bodies))]
		if key := [2]string{titleArea, body}; seen[key] {
			continue
		} else {
			seen[key] = true
		}
		title, nodes, err := ParseTemplate(titleArea, body, fixtureParseOptions)
		if err != nil {
			parseErr := err.(*ParseError)
			out = append(out, titleEntry{TitleArea: titleArea, Body: body, Line: parseErr.Line, Reason: parseErr.Reason, Area: parseErr.Area})
			continue
		}
		if Serialize(title) != titleArea || Serialize(nodes) != body {
			t.Fatalf("round trip changed an accepted pair: %q | %q", titleArea, body)
		}
		out = append(out, titleEntry{TitleArea: titleArea, Body: body, OK: true})
	}
	return out
}

// titleReasons are the refusals a title pair can end on. The other reasons cannot: a title refuses
// slot, repeat and note as not_in_title before reading their attributes, and none of the fixed
// bodies fails alone.
var titleReasons = []string{
	ReasonUnknownTag, ReasonUnclosedTag, ReasonUnexpectedClose, ReasonMalformedTag,
	ReasonMissingAttribute, ReasonEmptyWrite, ReasonNotInTitle, ReasonDuplicateAskLabel,
	ReasonTooManyAsks,
}

// Review F29: the title half of the corpus reaches every title refusal, the cross-area data-field
// ceiling included, so a generator change that loses one fails here rather than going unseen. A
// separate test, so it also runs while the corpus is being regenerated.
func TestTitleCorpusReachesEveryTitleReason(t *testing.T) {
	seen := map[string]bool{}
	crossArea := false
	for _, entry := range titleCorpus(t) {
		seen[entry.Reason] = true
		if entry.Reason == ReasonTooManyAsks {
			if _, _, err := ParseTemplate("", entry.Body, fixtureParseOptions); err == nil {
				crossArea = true
			}
		}
	}
	var missing []string
	for _, reason := range titleReasons {
		if !seen[reason] {
			missing = append(missing, reason)
		}
	}
	if len(missing) > 0 {
		t.Errorf("the title corpus never ends on %s", strings.Join(missing, ", "))
	}
	if !crossArea {
		t.Errorf("no %s entry is cross-area: its body alone should parse", ReasonTooManyAsks)
	}
}

type titleEntry struct {
	TitleArea string `json:"titleArea"`
	Body      string `json:"body"`
	OK        bool   `json:"ok"`
	Line      int    `json:"line,omitempty"`
	Reason    string `json:"reason,omitempty"`
	Area      string `json:"area,omitempty"`
}
