// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analysis_preparations.sql

package sqlc

import (
	"context"
	"database/sql"
)

const acceptAnalysisVerification = `-- name: AcceptAnalysisVerification :execrows
UPDATE clip_analysis_preparations SET state='accepted',accepted_result=?1,progress=1000
WHERE id=?2 AND state='verifying' AND current_attempt_id=?3 AND expires_at>?4 AND deadline_at>?4
`

type AcceptAnalysisVerificationParams struct {
	AcceptedResult sql.NullString
	ID             string
	AttemptID      sql.NullString
	Now            string
}

func (q *Queries) AcceptAnalysisVerification(ctx context.Context, arg AcceptAnalysisVerificationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, acceptAnalysisVerification,
		arg.AcceptedResult,
		arg.ID,
		arg.AttemptID,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const acceptEmptyAnalysisPreparation = `-- name: AcceptEmptyAnalysisPreparation :execrows
UPDATE clip_analysis_preparations SET state='accepted',progress=1000
WHERE id=?1 AND user_id=?2 AND state='preparing' AND expires_at>?3
AND NOT EXISTS(SELECT 1 FROM clip_analysis_copies c WHERE c.preparation_id=clip_analysis_preparations.id)
`

type AcceptEmptyAnalysisPreparationParams struct {
	ID     string
	UserID string
	Now    string
}

func (q *Queries) AcceptEmptyAnalysisPreparation(ctx context.Context, arg AcceptEmptyAnalysisPreparationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, acceptEmptyAnalysisPreparation, arg.ID, arg.UserID, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const analysisCopies = `-- name: AnalysisCopies :many
SELECT preparation_id, slot, source_id, source_fingerprint, ordinal, offset_ms, duration_ms, width, height, has_audio, object_key, exact_bytes, sha256, state, put_expires_at, verification_json FROM clip_analysis_copies WHERE preparation_id=? ORDER BY source_id,ordinal
`

func (q *Queries) AnalysisCopies(ctx context.Context, preparationID string) ([]ClipAnalysisCopy, error) {
	rows, err := q.db.QueryContext(ctx, analysisCopies, preparationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClipAnalysisCopy
	for rows.Next() {
		var i ClipAnalysisCopy
		if err := rows.Scan(
			&i.PreparationID,
			&i.Slot,
			&i.SourceID,
			&i.SourceFingerprint,
			&i.Ordinal,
			&i.OffsetMs,
			&i.DurationMs,
			&i.Width,
			&i.Height,
			&i.HasAudio,
			&i.ObjectKey,
			&i.ExactBytes,
			&i.Sha256,
			&i.State,
			&i.PutExpiresAt,
			&i.VerificationJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analysisObjectKeyExists = `-- name: AnalysisObjectKeyExists :one
SELECT COUNT(*) FROM clip_analysis_copies WHERE object_key=? AND state!='deleted'
`

func (q *Queries) AnalysisObjectKeyExists(ctx context.Context, objectKey sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, analysisObjectKeyExists, objectKey)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const analysisPreparationAccountCapacity = `-- name: AnalysisPreparationAccountCapacity :one
SELECT COUNT(*) FROM clip_analysis_preparations WHERE user_id=? AND state IN ('preparing','verifying') AND expires_at>?
`

type AnalysisPreparationAccountCapacityParams struct {
	UserID    string
	ExpiresAt string
}

func (q *Queries) AnalysisPreparationAccountCapacity(ctx context.Context, arg AnalysisPreparationAccountCapacityParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, analysisPreparationAccountCapacity, arg.UserID, arg.ExpiresAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const analysisPreparationCapacity = `-- name: AnalysisPreparationCapacity :one
SELECT COUNT(*) FROM clip_analysis_preparations WHERE state IN ('preparing','verifying') AND expires_at>?
`

func (q *Queries) AnalysisPreparationCapacity(ctx context.Context, expiresAt string) (int64, error) {
	row := q.db.QueryRowContext(ctx, analysisPreparationCapacity, expiresAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const analysisPreparationForQuote = `-- name: AnalysisPreparationForQuote :one
SELECT id, user_id, project_id, batch_id, quote_id, profile_version, expected_revision, metadata_json, manifest_digest, state, parent_job_id, current_attempt_id, attempt_count, progress, created_at, expires_at, queue_deadline_at, deadline_at, accepted_result, failure, cleanup_at, reconciled_at FROM clip_analysis_preparations WHERE quote_id=? AND user_id=?
`

type AnalysisPreparationForQuoteParams struct {
	QuoteID string
	UserID  string
}

func (q *Queries) AnalysisPreparationForQuote(ctx context.Context, arg AnalysisPreparationForQuoteParams) (ClipAnalysisPreparation, error) {
	row := q.db.QueryRowContext(ctx, analysisPreparationForQuote, arg.QuoteID, arg.UserID)
	var i ClipAnalysisPreparation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.BatchID,
		&i.QuoteID,
		&i.ProfileVersion,
		&i.ExpectedRevision,
		&i.MetadataJson,
		&i.ManifestDigest,
		&i.State,
		&i.ParentJobID,
		&i.CurrentAttemptID,
		&i.AttemptCount,
		&i.Progress,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.QueueDeadlineAt,
		&i.DeadlineAt,
		&i.AcceptedResult,
		&i.Failure,
		&i.CleanupAt,
		&i.ReconciledAt,
	)
	return i, err
}

const analysisPreparationForStage = `-- name: AnalysisPreparationForStage :one
SELECT id, user_id, project_id, batch_id, quote_id, profile_version, expected_revision, metadata_json, manifest_digest, state, parent_job_id, current_attempt_id, attempt_count, progress, created_at, expires_at, queue_deadline_at, deadline_at, accepted_result, failure, cleanup_at, reconciled_at FROM clip_analysis_preparations WHERE id=?
`

func (q *Queries) AnalysisPreparationForStage(ctx context.Context, id string) (ClipAnalysisPreparation, error) {
	row := q.db.QueryRowContext(ctx, analysisPreparationForStage, id)
	var i ClipAnalysisPreparation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.BatchID,
		&i.QuoteID,
		&i.ProfileVersion,
		&i.ExpectedRevision,
		&i.MetadataJson,
		&i.ManifestDigest,
		&i.State,
		&i.ParentJobID,
		&i.CurrentAttemptID,
		&i.AttemptCount,
		&i.Progress,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.QueueDeadlineAt,
		&i.DeadlineAt,
		&i.AcceptedResult,
		&i.Failure,
		&i.CleanupAt,
		&i.ReconciledAt,
	)
	return i, err
}

const analysisVerificationActiveCount = `-- name: AnalysisVerificationActiveCount :one
SELECT COUNT(*) FROM clip_analysis_verification_attempts a JOIN clip_analysis_preparations p ON p.current_attempt_id=a.id
WHERE a.outcome IS NULL AND a.lease_expires_at>?1
`

func (q *Queries) AnalysisVerificationActiveCount(ctx context.Context, now string) (int64, error) {
	row := q.db.QueryRowContext(ctx, analysisVerificationActiveCount, now)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const analysisVerificationOwnActiveCount = `-- name: AnalysisVerificationOwnActiveCount :one
SELECT COUNT(*) FROM clip_analysis_verification_attempts a JOIN clip_analysis_preparations p ON p.current_attempt_id=a.id
WHERE a.outcome IS NULL AND a.lease_expires_at>?1 AND a.worker_id=?2
`

type AnalysisVerificationOwnActiveCountParams struct {
	Now      string
	WorkerID string
}

func (q *Queries) AnalysisVerificationOwnActiveCount(ctx context.Context, arg AnalysisVerificationOwnActiveCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, analysisVerificationOwnActiveCount, arg.Now, arg.WorkerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const analysisVerificationWaitingCount = `-- name: AnalysisVerificationWaitingCount :one
SELECT COUNT(*) FROM clip_analysis_preparations p LEFT JOIN clip_analysis_verification_attempts a ON a.id=p.current_attempt_id
WHERE p.state='verifying' AND p.expires_at>?1 AND p.deadline_at>?1
AND p.attempt_count<CAST(?2 AS INTEGER)
AND (p.attempt_count>0 OR p.queue_deadline_at>?1)
AND (a.id IS NULL OR a.outcome IS NOT NULL OR a.lease_expires_at<=?1)
`

type AnalysisVerificationWaitingCountParams struct {
	Now         string
	MaxAttempts int64
}

func (q *Queries) AnalysisVerificationWaitingCount(ctx context.Context, arg AnalysisVerificationWaitingCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, analysisVerificationWaitingCount, arg.Now, arg.MaxAttempts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const bindAnalysisParent = `-- name: BindAnalysisParent :execrows
UPDATE clip_analysis_preparations SET parent_job_id=COALESCE(parent_job_id,?1)
WHERE id=?2 AND user_id=?3 AND state='preparing' AND expires_at>?4
AND (parent_job_id IS NULL OR parent_job_id=?1)
`

type BindAnalysisParentParams struct {
	ParentJobID sql.NullString
	ID          string
	UserID      string
	Now         string
}

func (q *Queries) BindAnalysisParent(ctx context.Context, arg BindAnalysisParentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, bindAnalysisParent,
		arg.ParentJobID,
		arg.ID,
		arg.UserID,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const bindAnalysisQuoteDigest = `-- name: BindAnalysisQuoteDigest :execrows
UPDATE clip_generation_quotes SET input_digest=?1
WHERE id=?2 AND user_id=?3 AND input_digest=?4 AND consumed_job_id IS NULL AND expires_at>?5
`

type BindAnalysisQuoteDigestParams struct {
	BoundDigest    string
	QuoteID        string
	UserID         string
	OriginalDigest string
	Now            string
}

func (q *Queries) BindAnalysisQuoteDigest(ctx context.Context, arg BindAnalysisQuoteDigestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, bindAnalysisQuoteDigest,
		arg.BoundDigest,
		arg.QuoteID,
		arg.UserID,
		arg.OriginalDigest,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const claimAnalysisPreparation = `-- name: ClaimAnalysisPreparation :one
UPDATE clip_analysis_preparations SET current_attempt_id=?1,attempt_count=attempt_count+1
WHERE id=(SELECT p.id FROM clip_analysis_preparations p LEFT JOIN clip_analysis_verification_attempts a ON a.id=p.current_attempt_id
WHERE p.state='verifying' AND p.profile_version=?2 AND p.expires_at>?3 AND p.deadline_at>?3
AND p.attempt_count<CAST(?4 AS INTEGER) AND (p.attempt_count>0 OR p.queue_deadline_at>?3)
AND (a.id IS NULL OR a.outcome IS NOT NULL OR a.lease_expires_at<=?3)
AND (SELECT COUNT(*) FROM clip_analysis_verification_attempts active JOIN clip_analysis_preparations owner ON owner.current_attempt_id=active.id
WHERE active.outcome IS NULL AND active.lease_expires_at>?3)<CAST(?5 AS INTEGER)
ORDER BY p.created_at,p.id LIMIT 1)
RETURNING id, user_id, project_id, batch_id, quote_id, profile_version, expected_revision, metadata_json, manifest_digest, state, parent_job_id, current_attempt_id, attempt_count, progress, created_at, expires_at, queue_deadline_at, deadline_at, accepted_result, failure, cleanup_at, reconciled_at
`

type ClaimAnalysisPreparationParams struct {
	AttemptID      sql.NullString
	ProfileVersion string
	Now            string
	MaxAttempts    int64
	ActiveLimit    int64
}

func (q *Queries) ClaimAnalysisPreparation(ctx context.Context, arg ClaimAnalysisPreparationParams) (ClipAnalysisPreparation, error) {
	row := q.db.QueryRowContext(ctx, claimAnalysisPreparation,
		arg.AttemptID,
		arg.ProfileVersion,
		arg.Now,
		arg.MaxAttempts,
		arg.ActiveLimit,
	)
	var i ClipAnalysisPreparation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.BatchID,
		&i.QuoteID,
		&i.ProfileVersion,
		&i.ExpectedRevision,
		&i.MetadataJson,
		&i.ManifestDigest,
		&i.State,
		&i.ParentJobID,
		&i.CurrentAttemptID,
		&i.AttemptCount,
		&i.Progress,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.QueueDeadlineAt,
		&i.DeadlineAt,
		&i.AcceptedResult,
		&i.Failure,
		&i.CleanupAt,
		&i.ReconciledAt,
	)
	return i, err
}

const consumeAnalysisPreparation = `-- name: ConsumeAnalysisPreparation :execrows
UPDATE clip_analysis_preparations SET state='consumed' WHERE id=?1 AND parent_job_id=?2 AND state IN ('accepted','consumed') AND expires_at>?3
`

type ConsumeAnalysisPreparationParams struct {
	ID          string
	ParentJobID sql.NullString
	Now         string
}

func (q *Queries) ConsumeAnalysisPreparation(ctx context.Context, arg ConsumeAnalysisPreparationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeAnalysisPreparation, arg.ID, arg.ParentJobID, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const dueAnalysisCopyDeletions = `-- name: DueAnalysisCopyDeletions :many
SELECT object_key, delete_after FROM clip_analysis_copy_deletions WHERE delete_after<=? ORDER BY delete_after,object_key LIMIT 100
`

func (q *Queries) DueAnalysisCopyDeletions(ctx context.Context, deleteAfter string) ([]ClipAnalysisCopyDeletion, error) {
	rows, err := q.db.QueryContext(ctx, dueAnalysisCopyDeletions, deleteAfter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClipAnalysisCopyDeletion
	for rows.Next() {
		var i ClipAnalysisCopyDeletion
		if err := rows.Scan(&i.ObjectKey, &i.DeleteAfter); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expireAnalysisVerificationAttempts = `-- name: ExpireAnalysisVerificationAttempts :exec
UPDATE clip_analysis_verification_attempts SET outcome='expired',finished_at=?1
WHERE preparation_id=?2 AND outcome IS NULL AND lease_expires_at<=?1
`

type ExpireAnalysisVerificationAttemptsParams struct {
	Now           sql.NullString
	PreparationID string
}

func (q *Queries) ExpireAnalysisVerificationAttempts(ctx context.Context, arg ExpireAnalysisVerificationAttemptsParams) error {
	_, err := q.db.ExecContext(ctx, expireAnalysisVerificationAttempts, arg.Now, arg.PreparationID)
	return err
}

const getAnalysisPreparation = `-- name: GetAnalysisPreparation :one
SELECT id, user_id, project_id, batch_id, quote_id, profile_version, expected_revision, metadata_json, manifest_digest, state, parent_job_id, current_attempt_id, attempt_count, progress, created_at, expires_at, queue_deadline_at, deadline_at, accepted_result, failure, cleanup_at, reconciled_at FROM clip_analysis_preparations WHERE id=? AND user_id=?
`

type GetAnalysisPreparationParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetAnalysisPreparation(ctx context.Context, arg GetAnalysisPreparationParams) (ClipAnalysisPreparation, error) {
	row := q.db.QueryRowContext(ctx, getAnalysisPreparation, arg.ID, arg.UserID)
	var i ClipAnalysisPreparation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.BatchID,
		&i.QuoteID,
		&i.ProfileVersion,
		&i.ExpectedRevision,
		&i.MetadataJson,
		&i.ManifestDigest,
		&i.State,
		&i.ParentJobID,
		&i.CurrentAttemptID,
		&i.AttemptCount,
		&i.Progress,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.QueueDeadlineAt,
		&i.DeadlineAt,
		&i.AcceptedResult,
		&i.Failure,
		&i.CleanupAt,
		&i.ReconciledAt,
	)
	return i, err
}

const getAnalysisVerificationAttempt = `-- name: GetAnalysisVerificationAttempt :one
SELECT id, preparation_id, ordinal, worker_id, token_hash, lease_expires_at, started_at, outcome, finished_at, runtime_manifest FROM clip_analysis_verification_attempts WHERE id=?
`

func (q *Queries) GetAnalysisVerificationAttempt(ctx context.Context, id string) (ClipAnalysisVerificationAttempt, error) {
	row := q.db.QueryRowContext(ctx, getAnalysisVerificationAttempt, id)
	var i ClipAnalysisVerificationAttempt
	err := row.Scan(
		&i.ID,
		&i.PreparationID,
		&i.Ordinal,
		&i.WorkerID,
		&i.TokenHash,
		&i.LeaseExpiresAt,
		&i.StartedAt,
		&i.Outcome,
		&i.FinishedAt,
		&i.RuntimeManifest,
	)
	return i, err
}

const insertAnalysisCopy = `-- name: InsertAnalysisCopy :exec
INSERT INTO clip_analysis_copies(preparation_id,slot,source_id,source_fingerprint,ordinal,offset_ms,duration_ms,width,height,has_audio) VALUES(?,?,?,?,?,?,?,?,?,?)
`

type InsertAnalysisCopyParams struct {
	PreparationID     string
	Slot              string
	SourceID          string
	SourceFingerprint string
	Ordinal           int64
	OffsetMs          int64
	DurationMs        int64
	Width             int64
	Height            int64
	HasAudio          int64
}

func (q *Queries) InsertAnalysisCopy(ctx context.Context, arg InsertAnalysisCopyParams) error {
	_, err := q.db.ExecContext(ctx, insertAnalysisCopy,
		arg.PreparationID,
		arg.Slot,
		arg.SourceID,
		arg.SourceFingerprint,
		arg.Ordinal,
		arg.OffsetMs,
		arg.DurationMs,
		arg.Width,
		arg.Height,
		arg.HasAudio,
	)
	return err
}

const insertAnalysisPreparation = `-- name: InsertAnalysisPreparation :exec
INSERT INTO clip_analysis_preparations(id,user_id,project_id,batch_id,quote_id,profile_version,expected_revision,metadata_json,manifest_digest,created_at,expires_at,queue_deadline_at,deadline_at)
VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)
`

type InsertAnalysisPreparationParams struct {
	ID               string
	UserID           string
	ProjectID        string
	BatchID          string
	QuoteID          string
	ProfileVersion   string
	ExpectedRevision int64
	MetadataJson     string
	ManifestDigest   string
	CreatedAt        string
	ExpiresAt        string
	QueueDeadlineAt  string
	DeadlineAt       string
}

func (q *Queries) InsertAnalysisPreparation(ctx context.Context, arg InsertAnalysisPreparationParams) error {
	_, err := q.db.ExecContext(ctx, insertAnalysisPreparation,
		arg.ID,
		arg.UserID,
		arg.ProjectID,
		arg.BatchID,
		arg.QuoteID,
		arg.ProfileVersion,
		arg.ExpectedRevision,
		arg.MetadataJson,
		arg.ManifestDigest,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.QueueDeadlineAt,
		arg.DeadlineAt,
	)
	return err
}

const insertAnalysisVerificationAttempt = `-- name: InsertAnalysisVerificationAttempt :exec
INSERT INTO clip_analysis_verification_attempts(id,preparation_id,ordinal,worker_id,token_hash,lease_expires_at,started_at,runtime_manifest) VALUES(?,?,?,?,?,?,?,?)
`

type InsertAnalysisVerificationAttemptParams struct {
	ID              string
	PreparationID   string
	Ordinal         int64
	WorkerID        string
	TokenHash       string
	LeaseExpiresAt  string
	StartedAt       string
	RuntimeManifest string
}

func (q *Queries) InsertAnalysisVerificationAttempt(ctx context.Context, arg InsertAnalysisVerificationAttemptParams) error {
	_, err := q.db.ExecContext(ctx, insertAnalysisVerificationAttempt,
		arg.ID,
		arg.PreparationID,
		arg.Ordinal,
		arg.WorkerID,
		arg.TokenHash,
		arg.LeaseExpiresAt,
		arg.StartedAt,
		arg.RuntimeManifest,
	)
	return err
}

const liveAnalysisPreparations = `-- name: LiveAnalysisPreparations :many
SELECT id, user_id, project_id, batch_id, quote_id, profile_version, expected_revision, metadata_json, manifest_digest, state, parent_job_id, current_attempt_id, attempt_count, progress, created_at, expires_at, queue_deadline_at, deadline_at, accepted_result, failure, cleanup_at, reconciled_at FROM clip_analysis_preparations WHERE reconciled_at IS NULL AND id>? ORDER BY id LIMIT 100
`

func (q *Queries) LiveAnalysisPreparations(ctx context.Context, id string) ([]ClipAnalysisPreparation, error) {
	rows, err := q.db.QueryContext(ctx, liveAnalysisPreparations, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClipAnalysisPreparation
	for rows.Next() {
		var i ClipAnalysisPreparation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.BatchID,
			&i.QuoteID,
			&i.ProfileVersion,
			&i.ExpectedRevision,
			&i.MetadataJson,
			&i.ManifestDigest,
			&i.State,
			&i.ParentJobID,
			&i.CurrentAttemptID,
			&i.AttemptCount,
			&i.Progress,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.QueueDeadlineAt,
			&i.DeadlineAt,
			&i.AcceptedResult,
			&i.Failure,
			&i.CleanupAt,
			&i.ReconciledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAnalysisCopyDeleted = `-- name: MarkAnalysisCopyDeleted :exec
UPDATE clip_analysis_copies SET state='deleted' WHERE object_key=?
`

func (q *Queries) MarkAnalysisCopyDeleted(ctx context.Context, objectKey sql.NullString) error {
	_, err := q.db.ExecContext(ctx, markAnalysisCopyDeleted, objectKey)
	return err
}

const markAnalysisPreparationCleanup = `-- name: MarkAnalysisPreparationCleanup :exec
UPDATE clip_analysis_preparations SET cleanup_at=? WHERE id=?
`

type MarkAnalysisPreparationCleanupParams struct {
	CleanupAt sql.NullString
	ID        string
}

func (q *Queries) MarkAnalysisPreparationCleanup(ctx context.Context, arg MarkAnalysisPreparationCleanupParams) error {
	_, err := q.db.ExecContext(ctx, markAnalysisPreparationCleanup, arg.CleanupAt, arg.ID)
	return err
}

const markAnalysisPreparationReconciled = `-- name: MarkAnalysisPreparationReconciled :exec
UPDATE clip_analysis_preparations SET reconciled_at=? WHERE id=?
`

type MarkAnalysisPreparationReconciledParams struct {
	ReconciledAt sql.NullString
	ID           string
}

func (q *Queries) MarkAnalysisPreparationReconciled(ctx context.Context, arg MarkAnalysisPreparationReconciledParams) error {
	_, err := q.db.ExecContext(ctx, markAnalysisPreparationReconciled, arg.ReconciledAt, arg.ID)
	return err
}

const queueAnalysisCopyCleanup = `-- name: QueueAnalysisCopyCleanup :exec
INSERT INTO clip_analysis_copy_deletions(object_key,delete_after)
SELECT object_key,MAX(COALESCE(put_expires_at,''),?1) FROM clip_analysis_copies WHERE preparation_id=?2 AND object_key IS NOT NULL AND state!='deleted'
ON CONFLICT(object_key) DO UPDATE SET delete_after=MAX(delete_after,excluded.delete_after)
`

type QueueAnalysisCopyCleanupParams struct {
	Now           interface{}
	PreparationID string
}

func (q *Queries) QueueAnalysisCopyCleanup(ctx context.Context, arg QueueAnalysisCopyCleanupParams) error {
	_, err := q.db.ExecContext(ctx, queueAnalysisCopyCleanup, arg.Now, arg.PreparationID)
	return err
}

const queueAnalysisOrphanDeletion = `-- name: QueueAnalysisOrphanDeletion :exec
INSERT INTO clip_analysis_copy_deletions(object_key,delete_after) VALUES(?,?) ON CONFLICT DO NOTHING
`

type QueueAnalysisOrphanDeletionParams struct {
	ObjectKey   string
	DeleteAfter string
}

func (q *Queries) QueueAnalysisOrphanDeletion(ctx context.Context, arg QueueAnalysisOrphanDeletionParams) error {
	_, err := q.db.ExecContext(ctx, queueAnalysisOrphanDeletion, arg.ObjectKey, arg.DeleteAfter)
	return err
}

const removeAnalysisCopyDeletion = `-- name: RemoveAnalysisCopyDeletion :exec
DELETE FROM clip_analysis_copy_deletions WHERE object_key=?
`

func (q *Queries) RemoveAnalysisCopyDeletion(ctx context.Context, objectKey string) error {
	_, err := q.db.ExecContext(ctx, removeAnalysisCopyDeletion, objectKey)
	return err
}

const renewAnalysisVerification = `-- name: RenewAnalysisVerification :execrows
UPDATE clip_analysis_verification_attempts SET lease_expires_at=?1
WHERE id=?2 AND worker_id=?3 AND token_hash=?4 AND outcome IS NULL AND lease_expires_at>?5
`

type RenewAnalysisVerificationParams struct {
	LeaseExpiresAt string
	ID             string
	WorkerID       string
	TokenHash      string
	Now            string
}

func (q *Queries) RenewAnalysisVerification(ctx context.Context, arg RenewAnalysisVerificationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renewAnalysisVerification,
		arg.LeaseExpiresAt,
		arg.ID,
		arg.WorkerID,
		arg.TokenHash,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const reserveAnalysisCopy = `-- name: ReserveAnalysisCopy :execrows
UPDATE clip_analysis_copies SET object_key=COALESCE(object_key,?1),exact_bytes=?2,sha256=?3,state='reserved',put_expires_at=MAX(COALESCE(put_expires_at,''),?4)
WHERE preparation_id=?5 AND slot=?6
AND (state='expected' OR (state='reserved' AND exact_bytes=?2 AND sha256=?3))
AND EXISTS(SELECT 1 FROM clip_analysis_preparations p WHERE p.id=clip_analysis_copies.preparation_id AND p.state='preparing' AND p.expires_at>?7)
`

type ReserveAnalysisCopyParams struct {
	ObjectKey     sql.NullString
	ExactBytes    int64
	Sha256        string
	PutExpiresAt  interface{}
	PreparationID string
	Slot          string
	Now           string
}

func (q *Queries) ReserveAnalysisCopy(ctx context.Context, arg ReserveAnalysisCopyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reserveAnalysisCopy,
		arg.ObjectKey,
		arg.ExactBytes,
		arg.Sha256,
		arg.PutExpiresAt,
		arg.PreparationID,
		arg.Slot,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const retireAnalysisCopies = `-- name: RetireAnalysisCopies :exec
UPDATE clip_analysis_copies SET state='cleanup' WHERE preparation_id=? AND object_key IS NOT NULL AND state!='deleted'
`

func (q *Queries) RetireAnalysisCopies(ctx context.Context, preparationID string) error {
	_, err := q.db.ExecContext(ctx, retireAnalysisCopies, preparationID)
	return err
}

const setAnalysisPreparationState = `-- name: SetAnalysisPreparationState :exec
UPDATE clip_analysis_preparations SET state=?1,failure=?2 WHERE id=?3
`

type SetAnalysisPreparationStateParams struct {
	State   string
	Failure sql.NullString
	ID      string
}

func (q *Queries) SetAnalysisPreparationState(ctx context.Context, arg SetAnalysisPreparationStateParams) error {
	_, err := q.db.ExecContext(ctx, setAnalysisPreparationState, arg.State, arg.Failure, arg.ID)
	return err
}

const stopAnalysisVerificationAttempt = `-- name: StopAnalysisVerificationAttempt :exec
UPDATE clip_analysis_verification_attempts SET outcome=COALESCE(outcome,?1),finished_at=COALESCE(finished_at,?2) WHERE id=?3
`

type StopAnalysisVerificationAttemptParams struct {
	Outcome sql.NullString
	Now     sql.NullString
	ID      string
}

func (q *Queries) StopAnalysisVerificationAttempt(ctx context.Context, arg StopAnalysisVerificationAttemptParams) error {
	_, err := q.db.ExecContext(ctx, stopAnalysisVerificationAttempt, arg.Outcome, arg.Now, arg.ID)
	return err
}

const submitAnalysisPreparation = `-- name: SubmitAnalysisPreparation :execrows
UPDATE clip_analysis_preparations SET state='verifying',manifest_digest=?1,deadline_at=MIN(expires_at,?2),queue_deadline_at=MIN(expires_at,?2,?3)
WHERE id=?4 AND user_id=?5 AND state='preparing' AND expires_at>?6
`

type SubmitAnalysisPreparationParams struct {
	ManifestDigest  string
	DeadlineAt      interface{}
	QueueDeadlineAt interface{}
	ID              string
	UserID          string
	Now             string
}

func (q *Queries) SubmitAnalysisPreparation(ctx context.Context, arg SubmitAnalysisPreparationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, submitAnalysisPreparation,
		arg.ManifestDigest,
		arg.DeadlineAt,
		arg.QueueDeadlineAt,
		arg.ID,
		arg.UserID,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAnalysisProgress = `-- name: UpdateAnalysisProgress :exec
UPDATE clip_analysis_preparations SET progress=MAX(progress,?1) WHERE id=?2
`

type UpdateAnalysisProgressParams struct {
	Progress interface{}
	ID       string
}

func (q *Queries) UpdateAnalysisProgress(ctx context.Context, arg UpdateAnalysisProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateAnalysisProgress, arg.Progress, arg.ID)
	return err
}

const verifyAnalysisCopy = `-- name: VerifyAnalysisCopy :execrows
UPDATE clip_analysis_copies SET state='verified',verification_json=?1
WHERE preparation_id=?2 AND slot=?3 AND state='reserved' AND exact_bytes=?4 AND sha256=?5
`

type VerifyAnalysisCopyParams struct {
	VerificationJson sql.NullString
	PreparationID    string
	Slot             string
	ExactBytes       int64
	Sha256           string
}

func (q *Queries) VerifyAnalysisCopy(ctx context.Context, arg VerifyAnalysisCopyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, verifyAnalysisCopy,
		arg.VerificationJson,
		arg.PreparationID,
		arg.Slot,
		arg.ExactBytes,
		arg.Sha256,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
