// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authoring.sql

package sqlc

import (
	"context"
)

const getAuthoringPublication = `-- name: GetAuthoringPublication :one
SELECT publication_key,target_id FROM video_template_authoring_publications
WHERE user_id=? AND session_id=? AND revision=?
`

type GetAuthoringPublicationParams struct {
	UserID    string
	SessionID string
	Revision  int64
}

type GetAuthoringPublicationRow struct {
	PublicationKey string
	TargetID       string
}

func (q *Queries) GetAuthoringPublication(ctx context.Context, arg GetAuthoringPublicationParams) (GetAuthoringPublicationRow, error) {
	row := q.db.QueryRowContext(ctx, getAuthoringPublication, arg.UserID, arg.SessionID, arg.Revision)
	var i GetAuthoringPublicationRow
	err := row.Scan(&i.PublicationKey, &i.TargetID)
	return i, err
}

const insertAuthoringPublication = `-- name: InsertAuthoringPublication :exec
INSERT INTO video_template_authoring_publications(user_id,session_id,revision,publication_key,target_id,created_at)
VALUES(?,?,?,?,?,?)
`

type InsertAuthoringPublicationParams struct {
	UserID         string
	SessionID      string
	Revision       int64
	PublicationKey string
	TargetID       string
	CreatedAt      string
}

func (q *Queries) InsertAuthoringPublication(ctx context.Context, arg InsertAuthoringPublicationParams) error {
	_, err := q.db.ExecContext(ctx, insertAuthoringPublication,
		arg.UserID,
		arg.SessionID,
		arg.Revision,
		arg.PublicationKey,
		arg.TargetID,
		arg.CreatedAt,
	)
	return err
}

const lockAuthoringPublication = `-- name: LockAuthoringPublication :exec
UPDATE video_templates SET name=name WHERE 0
`

func (q *Queries) LockAuthoringPublication(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, lockAuthoringPublication)
	return err
}
