// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clips.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countTemplateProjects = `-- name: CountTemplateProjects :one
SELECT count(*) FROM clip_projects WHERE video_template_id = ? AND user_id = ?
`

type CountTemplateProjectsParams struct {
	VideoTemplateID sql.NullString
	UserID          string
}

func (q *Queries) CountTemplateProjects(ctx context.Context, arg CountTemplateProjectsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTemplateProjects, arg.VideoTemplateID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteClipProject = `-- name: DeleteClipProject :execrows
DELETE FROM clip_projects WHERE id = ? AND user_id = ?
`

type DeleteClipProjectParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteClipProject(ctx context.Context, arg DeleteClipProjectParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteClipProject, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteVideoTemplate = `-- name: DeleteVideoTemplate :execrows
DELETE FROM video_templates WHERE id = ? AND user_id = ?
`

type DeleteVideoTemplateParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteVideoTemplate(ctx context.Context, arg DeleteVideoTemplateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteVideoTemplate, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getClipProject = `-- name: GetClipProject :one
SELECT id, user_id, title, video_template_id, ratio, target_duration_ms, analysis_json, edit_plan_json, result_key, result_content_type, result_bytes, result_duration_ms, result_created_at, edit_plan_revision, rendered_plan_revision, created_at, updated_at, deleting, disclosure, cta, hide_disclosure, composition_inputs_json, composition_snapshot_json, source_retention_expires_at, source_access_revoked_at, source_batch_id, result_id, finalized_at, finalized_plan_revision, finalized_result_key FROM clip_projects WHERE id = ? AND user_id = ?
`

type GetClipProjectParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetClipProject(ctx context.Context, arg GetClipProjectParams) (ClipProject, error) {
	row := q.db.QueryRowContext(ctx, getClipProject, arg.ID, arg.UserID)
	var i ClipProject
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.VideoTemplateID,
		&i.Ratio,
		&i.TargetDurationMs,
		&i.AnalysisJson,
		&i.EditPlanJson,
		&i.ResultKey,
		&i.ResultContentType,
		&i.ResultBytes,
		&i.ResultDurationMs,
		&i.ResultCreatedAt,
		&i.EditPlanRevision,
		&i.RenderedPlanRevision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Deleting,
		&i.Disclosure,
		&i.Cta,
		&i.HideDisclosure,
		&i.CompositionInputsJson,
		&i.CompositionSnapshotJson,
		&i.SourceRetentionExpiresAt,
		&i.SourceAccessRevokedAt,
		&i.SourceBatchID,
		&i.ResultID,
		&i.FinalizedAt,
		&i.FinalizedPlanRevision,
		&i.FinalizedResultKey,
	)
	return i, err
}

const getVideoTemplate = `-- name: GetVideoTemplate :one
SELECT id, user_id, name, information_fields, cut_guidance, copy_styles, accent, created_at, updated_at, preset, caption_pace, composition_body, composition_legacy FROM video_templates WHERE id = ? AND user_id = ?
`

type GetVideoTemplateParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetVideoTemplate(ctx context.Context, arg GetVideoTemplateParams) (VideoTemplate, error) {
	row := q.db.QueryRowContext(ctx, getVideoTemplate, arg.ID, arg.UserID)
	var i VideoTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.InformationFields,
		&i.CutGuidance,
		&i.CopyStyles,
		&i.Accent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Preset,
		&i.CaptionPace,
		&i.CompositionBody,
		&i.CompositionLegacy,
	)
	return i, err
}

const insertClipProject = `-- name: InsertClipProject :exec
INSERT INTO clip_projects(id, user_id, title, video_template_id, ratio, target_duration_ms, disclosure, cta, hide_disclosure, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertClipProjectParams struct {
	ID               string
	UserID           string
	Title            string
	VideoTemplateID  sql.NullString
	Ratio            string
	TargetDurationMs int64
	Disclosure       string
	Cta              string
	HideDisclosure   int64
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) InsertClipProject(ctx context.Context, arg InsertClipProjectParams) error {
	_, err := q.db.ExecContext(ctx, insertClipProject,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.VideoTemplateID,
		arg.Ratio,
		arg.TargetDurationMs,
		arg.Disclosure,
		arg.Cta,
		arg.HideDisclosure,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertVideoTemplate = `-- name: InsertVideoTemplate :exec
INSERT INTO video_templates(id, user_id, name, information_fields, cut_guidance, copy_styles, accent, preset, caption_pace, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertVideoTemplateParams struct {
	ID                string
	UserID            string
	Name              string
	InformationFields string
	CutGuidance       string
	CopyStyles        string
	Accent            sql.NullString
	Preset            string
	CaptionPace       string
	CreatedAt         string
	UpdatedAt         string
}

func (q *Queries) InsertVideoTemplate(ctx context.Context, arg InsertVideoTemplateParams) error {
	_, err := q.db.ExecContext(ctx, insertVideoTemplate,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.InformationFields,
		arg.CutGuidance,
		arg.CopyStyles,
		arg.Accent,
		arg.Preset,
		arg.CaptionPace,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listClipAnswers = `-- name: ListClipAnswers :many
SELECT label, answer FROM clip_project_answers WHERE project_id = ? AND user_id = ? ORDER BY label
`

type ListClipAnswersParams struct {
	ProjectID string
	UserID    string
}

type ListClipAnswersRow struct {
	Label  string
	Answer string
}

func (q *Queries) ListClipAnswers(ctx context.Context, arg ListClipAnswersParams) ([]ListClipAnswersRow, error) {
	rows, err := q.db.QueryContext(ctx, listClipAnswers, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClipAnswersRow
	for rows.Next() {
		var i ListClipAnswersRow
		if err := rows.Scan(&i.Label, &i.Answer); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClipProjects = `-- name: ListClipProjects :many
SELECT id, user_id, title, video_template_id, ratio, target_duration_ms, analysis_json, edit_plan_json, result_key, result_content_type, result_bytes, result_duration_ms, result_created_at, edit_plan_revision, rendered_plan_revision, created_at, updated_at, deleting, disclosure, cta, hide_disclosure, composition_inputs_json, composition_snapshot_json, source_retention_expires_at, source_access_revoked_at, source_batch_id, result_id, finalized_at, finalized_plan_revision, finalized_result_key FROM clip_projects WHERE user_id = ? ORDER BY updated_at DESC, id
`

func (q *Queries) ListClipProjects(ctx context.Context, userID string) ([]ClipProject, error) {
	rows, err := q.db.QueryContext(ctx, listClipProjects, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClipProject
	for rows.Next() {
		var i ClipProject
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.VideoTemplateID,
			&i.Ratio,
			&i.TargetDurationMs,
			&i.AnalysisJson,
			&i.EditPlanJson,
			&i.ResultKey,
			&i.ResultContentType,
			&i.ResultBytes,
			&i.ResultDurationMs,
			&i.ResultCreatedAt,
			&i.EditPlanRevision,
			&i.RenderedPlanRevision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Deleting,
			&i.Disclosure,
			&i.Cta,
			&i.HideDisclosure,
			&i.CompositionInputsJson,
			&i.CompositionSnapshotJson,
			&i.SourceRetentionExpiresAt,
			&i.SourceAccessRevokedAt,
			&i.SourceBatchID,
			&i.ResultID,
			&i.FinalizedAt,
			&i.FinalizedPlanRevision,
			&i.FinalizedResultKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideoTemplates = `-- name: ListVideoTemplates :many
SELECT id, user_id, name, information_fields, cut_guidance, copy_styles, accent, created_at, updated_at, preset, caption_pace, composition_body, composition_legacy FROM video_templates WHERE user_id = ? ORDER BY name, id
`

func (q *Queries) ListVideoTemplates(ctx context.Context, userID string) ([]VideoTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listVideoTemplates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VideoTemplate
	for rows.Next() {
		var i VideoTemplate
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.InformationFields,
			&i.CutGuidance,
			&i.CopyStyles,
			&i.Accent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Preset,
			&i.CaptionPace,
			&i.CompositionBody,
			&i.CompositionLegacy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectsForTemplate = `-- name: ProjectsForTemplate :many
SELECT id, user_id, title, video_template_id, ratio, target_duration_ms, analysis_json, edit_plan_json, result_key, result_content_type, result_bytes, result_duration_ms, result_created_at, edit_plan_revision, rendered_plan_revision, created_at, updated_at, deleting, disclosure, cta, hide_disclosure, composition_inputs_json, composition_snapshot_json, source_retention_expires_at, source_access_revoked_at, source_batch_id, result_id, finalized_at, finalized_plan_revision, finalized_result_key FROM clip_projects WHERE video_template_id = ? AND user_id = ? ORDER BY id
`

type ProjectsForTemplateParams struct {
	VideoTemplateID sql.NullString
	UserID          string
}

func (q *Queries) ProjectsForTemplate(ctx context.Context, arg ProjectsForTemplateParams) ([]ClipProject, error) {
	rows, err := q.db.QueryContext(ctx, projectsForTemplate, arg.VideoTemplateID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClipProject
	for rows.Next() {
		var i ClipProject
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.VideoTemplateID,
			&i.Ratio,
			&i.TargetDurationMs,
			&i.AnalysisJson,
			&i.EditPlanJson,
			&i.ResultKey,
			&i.ResultContentType,
			&i.ResultBytes,
			&i.ResultDurationMs,
			&i.ResultCreatedAt,
			&i.EditPlanRevision,
			&i.RenderedPlanRevision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Deleting,
			&i.Disclosure,
			&i.Cta,
			&i.HideDisclosure,
			&i.CompositionInputsJson,
			&i.CompositionSnapshotJson,
			&i.SourceRetentionExpiresAt,
			&i.SourceAccessRevokedAt,
			&i.SourceBatchID,
			&i.ResultID,
			&i.FinalizedAt,
			&i.FinalizedPlanRevision,
			&i.FinalizedResultKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveProjectComposition = `-- name: SaveProjectComposition :execrows
UPDATE clip_projects SET composition_snapshot_json=?,composition_inputs_json=? WHERE id=? AND user_id=? AND finalized_at IS NULL
`

type SaveProjectCompositionParams struct {
	CompositionSnapshotJson sql.NullString
	CompositionInputsJson   sql.NullString
	ID                      string
	UserID                  string
}

func (q *Queries) SaveProjectComposition(ctx context.Context, arg SaveProjectCompositionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveProjectComposition,
		arg.CompositionSnapshotJson,
		arg.CompositionInputsJson,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const saveTemplateComposition = `-- name: SaveTemplateComposition :execrows
UPDATE video_templates SET composition_body=?,composition_legacy=? WHERE id=? AND user_id=?
`

type SaveTemplateCompositionParams struct {
	CompositionBody   sql.NullString
	CompositionLegacy int64
	ID                string
	UserID            string
}

func (q *Queries) SaveTemplateComposition(ctx context.Context, arg SaveTemplateCompositionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveTemplateComposition,
		arg.CompositionBody,
		arg.CompositionLegacy,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchClip = `-- name: TouchClip :execrows
UPDATE clip_projects SET updated_at = ? WHERE id = ? AND user_id = ? AND finalized_at IS NULL
`

type TouchClipParams struct {
	UpdatedAt string
	ID        string
	UserID    string
}

func (q *Queries) TouchClip(ctx context.Context, arg TouchClipParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchClip, arg.UpdatedAt, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchCompositionRevision = `-- name: TouchCompositionRevision :execrows
UPDATE clip_projects SET edit_plan_revision=edit_plan_revision+1,updated_at=? WHERE id=? AND user_id=? AND deleting=0 AND finalized_at IS NULL
`

type TouchCompositionRevisionParams struct {
	UpdatedAt string
	ID        string
	UserID    string
}

func (q *Queries) TouchCompositionRevision(ctx context.Context, arg TouchCompositionRevisionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchCompositionRevision, arg.UpdatedAt, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateClipCTA = `-- name: UpdateClipCTA :execrows
UPDATE clip_projects SET cta = ?, updated_at = ? WHERE id = ? AND user_id = ? AND finalized_at IS NULL
`

type UpdateClipCTAParams struct {
	Cta       string
	UpdatedAt string
	ID        string
	UserID    string
}

func (q *Queries) UpdateClipCTA(ctx context.Context, arg UpdateClipCTAParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateClipCTA,
		arg.Cta,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateClipDisclosure = `-- name: UpdateClipDisclosure :execrows
UPDATE clip_projects SET disclosure = ?, updated_at = ? WHERE id = ? AND user_id = ? AND finalized_at IS NULL
`

type UpdateClipDisclosureParams struct {
	Disclosure string
	UpdatedAt  string
	ID         string
	UserID     string
}

func (q *Queries) UpdateClipDisclosure(ctx context.Context, arg UpdateClipDisclosureParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateClipDisclosure,
		arg.Disclosure,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateClipHideDisclosure = `-- name: UpdateClipHideDisclosure :execrows
UPDATE clip_projects SET hide_disclosure = ?1,
    edit_plan_revision = edit_plan_revision + CASE WHEN edit_plan_json IS NOT NULL AND hide_disclosure != ?1 THEN 1 ELSE 0 END,
    updated_at = ?2 WHERE id = ?3 AND user_id = ?4
`

type UpdateClipHideDisclosureParams struct {
	HideDisclosure int64
	UpdatedAt      string
	ID             string
	UserID         string
}

func (q *Queries) UpdateClipHideDisclosure(ctx context.Context, arg UpdateClipHideDisclosureParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateClipHideDisclosure,
		arg.HideDisclosure,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateClipTargetDurationMS = `-- name: UpdateClipTargetDurationMS :execrows
UPDATE clip_projects SET target_duration_ms = ?, updated_at = ? WHERE id = ? AND user_id = ? AND finalized_at IS NULL
`

type UpdateClipTargetDurationMSParams struct {
	TargetDurationMs int64
	UpdatedAt        string
	ID               string
	UserID           string
}

func (q *Queries) UpdateClipTargetDurationMS(ctx context.Context, arg UpdateClipTargetDurationMSParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateClipTargetDurationMS,
		arg.TargetDurationMs,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateClipTitle = `-- name: UpdateClipTitle :execrows
UPDATE clip_projects SET title = ?, updated_at = ? WHERE id = ? AND user_id = ? AND finalized_at IS NULL
`

type UpdateClipTitleParams struct {
	Title     string
	UpdatedAt string
	ID        string
	UserID    string
}

func (q *Queries) UpdateClipTitle(ctx context.Context, arg UpdateClipTitleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateClipTitle,
		arg.Title,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateClipVideoTemplateID = `-- name: UpdateClipVideoTemplateID :execrows
UPDATE clip_projects SET video_template_id = ?, updated_at = ? WHERE id = ? AND user_id = ? AND finalized_at IS NULL
`

type UpdateClipVideoTemplateIDParams struct {
	VideoTemplateID sql.NullString
	UpdatedAt       string
	ID              string
	UserID          string
}

func (q *Queries) UpdateClipVideoTemplateID(ctx context.Context, arg UpdateClipVideoTemplateIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateClipVideoTemplateID,
		arg.VideoTemplateID,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateVideoTemplateAccent = `-- name: UpdateVideoTemplateAccent :execrows
UPDATE video_templates SET accent = ?, updated_at = ? WHERE id = ? AND user_id = ?
`

type UpdateVideoTemplateAccentParams struct {
	Accent    sql.NullString
	UpdatedAt string
	ID        string
	UserID    string
}

func (q *Queries) UpdateVideoTemplateAccent(ctx context.Context, arg UpdateVideoTemplateAccentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateVideoTemplateAccent,
		arg.Accent,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateVideoTemplateCaptionPace = `-- name: UpdateVideoTemplateCaptionPace :execrows
UPDATE video_templates SET caption_pace = ?, updated_at = ? WHERE id = ? AND user_id = ?
`

type UpdateVideoTemplateCaptionPaceParams struct {
	CaptionPace string
	UpdatedAt   string
	ID          string
	UserID      string
}

func (q *Queries) UpdateVideoTemplateCaptionPace(ctx context.Context, arg UpdateVideoTemplateCaptionPaceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateVideoTemplateCaptionPace,
		arg.CaptionPace,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateVideoTemplateCopyStyles = `-- name: UpdateVideoTemplateCopyStyles :execrows
UPDATE video_templates SET copy_styles = ?, updated_at = ? WHERE id = ? AND user_id = ?
`

type UpdateVideoTemplateCopyStylesParams struct {
	CopyStyles string
	UpdatedAt  string
	ID         string
	UserID     string
}

func (q *Queries) UpdateVideoTemplateCopyStyles(ctx context.Context, arg UpdateVideoTemplateCopyStylesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateVideoTemplateCopyStyles,
		arg.CopyStyles,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateVideoTemplateCutGuidance = `-- name: UpdateVideoTemplateCutGuidance :execrows
UPDATE video_templates SET cut_guidance = ?, updated_at = ? WHERE id = ? AND user_id = ?
`

type UpdateVideoTemplateCutGuidanceParams struct {
	CutGuidance string
	UpdatedAt   string
	ID          string
	UserID      string
}

func (q *Queries) UpdateVideoTemplateCutGuidance(ctx context.Context, arg UpdateVideoTemplateCutGuidanceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateVideoTemplateCutGuidance,
		arg.CutGuidance,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateVideoTemplateInformationFields = `-- name: UpdateVideoTemplateInformationFields :execrows
UPDATE video_templates SET information_fields = ?, updated_at = ? WHERE id = ? AND user_id = ?
`

type UpdateVideoTemplateInformationFieldsParams struct {
	InformationFields string
	UpdatedAt         string
	ID                string
	UserID            string
}

func (q *Queries) UpdateVideoTemplateInformationFields(ctx context.Context, arg UpdateVideoTemplateInformationFieldsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateVideoTemplateInformationFields,
		arg.InformationFields,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateVideoTemplateName = `-- name: UpdateVideoTemplateName :execrows
UPDATE video_templates SET name = ?, updated_at = ? WHERE id = ? AND user_id = ?
`

type UpdateVideoTemplateNameParams struct {
	Name      string
	UpdatedAt string
	ID        string
	UserID    string
}

func (q *Queries) UpdateVideoTemplateName(ctx context.Context, arg UpdateVideoTemplateNameParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateVideoTemplateName,
		arg.Name,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateVideoTemplatePreset = `-- name: UpdateVideoTemplatePreset :execrows
UPDATE video_templates SET preset = ?, updated_at = ? WHERE id = ? AND user_id = ?
`

type UpdateVideoTemplatePresetParams struct {
	Preset    string
	UpdatedAt string
	ID        string
	UserID    string
}

func (q *Queries) UpdateVideoTemplatePreset(ctx context.Context, arg UpdateVideoTemplatePresetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateVideoTemplatePreset,
		arg.Preset,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertClipAnswer = `-- name: UpsertClipAnswer :exec
INSERT INTO clip_project_answers(project_id, user_id, label, answer, updated_at) VALUES (?, ?, ?, ?, ?)
ON CONFLICT(project_id, label) DO UPDATE SET answer = excluded.answer, updated_at = excluded.updated_at WHERE user_id = excluded.user_id
`

type UpsertClipAnswerParams struct {
	ProjectID string
	UserID    string
	Label     string
	Answer    string
	UpdatedAt string
}

func (q *Queries) UpsertClipAnswer(ctx context.Context, arg UpsertClipAnswerParams) error {
	_, err := q.db.ExecContext(ctx, upsertClipAnswer,
		arg.ProjectID,
		arg.UserID,
		arg.Label,
		arg.Answer,
		arg.UpdatedAt,
	)
	return err
}
