// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: export_benefits.sql

package sqlc

import (
	"context"
	"database/sql"
)

const currentExportWindow = `-- name: CurrentExportWindow :one
SELECT user_id,coverage_id,window_start,window_end,allowance,used,reserved,correlation_id
FROM server_export_windows
WHERE user_id=? AND window_start<=? AND window_end>?
ORDER BY window_start DESC LIMIT 1
`

type CurrentExportWindowParams struct {
	UserID      string
	WindowStart string
	WindowEnd   string
}

func (q *Queries) CurrentExportWindow(ctx context.Context, arg CurrentExportWindowParams) (ServerExportWindow, error) {
	row := q.db.QueryRowContext(ctx, currentExportWindow, arg.UserID, arg.WindowStart, arg.WindowEnd)
	var i ServerExportWindow
	err := row.Scan(
		&i.UserID,
		&i.CoverageID,
		&i.WindowStart,
		&i.WindowEnd,
		&i.Allowance,
		&i.Used,
		&i.Reserved,
		&i.CorrelationID,
	)
	return i, err
}

const insertExportAdjustment = `-- name: InsertExportAdjustment :execrows
INSERT INTO server_export_adjustments(correlation_id,user_id,coverage_id,window_start,allowance_delta)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(correlation_id) DO NOTHING
`

type InsertExportAdjustmentParams struct {
	CorrelationID  string
	UserID         string
	CoverageID     string
	WindowStart    string
	AllowanceDelta int64
}

func (q *Queries) InsertExportAdjustment(ctx context.Context, arg InsertExportAdjustmentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertExportAdjustment,
		arg.CorrelationID,
		arg.UserID,
		arg.CoverageID,
		arg.WindowStart,
		arg.AllowanceDelta,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertExportWindow = `-- name: InsertExportWindow :execrows
INSERT INTO server_export_windows(user_id,coverage_id,window_start,window_end,allowance,correlation_id)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(user_id,coverage_id,window_start) DO UPDATE SET window_end=excluded.window_end
WHERE server_export_windows.window_end < excluded.window_end
`

type InsertExportWindowParams struct {
	UserID        string
	CoverageID    string
	WindowStart   string
	WindowEnd     string
	Allowance     int64
	CorrelationID sql.NullString
}

// Clip owns the server-export allowance, separate from AI-credit lots.
func (q *Queries) InsertExportWindow(ctx context.Context, arg InsertExportWindowParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertExportWindow,
		arg.UserID,
		arg.CoverageID,
		arg.WindowStart,
		arg.WindowEnd,
		arg.Allowance,
		arg.CorrelationID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const raiseExportAllowance = `-- name: RaiseExportAllowance :execrows
UPDATE server_export_windows SET allowance=allowance+?
WHERE user_id=? AND coverage_id=? AND window_start=?
`

type RaiseExportAllowanceParams struct {
	Allowance   int64
	UserID      string
	CoverageID  string
	WindowStart string
}

func (q *Queries) RaiseExportAllowance(ctx context.Context, arg RaiseExportAllowanceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, raiseExportAllowance,
		arg.Allowance,
		arg.UserID,
		arg.CoverageID,
		arg.WindowStart,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
