// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media_artifacts.sql

package sqlc

import (
	"context"
	"database/sql"
)

const acceptMediaArtifact = `-- name: AcceptMediaArtifact :execrows
UPDATE clip_media_artifacts SET state='accepted',actual_bytes=exact_bytes,accepted_at=?1
WHERE attempt_id=?2 AND slot=?3 AND metadata_json=?4 AND state='reserved' AND exact_bytes>0
`

type AcceptMediaArtifactParams struct {
	Now       sql.NullString
	AttemptID string
	Slot      string
	Metadata  string
}

func (q *Queries) AcceptMediaArtifact(ctx context.Context, arg AcceptMediaArtifactParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, acceptMediaArtifact,
		arg.Now,
		arg.AttemptID,
		arg.Slot,
		arg.Metadata,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const consumeMediaRender = `-- name: ConsumeMediaRender :execrows
UPDATE clip_media_artifacts SET canonical=1
WHERE attempt_id=?1 AND slot='result' AND object_key=?2 AND state='accepted'
`

type ConsumeMediaRenderParams struct {
	AttemptID string
	ObjectKey string
}

func (q *Queries) ConsumeMediaRender(ctx context.Context, arg ConsumeMediaRenderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeMediaRender, arg.AttemptID, arg.ObjectKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const extendMediaPutExpiry = `-- name: ExtendMediaPutExpiry :exec
UPDATE clip_media_artifacts SET put_expires_at=MAX(COALESCE(put_expires_at,created_at),?1) WHERE attempt_id=?2 AND slot=?3
`

type ExtendMediaPutExpiryParams struct {
	ExpiresAt interface{}
	AttemptID string
	Slot      string
}

func (q *Queries) ExtendMediaPutExpiry(ctx context.Context, arg ExtendMediaPutExpiryParams) error {
	_, err := q.db.ExecContext(ctx, extendMediaPutExpiry, arg.ExpiresAt, arg.AttemptID, arg.Slot)
	return err
}

const getMediaArtifact = `-- name: GetMediaArtifact :one
SELECT attempt_id, slot, object_key, content_type, max_bytes, state, created_at, exact_bytes, metadata_json, actual_bytes, worker_digest, put_expires_at, accepted_at, canonical FROM clip_media_artifacts WHERE attempt_id=? AND slot=?
`

type GetMediaArtifactParams struct {
	AttemptID string
	Slot      string
}

func (q *Queries) GetMediaArtifact(ctx context.Context, arg GetMediaArtifactParams) (ClipMediaArtifact, error) {
	row := q.db.QueryRowContext(ctx, getMediaArtifact, arg.AttemptID, arg.Slot)
	var i ClipMediaArtifact
	err := row.Scan(
		&i.AttemptID,
		&i.Slot,
		&i.ObjectKey,
		&i.ContentType,
		&i.MaxBytes,
		&i.State,
		&i.CreatedAt,
		&i.ExactBytes,
		&i.MetadataJson,
		&i.ActualBytes,
		&i.WorkerDigest,
		&i.PutExpiresAt,
		&i.AcceptedAt,
		&i.Canonical,
	)
	return i, err
}

const insertMediaOutput = `-- name: InsertMediaOutput :exec
INSERT INTO clip_media_artifacts(attempt_id,slot,object_key,content_type,max_bytes,exact_bytes,metadata_json,worker_digest,put_expires_at,created_at)
VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(attempt_id,slot) DO NOTHING
`

type InsertMediaOutputParams struct {
	AttemptID    string
	Slot         string
	ObjectKey    string
	ContentType  string
	MaxBytes     int64
	ExactBytes   int64
	MetadataJson string
	WorkerDigest string
	PutExpiresAt sql.NullString
	CreatedAt    string
}

func (q *Queries) InsertMediaOutput(ctx context.Context, arg InsertMediaOutputParams) error {
	_, err := q.db.ExecContext(ctx, insertMediaOutput,
		arg.AttemptID,
		arg.Slot,
		arg.ObjectKey,
		arg.ContentType,
		arg.MaxBytes,
		arg.ExactBytes,
		arg.MetadataJson,
		arg.WorkerDigest,
		arg.PutExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const listMediaArtifacts = `-- name: ListMediaArtifacts :many
SELECT attempt_id, slot, object_key, content_type, max_bytes, state, created_at, exact_bytes, metadata_json, actual_bytes, worker_digest, put_expires_at, accepted_at, canonical FROM clip_media_artifacts WHERE attempt_id=? ORDER BY slot
`

func (q *Queries) ListMediaArtifacts(ctx context.Context, attemptID string) ([]ClipMediaArtifact, error) {
	rows, err := q.db.QueryContext(ctx, listMediaArtifacts, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClipMediaArtifact
	for rows.Next() {
		var i ClipMediaArtifact
		if err := rows.Scan(
			&i.AttemptID,
			&i.Slot,
			&i.ObjectKey,
			&i.ContentType,
			&i.MaxBytes,
			&i.State,
			&i.CreatedAt,
			&i.ExactBytes,
			&i.MetadataJson,
			&i.ActualBytes,
			&i.WorkerDigest,
			&i.PutExpiresAt,
			&i.AcceptedAt,
			&i.Canonical,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
