// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media_recovery.sql

package sqlc

import (
	"context"
	"database/sql"
)

const dueMediaDeletions = `-- name: DueMediaDeletions :many
SELECT object_key, not_before, created_at FROM clip_media_deletions d WHERE d.not_before<=?1
 AND NOT EXISTS(SELECT 1 FROM clip_projects p WHERE p.result_key=d.object_key)
 AND NOT EXISTS(SELECT 1 FROM clip_attempt_results r WHERE r.result_key=d.object_key)
 AND NOT EXISTS(SELECT 1 FROM clip_media_artifacts a WHERE a.object_key=d.object_key)
ORDER BY d.not_before,d.object_key LIMIT 100
`

func (q *Queries) DueMediaDeletions(ctx context.Context, cutoff string) ([]ClipMediaDeletion, error) {
	rows, err := q.db.QueryContext(ctx, dueMediaDeletions, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClipMediaDeletion
	for rows.Next() {
		var i ClipMediaDeletion
		if err := rows.Scan(&i.ObjectKey, &i.NotBefore, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMediaReconciled = `-- name: MarkMediaReconciled :exec
UPDATE clip_media_stages SET reconciled_at=? WHERE id=?
`

type MarkMediaReconciledParams struct {
	ReconciledAt sql.NullString
	ID           string
}

func (q *Queries) MarkMediaReconciled(ctx context.Context, arg MarkMediaReconciledParams) error {
	_, err := q.db.ExecContext(ctx, markMediaReconciled, arg.ReconciledAt, arg.ID)
	return err
}

const mediaRecoveryStages = `-- name: MediaRecoveryStages :many
SELECT id, parent_job_id, user_id, project_id, expected_revision, stage_key, operation, contract_version, input_digest, input_payload, renderer_version, asset_version, state, current_attempt_id, attempt_count, created_at, queue_deadline_at, deadline_at, lease_ttl_ns, attempt_limit, accepted_result, failure, retry_not_before, failure_detail, reconciled_at FROM clip_media_stages WHERE reconciled_at IS NULL AND id>?1 ORDER BY id LIMIT 100
`

func (q *Queries) MediaRecoveryStages(ctx context.Context, afterID string) ([]ClipMediaStage, error) {
	rows, err := q.db.QueryContext(ctx, mediaRecoveryStages, afterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClipMediaStage
	for rows.Next() {
		var i ClipMediaStage
		if err := rows.Scan(
			&i.ID,
			&i.ParentJobID,
			&i.UserID,
			&i.ProjectID,
			&i.ExpectedRevision,
			&i.StageKey,
			&i.Operation,
			&i.ContractVersion,
			&i.InputDigest,
			&i.InputPayload,
			&i.RendererVersion,
			&i.AssetVersion,
			&i.State,
			&i.CurrentAttemptID,
			&i.AttemptCount,
			&i.CreatedAt,
			&i.QueueDeadlineAt,
			&i.DeadlineAt,
			&i.LeaseTtlNs,
			&i.AttemptLimit,
			&i.AcceptedResult,
			&i.Failure,
			&i.RetryNotBefore,
			&i.FailureDetail,
			&i.ReconciledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueOrphanMediaDeletion = `-- name: QueueOrphanMediaDeletion :exec
INSERT INTO clip_media_deletions(object_key,not_before,created_at)
SELECT ?1,?2,?2
WHERE NOT EXISTS(SELECT 1 FROM clip_media_artifacts WHERE object_key=?1)
 AND NOT EXISTS(SELECT 1 FROM clip_projects WHERE result_key=?1)
 AND NOT EXISTS(SELECT 1 FROM clip_attempt_results WHERE result_key=?1)
ON CONFLICT(object_key) DO NOTHING
`

type QueueOrphanMediaDeletionParams struct {
	ObjectKey string
	Now       string
}

func (q *Queries) QueueOrphanMediaDeletion(ctx context.Context, arg QueueOrphanMediaDeletionParams) error {
	_, err := q.db.ExecContext(ctx, queueOrphanMediaDeletion, arg.ObjectKey, arg.Now)
	return err
}

const removeMediaDeletion = `-- name: RemoveMediaDeletion :exec
DELETE FROM clip_media_deletions WHERE object_key=?
`

func (q *Queries) RemoveMediaDeletion(ctx context.Context, objectKey string) error {
	_, err := q.db.ExecContext(ctx, removeMediaDeletion, objectKey)
	return err
}

const retireMediaStageArtifacts = `-- name: RetireMediaStageArtifacts :exec
DELETE FROM clip_media_artifacts WHERE canonical=0 AND attempt_id IN
(SELECT id FROM clip_media_attempts WHERE stage_id=?1 AND (?2=1 OR id!=?3))
`

type RetireMediaStageArtifactsParams struct {
	StageID          string
	AllAttempts      interface{}
	CurrentAttemptID string
}

func (q *Queries) RetireMediaStageArtifacts(ctx context.Context, arg RetireMediaStageArtifactsParams) error {
	_, err := q.db.ExecContext(ctx, retireMediaStageArtifacts, arg.StageID, arg.AllAttempts, arg.CurrentAttemptID)
	return err
}

const retireSupersededMediaResults = `-- name: RetireSupersededMediaResults :exec
DELETE FROM clip_media_artifacts WHERE object_key IN
(SELECT a.object_key FROM clip_media_artifacts a WHERE a.canonical=1
 AND NOT EXISTS(SELECT 1 FROM clip_projects p WHERE p.result_key=a.object_key)
 AND NOT EXISTS(SELECT 1 FROM clip_attempt_results r WHERE r.result_key=a.object_key)
 ORDER BY a.object_key LIMIT 100)
`

func (q *Queries) RetireSupersededMediaResults(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, retireSupersededMediaResults)
	return err
}

const setMediaRecoveryState = `-- name: SetMediaRecoveryState :exec
UPDATE clip_media_stages SET state=?1,failure_detail=NULL,failure=?2,retry_not_before=?3
WHERE id=?4 AND state!='succeeded'
`

type SetMediaRecoveryStateParams struct {
	State          string
	Failure        sql.NullString
	RetryNotBefore sql.NullString
	ID             string
}

func (q *Queries) SetMediaRecoveryState(ctx context.Context, arg SetMediaRecoveryStateParams) error {
	_, err := q.db.ExecContext(ctx, setMediaRecoveryState,
		arg.State,
		arg.Failure,
		arg.RetryNotBefore,
		arg.ID,
	)
	return err
}

const stopMediaAttempt = `-- name: StopMediaAttempt :exec
UPDATE clip_media_attempts SET outcome=?1,finished_at=?2
WHERE id=?3 AND outcome IS NULL
`

type StopMediaAttemptParams struct {
	Outcome sql.NullString
	Now     sql.NullString
	ID      string
}

func (q *Queries) StopMediaAttempt(ctx context.Context, arg StopMediaAttemptParams) error {
	_, err := q.db.ExecContext(ctx, stopMediaAttempt, arg.Outcome, arg.Now, arg.ID)
	return err
}
