// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type ClipProject struct {
	ID                   string
	UserID               string
	Title                string
	VideoTemplateID      sql.NullString
	Ratio                string
	TargetDurationMs     int64
	AnalysisJson         sql.NullString
	EditPlanJson         sql.NullString
	ResultKey            sql.NullString
	ResultContentType    sql.NullString
	ResultBytes          sql.NullInt64
	ResultDurationMs     sql.NullInt64
	ResultCreatedAt      sql.NullString
	EditPlanRevision     int64
	RenderedPlanRevision int64
	CreatedAt            string
	UpdatedAt            string
}

type VideoTemplate struct {
	ID                string
	UserID            string
	Name              string
	InformationFields string
	CutGuidance       string
	CopyStyles        string
	Accent            sql.NullString
	CreatedAt         string
	UpdatedAt         string
}
