// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type ClipAttemptResult struct {
	JobID             string
	UserID            string
	ProjectID         string
	ExpectedRevision  int64
	AnalysisJson      string
	EditPlanJson      string
	ResultKey         string
	ResultContentType string
	ResultBytes       int64
	ResultDurationMs  int64
	ResultCreatedAt   string
	RenderKind        string
}

type ClipBrowserRender struct {
	ID           string
	UserID       string
	ProjectID    string
	PlanRevision int64
	Ratio        string
	DurationMs   int64
	HasAudio     int64
	CreatedAt    string
	VerdictJson  sql.NullString
	ReportedAt   sql.NullString
	UploadBytes  int64
	StoredAt     sql.NullString
	CancelledAt  sql.NullString
}

type ClipGenerationQuote struct {
	ID            string
	UserID        string
	ProjectID     string
	BatchID       string
	InputDigest   string
	PricingJson   string
	MaxCredits    int64
	ExpiresAt     string
	ConsumedJobID sql.NullString
}

type ClipMediaArtifact struct {
	AttemptID    string
	Slot         string
	ObjectKey    string
	ContentType  string
	MaxBytes     int64
	State        string
	CreatedAt    string
	ExactBytes   int64
	MetadataJson string
	ActualBytes  sql.NullInt64
	WorkerDigest string
	PutExpiresAt sql.NullString
	AcceptedAt   sql.NullString
	Canonical    int64
}

type ClipMediaAttempt struct {
	ID              string
	StageID         string
	Ordinal         int64
	WorkerID        string
	TokenHash       string
	LeaseExpiresAt  string
	StartedAt       string
	FinishedAt      sql.NullString
	SelectedProfile string
	RuntimeManifest string
	Progress        int64
	Outcome         sql.NullString
}

type ClipMediaStage struct {
	ID               string
	ParentJobID      string
	UserID           string
	ProjectID        string
	ExpectedRevision int64
	StageKey         string
	Operation        string
	ContractVersion  int64
	InputDigest      string
	InputPayload     string
	RendererVersion  string
	AssetVersion     string
	State            string
	CurrentAttemptID sql.NullString
	AttemptCount     int64
	CreatedAt        string
	QueueDeadlineAt  string
	DeadlineAt       string
	LeaseTtlNs       int64
	AttemptLimit     int64
	AcceptedResult   sql.NullString
	Failure          sql.NullString
}

type ClipProject struct {
	ID                       string
	UserID                   string
	Title                    string
	VideoTemplateID          sql.NullString
	Ratio                    string
	TargetDurationMs         int64
	AnalysisJson             sql.NullString
	EditPlanJson             sql.NullString
	ResultKey                sql.NullString
	ResultContentType        sql.NullString
	ResultBytes              sql.NullInt64
	ResultDurationMs         sql.NullInt64
	ResultCreatedAt          sql.NullString
	EditPlanRevision         int64
	RenderedPlanRevision     int64
	CreatedAt                string
	UpdatedAt                string
	Deleting                 int64
	Disclosure               string
	Cta                      string
	HideDisclosure           int64
	CompositionInputsJson    sql.NullString
	CompositionSnapshotJson  sql.NullString
	SourceRetentionExpiresAt sql.NullString
	SourceAccessRevokedAt    sql.NullString
	SourceBatchID            sql.NullString
	ResultID                 sql.NullString
	FinalizedAt              sql.NullString
	FinalizedPlanRevision    sql.NullInt64
	FinalizedResultKey       sql.NullString
	Language                 string
	Instruction              string
	CaptionPace              string
	Accent                   string
	IntroPreset              string
	OutroPreset              string
	AllowedCaptionStyles     string
	RenderKind               string
}

type ClipSourceAttempt struct {
	JobID        string
	UserID       string
	ProjectID    string
	BatchID      string
	ManifestJson string
	BoundAt      string
	ReleasedAt   sql.NullString
}

type ClipSourceBatch struct {
	ID           string
	UserID       string
	ProjectID    string
	State        string
	CreatedAt    string
	ExpiresAt    string
	JobID        sql.NullString
	PutExpiresAt string
}

type ClipSourceLease struct {
	ID                  string
	BatchID             string
	UserID              string
	ObjectKey           string
	Filename            string
	ContentType         string
	Fingerprint         string
	DeclaredBytes       int64
	ActualBytes         int64
	DurationMs          int64
	Width               int64
	Height              int64
	State               string
	Ordinal             int64
	CanonicalID         string
	RetentionExpiresAt  sql.NullString
	CleanupPending      int64
	RetainOriginalAudio int64
	Position            int64
}

type VideoTemplate struct {
	ID                string
	UserID            string
	Name              string
	InformationFields string
	CutGuidance       string
	CopyStyles        string
	Accent            sql.NullString
	CreatedAt         string
	UpdatedAt         string
	Preset            string
	CaptionPace       string
	CompositionBody   sql.NullString
	CompositionLegacy int64
}
