// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quotes.sql

package sqlc

import (
	"context"
	"database/sql"
)

const consumeClipQuote = `-- name: ConsumeClipQuote :execrows
UPDATE clip_generation_quotes SET consumed_job_id=? WHERE user_id=? AND id=? AND consumed_job_id IS NULL AND expires_at>?
`

type ConsumeClipQuoteParams struct {
	ConsumedJobID sql.NullString
	UserID        string
	ID            string
	ExpiresAt     string
}

func (q *Queries) ConsumeClipQuote(ctx context.Context, arg ConsumeClipQuoteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeClipQuote,
		arg.ConsumedJobID,
		arg.UserID,
		arg.ID,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getClipQuote = `-- name: GetClipQuote :one
SELECT id, user_id, project_id, batch_id, input_digest, pricing_json, max_credits, expires_at, consumed_job_id FROM clip_generation_quotes WHERE user_id=? AND id=?
`

type GetClipQuoteParams struct {
	UserID string
	ID     string
}

func (q *Queries) GetClipQuote(ctx context.Context, arg GetClipQuoteParams) (ClipGenerationQuote, error) {
	row := q.db.QueryRowContext(ctx, getClipQuote, arg.UserID, arg.ID)
	var i ClipGenerationQuote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.BatchID,
		&i.InputDigest,
		&i.PricingJson,
		&i.MaxCredits,
		&i.ExpiresAt,
		&i.ConsumedJobID,
	)
	return i, err
}

const saveClipQuote = `-- name: SaveClipQuote :execrows
INSERT INTO clip_generation_quotes(id,user_id,project_id,batch_id,input_digest,pricing_json,max_credits,expires_at)
VALUES (?,?,?,?,?,?,?,?)
ON CONFLICT(batch_id) DO UPDATE SET id=excluded.id,input_digest=excluded.input_digest,pricing_json=excluded.pricing_json,max_credits=excluded.max_credits,expires_at=excluded.expires_at
WHERE clip_generation_quotes.consumed_job_id IS NULL AND clip_generation_quotes.user_id=excluded.user_id AND clip_generation_quotes.project_id=excluded.project_id
`

type SaveClipQuoteParams struct {
	ID          string
	UserID      string
	ProjectID   string
	BatchID     string
	InputDigest string
	PricingJson string
	MaxCredits  int64
	ExpiresAt   string
}

func (q *Queries) SaveClipQuote(ctx context.Context, arg SaveClipQuoteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveClipQuote,
		arg.ID,
		arg.UserID,
		arg.ProjectID,
		arg.BatchID,
		arg.InputDigest,
		arg.PricingJson,
		arg.MaxCredits,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
