// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recovery.sql

package sqlc

import (
	"context"
)

const correctClipSpokenRecovery = `-- name: CorrectClipSpokenRecovery :execrows
UPDATE clip_recovery_states SET state_json=?1
WHERE clip_recovery_states.project_id=?2 AND clip_recovery_states.user_id=?3 AND clip_recovery_states.state_json=?4
AND EXISTS(SELECT 1 FROM clip_projects p WHERE p.id=clip_recovery_states.project_id AND p.user_id=clip_recovery_states.user_id AND p.deleting=0 AND p.finalized_at IS NULL AND p.edit_plan_json IS NULL)
AND NOT EXISTS(SELECT 1 FROM generation_jobs j WHERE j.clip_project_id=clip_recovery_states.project_id AND j.user_id=clip_recovery_states.user_id AND j.status IN ('queued','running'))
`

type CorrectClipSpokenRecoveryParams struct {
	StateJson    string
	ProjectID    string
	UserID       string
	ExpectedJson string
}

func (q *Queries) CorrectClipSpokenRecovery(ctx context.Context, arg CorrectClipSpokenRecoveryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, correctClipSpokenRecovery,
		arg.StateJson,
		arg.ProjectID,
		arg.UserID,
		arg.ExpectedJson,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getClipRecovery = `-- name: GetClipRecovery :one
SELECT r.job_id,r.state_json FROM clip_recovery_states r JOIN clip_projects p ON p.id=r.project_id AND p.user_id=r.user_id
WHERE r.project_id=?1 AND r.user_id=?2 AND p.deleting=0 AND p.finalized_at IS NULL
`

type GetClipRecoveryParams struct {
	ProjectID string
	UserID    string
}

type GetClipRecoveryRow struct {
	JobID     string
	StateJson string
}

func (q *Queries) GetClipRecovery(ctx context.Context, arg GetClipRecoveryParams) (GetClipRecoveryRow, error) {
	row := q.db.QueryRowContext(ctx, getClipRecovery, arg.ProjectID, arg.UserID)
	var i GetClipRecoveryRow
	err := row.Scan(&i.JobID, &i.StateJson)
	return i, err
}

const saveClipRecovery = `-- name: SaveClipRecovery :execrows
INSERT INTO clip_recovery_states(project_id,user_id,job_id,state_json)
SELECT p.id,p.user_id,j.id,?1 FROM clip_projects p JOIN generation_jobs j ON j.clip_project_id=p.id AND j.user_id=p.user_id
WHERE p.id=?2 AND p.user_id=?3 AND j.id=?4
AND p.deleting=0 AND p.finalized_at IS NULL AND j.status IN ('queued','running')
ON CONFLICT(project_id) DO UPDATE SET user_id=excluded.user_id,job_id=excluded.job_id,state_json=excluded.state_json
`

type SaveClipRecoveryParams struct {
	StateJson string
	ProjectID string
	UserID    string
	JobID     string
}

// The unique active-clip-job index makes this attempt the only live writer.
// A terminal predecessor can have a later timestamp after a clock rollback.
func (q *Queries) SaveClipRecovery(ctx context.Context, arg SaveClipRecoveryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveClipRecovery,
		arg.StateJson,
		arg.ProjectID,
		arg.UserID,
		arg.JobID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
