// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countActiveSourceAttempts = `-- name: CountActiveSourceAttempts :one
SELECT COUNT(*) FROM clip_source_attempts WHERE batch_id=? AND released_at IS NULL
`

func (q *Queries) CountActiveSourceAttempts(ctx context.Context, batchID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveSourceAttempts, batchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const fenceSourceAccess = `-- name: FenceSourceAccess :execrows
UPDATE clip_projects SET source_access_revoked_at=COALESCE(source_access_revoked_at,?) WHERE id=? AND user_id=?
`

type FenceSourceAccessParams struct {
	SourceAccessRevokedAt sql.NullString
	ID                    string
	UserID                string
}

func (q *Queries) FenceSourceAccess(ctx context.Context, arg FenceSourceAccessParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, fenceSourceAccess, arg.SourceAccessRevokedAt, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSourceAttempt = `-- name: GetSourceAttempt :one
SELECT job_id, user_id, project_id, batch_id, manifest_json, bound_at, released_at FROM clip_source_attempts WHERE user_id=? AND job_id=?
`

type GetSourceAttemptParams struct {
	UserID string
	JobID  string
}

func (q *Queries) GetSourceAttempt(ctx context.Context, arg GetSourceAttemptParams) (ClipSourceAttempt, error) {
	row := q.db.QueryRowContext(ctx, getSourceAttempt, arg.UserID, arg.JobID)
	var i ClipSourceAttempt
	err := row.Scan(
		&i.JobID,
		&i.UserID,
		&i.ProjectID,
		&i.BatchID,
		&i.ManifestJson,
		&i.BoundAt,
		&i.ReleasedAt,
	)
	return i, err
}

const insertSourceAttempt = `-- name: InsertSourceAttempt :exec
INSERT INTO clip_source_attempts(job_id,user_id,project_id,batch_id,manifest_json,bound_at) VALUES (?,?,?,?,?,?)
`

type InsertSourceAttemptParams struct {
	JobID        string
	UserID       string
	ProjectID    string
	BatchID      string
	ManifestJson string
	BoundAt      string
}

func (q *Queries) InsertSourceAttempt(ctx context.Context, arg InsertSourceAttemptParams) error {
	_, err := q.db.ExecContext(ctx, insertSourceAttempt,
		arg.JobID,
		arg.UserID,
		arg.ProjectID,
		arg.BatchID,
		arg.ManifestJson,
		arg.BoundAt,
	)
	return err
}

const listPartialSourceCleanup = `-- name: ListPartialSourceCleanup :many
SELECT id, user_id, project_id, state, created_at, expires_at, job_id, put_expires_at FROM clip_source_batches b WHERE b.state NOT IN ('cleanup_pending','consuming') AND (EXISTS(SELECT 1 FROM clip_source_leases l WHERE l.batch_id=b.id AND l.cleanup_pending=1) OR EXISTS(SELECT 1 FROM clip_proxy_leases p WHERE p.batch_id=b.id)) AND NOT EXISTS(SELECT 1 FROM clip_source_attempts a WHERE a.batch_id=b.id AND a.released_at IS NULL)
`

func (q *Queries) ListPartialSourceCleanup(ctx context.Context) ([]ClipSourceBatch, error) {
	rows, err := q.db.QueryContext(ctx, listPartialSourceCleanup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClipSourceBatch
	for rows.Next() {
		var i ClipSourceBatch
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.State,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.JobID,
			&i.PutExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBatchLeasesCleanup = `-- name: MarkBatchLeasesCleanup :exec
UPDATE clip_source_leases SET cleanup_pending=1 WHERE batch_id=?
`

func (q *Queries) MarkBatchLeasesCleanup(ctx context.Context, batchID string) error {
	_, err := q.db.ExecContext(ctx, markBatchLeasesCleanup, batchID)
	return err
}

const markExpiredSourceLeases = `-- name: MarkExpiredSourceLeases :exec
UPDATE clip_source_leases SET cleanup_pending=1
WHERE cleanup_pending=0 AND EXISTS(SELECT 1 FROM clip_source_batches b WHERE b.id=clip_source_leases.batch_id AND b.state!='consuming') AND NOT EXISTS (SELECT 1 FROM clip_source_attempts a WHERE a.batch_id=clip_source_leases.batch_id AND a.released_at IS NULL)
AND (retention_expires_at<=?1 OR (state='pending' AND EXISTS(SELECT 1 FROM clip_source_batches b WHERE b.id=clip_source_leases.batch_id AND b.expires_at<=?1)))
`

func (q *Queries) MarkExpiredSourceLeases(ctx context.Context, now sql.NullString) error {
	_, err := q.db.ExecContext(ctx, markExpiredSourceLeases, now)
	return err
}

const refreshProjectRetention = `-- name: RefreshProjectRetention :exec
UPDATE clip_projects SET source_retention_expires_at=(SELECT MAX(l.retention_expires_at) FROM clip_source_leases l JOIN clip_source_batches b ON b.id=l.batch_id WHERE b.project_id=clip_projects.id AND b.user_id=clip_projects.user_id AND b.state!='cleanup_pending' AND l.cleanup_pending=0) WHERE clip_projects.id=? AND clip_projects.user_id=? AND clip_projects.source_access_revoked_at IS NULL
`

type RefreshProjectRetentionParams struct {
	ID     string
	UserID string
}

func (q *Queries) RefreshProjectRetention(ctx context.Context, arg RefreshProjectRetentionParams) error {
	_, err := q.db.ExecContext(ctx, refreshProjectRetention, arg.ID, arg.UserID)
	return err
}

const releaseSourceAttempt = `-- name: ReleaseSourceAttempt :execrows
UPDATE clip_source_attempts SET released_at=? WHERE user_id=? AND job_id=? AND released_at IS NULL
`

type ReleaseSourceAttemptParams struct {
	ReleasedAt sql.NullString
	UserID     string
	JobID      string
}

func (q *Queries) ReleaseSourceAttempt(ctx context.Context, arg ReleaseSourceAttemptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, releaseSourceAttempt, arg.ReleasedAt, arg.UserID, arg.JobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const restoreSourceBatch = `-- name: RestoreSourceBatch :exec
UPDATE clip_source_batches SET state='ready' WHERE id=? AND state='consuming' AND NOT EXISTS(SELECT 1 FROM clip_source_attempts a WHERE a.batch_id=clip_source_batches.id AND a.released_at IS NULL)
`

func (q *Queries) RestoreSourceBatch(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, restoreSourceBatch, id)
	return err
}

const selectSourceBatch = `-- name: SelectSourceBatch :execrows
UPDATE clip_projects SET source_batch_id=? WHERE id=? AND user_id=? AND deleting=0 AND finalized_at IS NULL AND source_access_revoked_at IS NULL
`

type SelectSourceBatchParams struct {
	SourceBatchID sql.NullString
	ID            string
	UserID        string
}

func (q *Queries) SelectSourceBatch(ctx context.Context, arg SelectSourceBatchParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, selectSourceBatch, arg.SourceBatchID, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setBoundSourceRetention = `-- name: SetBoundSourceRetention :exec
UPDATE clip_source_leases SET retention_expires_at=MAX(COALESCE(retention_expires_at,''),?1)
WHERE batch_id=?2 AND state='ready' AND cleanup_pending=0
AND EXISTS (SELECT 1 FROM clip_source_batches b JOIN clip_projects p ON p.id=b.project_id AND p.user_id=b.user_id WHERE b.id=?2 AND b.state!='cleanup_pending' AND p.deleting=0 AND p.source_access_revoked_at IS NULL)
`

type SetBoundSourceRetentionParams struct {
	ExpiresAt interface{}
	BatchID   string
}

func (q *Queries) SetBoundSourceRetention(ctx context.Context, arg SetBoundSourceRetentionParams) error {
	_, err := q.db.ExecContext(ctx, setBoundSourceRetention, arg.ExpiresAt, arg.BatchID)
	return err
}

const setSourceRetention = `-- name: SetSourceRetention :exec
UPDATE clip_source_leases SET retention_expires_at=?1
WHERE batch_id IN (SELECT clip_source_batches.id FROM clip_source_batches WHERE clip_source_batches.project_id=?2 AND clip_source_batches.user_id=?3 AND clip_source_batches.state!='cleanup_pending')
AND state='ready' AND cleanup_pending=0 AND retention_expires_at>?4
AND EXISTS (SELECT 1 FROM clip_projects WHERE clip_projects.id=?2 AND clip_projects.user_id=?3 AND clip_projects.deleting=0 AND clip_projects.source_access_revoked_at IS NULL)
`

type SetSourceRetentionParams struct {
	ExpiresAt sql.NullString
	ProjectID string
	UserID    string
	Now       sql.NullString
}

func (q *Queries) SetSourceRetention(ctx context.Context, arg SetSourceRetentionParams) error {
	_, err := q.db.ExecContext(ctx, setSourceRetention,
		arg.ExpiresAt,
		arg.ProjectID,
		arg.UserID,
		arg.Now,
	)
	return err
}

const sourceProjectAccess = `-- name: SourceProjectAccess :one
SELECT source_batch_id,source_access_revoked_at,source_retention_expires_at,deleting,finalized_at FROM clip_projects WHERE id=? AND user_id=?
`

type SourceProjectAccessParams struct {
	ID     string
	UserID string
}

type SourceProjectAccessRow struct {
	SourceBatchID            sql.NullString
	SourceAccessRevokedAt    sql.NullString
	SourceRetentionExpiresAt sql.NullString
	Deleting                 int64
	FinalizedAt              sql.NullString
}

func (q *Queries) SourceProjectAccess(ctx context.Context, arg SourceProjectAccessParams) (SourceProjectAccessRow, error) {
	row := q.db.QueryRowContext(ctx, sourceProjectAccess, arg.ID, arg.UserID)
	var i SourceProjectAccessRow
	err := row.Scan(
		&i.SourceBatchID,
		&i.SourceAccessRevokedAt,
		&i.SourceRetentionExpiresAt,
		&i.Deleting,
		&i.FinalizedAt,
	)
	return i, err
}

const unreleasedSourceAttempts = `-- name: UnreleasedSourceAttempts :many
SELECT job_id, user_id, project_id, batch_id, manifest_json, bound_at, released_at FROM clip_source_attempts WHERE released_at IS NULL ORDER BY bound_at,job_id
`

func (q *Queries) UnreleasedSourceAttempts(ctx context.Context) ([]ClipSourceAttempt, error) {
	rows, err := q.db.QueryContext(ctx, unreleasedSourceAttempts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClipSourceAttempt
	for rows.Next() {
		var i ClipSourceAttempt
		if err := rows.Scan(
			&i.JobID,
			&i.UserID,
			&i.ProjectID,
			&i.BatchID,
			&i.ManifestJson,
			&i.BoundAt,
			&i.ReleasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
