// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteAllSourceBatches = `-- name: DeleteAllSourceBatches :execrows
DELETE FROM clip_source_batches
`

// Source staging carries a user_id but deliberately no foreign key to users, so deleting
// every account leaves these rows behind. Only the dev fixture loader (internal/devseed)
// calls it, through cmd/seed, which the production image does not build.
func (q *Queries) DeleteAllSourceBatches(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAllSourceBatches)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const fenceSourceProjectDeletion = `-- name: FenceSourceProjectDeletion :execrows
UPDATE clip_projects SET deleting=1 WHERE id=? AND user_id=?
`

type FenceSourceProjectDeletionParams struct {
	ID     string
	UserID string
}

func (q *Queries) FenceSourceProjectDeletion(ctx context.Context, arg FenceSourceProjectDeletionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, fenceSourceProjectDeletion, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSourceBatch = `-- name: GetSourceBatch :one
SELECT id, user_id, project_id, state, created_at, expires_at, job_id, put_expires_at FROM clip_source_batches WHERE id=? AND user_id=?
`

type GetSourceBatchParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetSourceBatch(ctx context.Context, arg GetSourceBatchParams) (ClipSourceBatch, error) {
	row := q.db.QueryRowContext(ctx, getSourceBatch, arg.ID, arg.UserID)
	var i ClipSourceBatch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.State,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.JobID,
		&i.PutExpiresAt,
	)
	return i, err
}

const insertSourceBatch = `-- name: InsertSourceBatch :exec
INSERT INTO clip_source_batches(id,user_id,project_id,state,created_at,expires_at,put_expires_at) VALUES (?,?,?,?,?,?,?)
`

type InsertSourceBatchParams struct {
	ID           string
	UserID       string
	ProjectID    string
	State        string
	CreatedAt    string
	ExpiresAt    string
	PutExpiresAt string
}

func (q *Queries) InsertSourceBatch(ctx context.Context, arg InsertSourceBatchParams) error {
	_, err := q.db.ExecContext(ctx, insertSourceBatch,
		arg.ID,
		arg.UserID,
		arg.ProjectID,
		arg.State,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.PutExpiresAt,
	)
	return err
}

const insertSourceLease = `-- name: InsertSourceLease :exec
INSERT INTO clip_source_leases(id,canonical_id,batch_id,user_id,object_key,filename,content_type,fingerprint,declared_bytes,duration_ms,width,height,state,ordinal,retain_original_audio) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
`

type InsertSourceLeaseParams struct {
	ID                  string
	CanonicalID         string
	BatchID             string
	UserID              string
	ObjectKey           string
	Filename            string
	ContentType         string
	Fingerprint         string
	DeclaredBytes       int64
	DurationMs          int64
	Width               int64
	Height              int64
	State               string
	Ordinal             int64
	RetainOriginalAudio int64
}

func (q *Queries) InsertSourceLease(ctx context.Context, arg InsertSourceLeaseParams) error {
	_, err := q.db.ExecContext(ctx, insertSourceLease,
		arg.ID,
		arg.CanonicalID,
		arg.BatchID,
		arg.UserID,
		arg.ObjectKey,
		arg.Filename,
		arg.ContentType,
		arg.Fingerprint,
		arg.DeclaredBytes,
		arg.DurationMs,
		arg.Width,
		arg.Height,
		arg.State,
		arg.Ordinal,
		arg.RetainOriginalAudio,
	)
	return err
}

const listBatchProxies = `-- name: ListBatchProxies :many
SELECT object_key FROM clip_proxy_leases WHERE batch_id=?
`

func (q *Queries) ListBatchProxies(ctx context.Context, batchID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listBatchProxies, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var object_key string
		if err := rows.Scan(&object_key); err != nil {
			return nil, err
		}
		items = append(items, object_key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectSourceBatches = `-- name: ListProjectSourceBatches :many
SELECT id, user_id, project_id, state, created_at, expires_at, job_id, put_expires_at FROM clip_source_batches WHERE project_id=? AND user_id=? ORDER BY created_at,id
`

type ListProjectSourceBatchesParams struct {
	ProjectID string
	UserID    string
}

func (q *Queries) ListProjectSourceBatches(ctx context.Context, arg ListProjectSourceBatchesParams) ([]ClipSourceBatch, error) {
	rows, err := q.db.QueryContext(ctx, listProjectSourceBatches, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClipSourceBatch
	for rows.Next() {
		var i ClipSourceBatch
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.State,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.JobID,
			&i.PutExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceCleanup = `-- name: ListSourceCleanup :many
SELECT id, user_id, project_id, state, created_at, expires_at, job_id, put_expires_at FROM clip_source_batches WHERE state='cleanup_pending' AND NOT EXISTS (SELECT 1 FROM clip_source_attempts a WHERE a.batch_id=clip_source_batches.id AND a.released_at IS NULL) ORDER BY created_at,id
`

func (q *Queries) ListSourceCleanup(ctx context.Context) ([]ClipSourceBatch, error) {
	rows, err := q.db.QueryContext(ctx, listSourceCleanup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClipSourceBatch
	for rows.Next() {
		var i ClipSourceBatch
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.State,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.JobID,
			&i.PutExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceLeases = `-- name: ListSourceLeases :many
SELECT id, batch_id, user_id, object_key, filename, content_type, fingerprint, declared_bytes, actual_bytes, duration_ms, width, height, state, ordinal, canonical_id, retention_expires_at, cleanup_pending, retain_original_audio, position FROM clip_source_leases WHERE batch_id=? AND user_id=? ORDER BY position, ordinal
`

type ListSourceLeasesParams struct {
	BatchID string
	UserID  string
}

// The owner's own arrangement first, then the order they were confirmed in: a
// batch nobody arranged carries position 0 throughout and reads exactly as it
// always did (CLIP-136).
func (q *Queries) ListSourceLeases(ctx context.Context, arg ListSourceLeasesParams) ([]ClipSourceLease, error) {
	rows, err := q.db.QueryContext(ctx, listSourceLeases, arg.BatchID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClipSourceLease
	for rows.Next() {
		var i ClipSourceLease
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.UserID,
			&i.ObjectKey,
			&i.Filename,
			&i.ContentType,
			&i.Fingerprint,
			&i.DeclaredBytes,
			&i.ActualBytes,
			&i.DurationMs,
			&i.Width,
			&i.Height,
			&i.State,
			&i.Ordinal,
			&i.CanonicalID,
			&i.RetentionExpiresAt,
			&i.CleanupPending,
			&i.RetainOriginalAudio,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExpiredSources = `-- name: MarkExpiredSources :exec
UPDATE clip_source_batches SET state='cleanup_pending' WHERE state IN ('uploading','ready') AND expires_at<=? AND NOT EXISTS (SELECT 1 FROM clip_source_leases l WHERE l.batch_id=clip_source_batches.id AND l.cleanup_pending=0) AND NOT EXISTS(SELECT 1 FROM clip_source_attempts a WHERE a.batch_id=clip_source_batches.id AND a.released_at IS NULL)
`

func (q *Queries) MarkExpiredSources(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, markExpiredSources, expiresAt)
	return err
}

const markSourceBatchReady = `-- name: MarkSourceBatchReady :exec
UPDATE clip_source_batches SET state='ready' WHERE clip_source_batches.id=? AND clip_source_batches.user_id=? AND clip_source_batches.state='uploading' AND NOT EXISTS (SELECT 1 FROM clip_source_leases WHERE clip_source_leases.batch_id=clip_source_batches.id AND clip_source_leases.state!='ready')
`

type MarkSourceBatchReadyParams struct {
	ID     string
	UserID string
}

func (q *Queries) MarkSourceBatchReady(ctx context.Context, arg MarkSourceBatchReadyParams) error {
	_, err := q.db.ExecContext(ctx, markSourceBatchReady, arg.ID, arg.UserID)
	return err
}

const markSourceCleanup = `-- name: MarkSourceCleanup :execrows
UPDATE clip_source_batches SET state='cleanup_pending' WHERE id=? AND user_id=?
`

type MarkSourceCleanupParams struct {
	ID     string
	UserID string
}

func (q *Queries) MarkSourceCleanup(ctx context.Context, arg MarkSourceCleanupParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markSourceCleanup, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const projectSourceAudioChoices = `-- name: ProjectSourceAudioChoices :many
SELECT l.canonical_id, l.fingerprint, l.retain_original_audio FROM clip_source_leases l
JOIN clip_source_batches b ON b.id=l.batch_id AND b.user_id=l.user_id
WHERE b.project_id=? AND b.user_id=? ORDER BY b.created_at, b.id, l.position, l.ordinal
`

type ProjectSourceAudioChoicesParams struct {
	ProjectID string
	UserID    string
}

type ProjectSourceAudioChoicesRow struct {
	CanonicalID         string
	Fingerprint         string
	RetainOriginalAudio int64
}

// ProjectSourceAudioChoices is what the owner already decided about this
// project's footage, newest batch last, so reselecting a canonical source by
// fingerprint inherits its resolved choice instead of starting over.
func (q *Queries) ProjectSourceAudioChoices(ctx context.Context, arg ProjectSourceAudioChoicesParams) ([]ProjectSourceAudioChoicesRow, error) {
	rows, err := q.db.QueryContext(ctx, projectSourceAudioChoices, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectSourceAudioChoicesRow
	for rows.Next() {
		var i ProjectSourceAudioChoicesRow
		if err := rows.Scan(&i.CanonicalID, &i.Fingerprint, &i.RetainOriginalAudio); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSourceBatch = `-- name: RemoveSourceBatch :exec
DELETE FROM clip_source_batches WHERE clip_source_batches.id=? AND clip_source_batches.user_id=? AND state='cleanup_pending' AND put_expires_at<=? AND NOT EXISTS (SELECT 1 FROM clip_source_attempts a WHERE a.batch_id=clip_source_batches.id AND a.released_at IS NULL)
`

type RemoveSourceBatchParams struct {
	ID           string
	UserID       string
	PutExpiresAt string
}

func (q *Queries) RemoveSourceBatch(ctx context.Context, arg RemoveSourceBatchParams) error {
	_, err := q.db.ExecContext(ctx, removeSourceBatch, arg.ID, arg.UserID, arg.PutExpiresAt)
	return err
}

const setSourceLeasePosition = `-- name: SetSourceLeasePosition :execrows
UPDATE clip_source_leases SET position=?1
WHERE canonical_id=?2 AND batch_id=?3 AND user_id=?4 AND cleanup_pending=0
`

type SetSourceLeasePositionParams struct {
	Position    int64
	CanonicalID string
	BatchID     string
	UserID      string
}

func (q *Queries) SetSourceLeasePosition(ctx context.Context, arg SetSourceLeasePositionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setSourceLeasePosition,
		arg.Position,
		arg.CanonicalID,
		arg.BatchID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setSourceLeaseReady = `-- name: SetSourceLeaseReady :execrows
UPDATE clip_source_leases SET state='ready',actual_bytes=?,retention_expires_at=? WHERE canonical_id=? AND batch_id=? AND user_id=? AND state='pending' AND cleanup_pending=0
`

type SetSourceLeaseReadyParams struct {
	ActualBytes        int64
	RetentionExpiresAt sql.NullString
	CanonicalID        string
	BatchID            string
	UserID             string
}

func (q *Queries) SetSourceLeaseReady(ctx context.Context, arg SetSourceLeaseReadyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setSourceLeaseReady,
		arg.ActualBytes,
		arg.RetentionExpiresAt,
		arg.CanonicalID,
		arg.BatchID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setSourceOriginalAudio = `-- name: SetSourceOriginalAudio :execrows
UPDATE clip_source_leases SET retain_original_audio=?1
WHERE canonical_id=?2 AND fingerprint=?3 AND batch_id=?4 AND user_id=?5
  AND state='ready' AND cleanup_pending=0
`

type SetSourceOriginalAudioParams struct {
	RetainOriginalAudio int64
	CanonicalID         string
	Fingerprint         string
	BatchID             string
	UserID              string
}

// SetSourceOriginalAudio is owner-scoped and pins the exact file: a source whose
// fingerprint changed is a different file and keeps its own default.
func (q *Queries) SetSourceOriginalAudio(ctx context.Context, arg SetSourceOriginalAudioParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setSourceOriginalAudio,
		arg.RetainOriginalAudio,
		arg.CanonicalID,
		arg.Fingerprint,
		arg.BatchID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const sourceKeyExists = `-- name: SourceKeyExists :one
SELECT EXISTS(SELECT clip_source_leases.object_key FROM clip_source_leases WHERE clip_source_leases.object_key=?1 UNION ALL SELECT clip_proxy_leases.object_key FROM clip_proxy_leases WHERE clip_proxy_leases.object_key=?1) AS present
`

func (q *Queries) SourceKeyExists(ctx context.Context, key string) (bool, error) {
	row := q.db.QueryRowContext(ctx, sourceKeyExists, key)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const sourceProjectWritable = `-- name: SourceProjectWritable :one
SELECT CASE WHEN finalized_at IS NOT NULL OR deleting=1 OR source_access_revoked_at IS NOT NULL THEN 1 ELSE 0 END AS deleting FROM clip_projects WHERE id = ? AND user_id = ?
`

type SourceProjectWritableParams struct {
	ID     string
	UserID string
}

func (q *Queries) SourceProjectWritable(ctx context.Context, arg SourceProjectWritableParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, sourceProjectWritable, arg.ID, arg.UserID)
	var deleting int64
	err := row.Scan(&deleting)
	return deleting, err
}
