package voice

// prompts is a code-owned catalog. Keys are stable even when scene wording improves.
var prompts = makePromptCatalog()

func makePromptCatalog() []Prompt {
	out := []Prompt{
		{Key: "starter_day_open", Part: PartOpening, Starter: true, Scene: "여유로운 주말 아침이에요. 친구에게 오늘 계획을 이야기하려고 해요.", Text: "어떤 인사로 이야기를 시작할까요? 평소 말투로 1~3문장이면 충분해요.", Hint: "거창한 계획이 아니어도 좋아요. 집에서 쉬는 이야기도 괜찮아요."},
		{Key: "starter_discovery_open", Part: PartOpening, Starter: true, Scene: "산책하다가 작고 조용한 가게를 발견했어요.", Text: "친구에게 이 가게를 소개하는 첫마디를 써 보세요. 평소 말투로 1~3문장이면 충분해요.", Hint: "실제 가게가 아니어도 괜찮아요. 처음 눈길이 간 점부터 말해 주세요."},
		{Key: "starter_snack", Part: PartDescription, Starter: true, Scene: "별 기대 없이 고른 간식이 한입 먹어 보니 생각보다 맛있어요.", Text: "친구에게 그 맛을 어떻게 설명할까요? 평소 말투로 1~3문장이면 충분해요.", Hint: "맛있다는 말에 이유 하나를 더해 보세요."},
		{Key: "starter_rain", Part: PartDescription, Starter: true, Scene: "나가려는데 갑자기 비가 내려요. 다행히 우산은 챙겼어요.", Text: "그 순간의 마음을 친구에게 이야기해 보세요. 평소 말투로 1~3문장이면 충분해요.", Hint: "반가웠는지, 귀찮았는지 편하게 써 주세요."},
		{Key: "starter_recommend", Part: PartDescription, Starter: true, Scene: "친구가 주말에 부담 없이 기분 전환을 하고 싶대요.", Text: "어떤 일을 추천하고 싶나요? 평소 말투로 1~3문장이면 충분해요.", Hint: "산책이나 낮잠처럼 작은 일도 좋아요."},
		{Key: "starter_inconvenience", Part: PartDescription, Starter: true, Scene: "마음에 들어서 산 컵이 막상 써 보니 손잡이가 조금 불편해요.", Text: "아쉬운 점을 어떻게 말할까요? 평소 말투로 1~3문장이면 충분해요.", Hint: "좋았던 점과 불편한 점을 같이 이야기해도 좋아요."},
		{Key: "starter_surprise", Part: PartDescription, Starter: true, Scene: "평소 붐비던 길이 오늘은 한산해서 걸어가기 편해요.", Text: "뜻밖에 편해진 순간을 써 보세요. 평소 말투로 1~3문장이면 충분해요.", Hint: "놀랐던 마음이나 달라진 기분을 써 주세요."},
		{Key: "starter_choice", Part: PartDescription, Starter: true, Scene: "오늘은 새로운 메뉴를 먹을지, 늘 먹던 메뉴를 고를지 고민돼요.", Text: "어느 쪽을 고르고 싶은지 이유를 써 보세요. 평소 말투로 1~3문장이면 충분해요.", Hint: "정답은 없어요. 지금 마음이 가는 쪽이면 돼요."},
		{Key: "starter_day_close", Part: PartClosing, Starter: true, Scene: "작은 산책을 마치고 집으로 돌아왔어요.", Text: "오늘 이야기를 마지막 한마디로 마무리해 보세요. 평소 말투로 1~3문장이면 충분해요.", Hint: "오늘 기분이나 다음에 하고 싶은 일을 말해도 좋아요."},
		{Key: "starter_friend_close", Part: PartClosing, Starter: true, Scene: "친구에게 즐거웠던 하루를 다 이야기했어요.", Text: "친구에게 건넬 끝인사를 써 보세요. 평소 말투로 1~3문장이면 충분해요.", Hint: "평소 메시지에서 쓰는 편한 인사면 충분해요."},
	}
	out = append(out, legacyPrompts...)
	return append(out, additionalPrompts...)
}

// Ordinary imagined situations require no private history, specialist knowledge or upload.
var additionalPrompts = []Prompt{
	{Key: "everyday_food_01", Part: PartDescription, Scene: "따뜻한 국 한 숟갈을 먹으니 몸이 조금 풀려요.", Text: "한입 먹었을 때의 느낌을 친구에게 전해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "맛이나 식감 중 떠오르는 것 하나만 이야기해도 좋아요."},
	{Key: "everyday_food_02", Part: PartDescription, Scene: "갓 구운 빵을 나눠 먹는데 가장자리가 바삭해요.", Text: "한입 먹었을 때의 느낌을 친구에게 전해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "맛이나 식감 중 떠오르는 것 하나만 이야기해도 좋아요."},
	{Key: "everyday_food_03", Part: PartDescription, Scene: "같은 간식을 먹어도 오늘은 유난히 달게 느껴져요.", Text: "한입 먹었을 때의 느낌을 친구에게 전해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "맛이나 식감 중 떠오르는 것 하나만 이야기해도 좋아요."},
	{Key: "everyday_food_04", Part: PartDescription, Scene: "매운 음식을 먹었는데 예상보다 훨씬 매워요.", Text: "한입 먹었을 때의 느낌을 친구에게 전해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "맛이나 식감 중 떠오르는 것 하나만 이야기해도 좋아요."},
	{Key: "everyday_food_05", Part: PartDescription, Scene: "냉장고에 남은 재료로 간단한 한 끼를 만들었어요.", Text: "한입 먹었을 때의 느낌을 친구에게 전해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "맛이나 식감 중 떠오르는 것 하나만 이야기해도 좋아요."},
	{Key: "everyday_food_06", Part: PartDescription, Scene: "점심으로 먹은 음식이 든든해서 오후까지 배가 부르네요.", Text: "한입 먹었을 때의 느낌을 친구에게 전해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "맛이나 식감 중 떠오르는 것 하나만 이야기해도 좋아요."},
	{Key: "everyday_food_07", Part: PartDescription, Scene: "처음 먹어 본 과일이 생각보다 새콤해요.", Text: "한입 먹었을 때의 느낌을 친구에게 전해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "맛이나 식감 중 떠오르는 것 하나만 이야기해도 좋아요."},
	{Key: "everyday_food_08", Part: PartDescription, Scene: "식은 음식도 데워 먹으니 다시 맛있어졌어요.", Text: "한입 먹었을 때의 느낌을 친구에게 전해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "맛이나 식감 중 떠오르는 것 하나만 이야기해도 좋아요."},
	{Key: "everyday_drink_01", Part: PartDescription, Scene: "추운 날 따뜻한 차 한 잔을 손에 쥐었어요.", Text: "지금 마신 음료를 친구에게 소개해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "향이나 온도, 기분을 편하게 말해 주세요."},
	{Key: "everyday_drink_02", Part: PartDescription, Scene: "더운 날 차가운 물을 마시니 갈증이 가셔요.", Text: "지금 마신 음료를 친구에게 소개해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "향이나 온도, 기분을 편하게 말해 주세요."},
	{Key: "everyday_drink_03", Part: PartDescription, Scene: "늘 마시던 음료 대신 다른 맛을 골라 봤어요.", Text: "지금 마신 음료를 친구에게 소개해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "향이나 온도, 기분을 편하게 말해 주세요."},
	{Key: "everyday_drink_04", Part: PartDescription, Scene: "카페에서 받은 음료가 생각보다 진해요.", Text: "지금 마신 음료를 친구에게 소개해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "향이나 온도, 기분을 편하게 말해 주세요."},
	{Key: "everyday_drink_05", Part: PartDescription, Scene: "달지 않을 줄 알았던 음료가 꽤 달아요.", Text: "지금 마신 음료를 친구에게 소개해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "향이나 온도, 기분을 편하게 말해 주세요."},
	{Key: "everyday_drink_06", Part: PartDescription, Scene: "집에서 만든 음료를 얼음 넣어 마셔 봤어요.", Text: "지금 마신 음료를 친구에게 소개해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "향이나 온도, 기분을 편하게 말해 주세요."},
	{Key: "everyday_drink_07", Part: PartDescription, Scene: "창가에 앉아 천천히 따뜻한 음료를 마시고 있어요.", Text: "지금 마신 음료를 친구에게 소개해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "향이나 온도, 기분을 편하게 말해 주세요."},
	{Key: "everyday_drink_08", Part: PartDescription, Scene: "친구가 고른 음료를 한 모금 맛보니 취향이 달라요.", Text: "지금 마신 음료를 친구에게 소개해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "향이나 온도, 기분을 편하게 말해 주세요."},
	{Key: "everyday_commute_01", Part: PartDescription, Scene: "버스를 놓쳤는데 다음 버스가 금방 왔어요.", Text: "길에서 느낀 점을 친구에게 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "불편함이나 작은 즐거움 중 하나만 골라도 좋아요."},
	{Key: "everyday_commute_02", Part: PartDescription, Scene: "지하철에서 운 좋게 자리에 앉았어요.", Text: "길에서 느낀 점을 친구에게 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "불편함이나 작은 즐거움 중 하나만 골라도 좋아요."},
	{Key: "everyday_commute_03", Part: PartDescription, Scene: "늘 가던 길 대신 다른 골목으로 걸어 봤어요.", Text: "길에서 느낀 점을 친구에게 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "불편함이나 작은 즐거움 중 하나만 골라도 좋아요."},
	{Key: "everyday_commute_04", Part: PartDescription, Scene: "이어폰 없이 걸으니 주변 소리가 잘 들려요.", Text: "길에서 느낀 점을 친구에게 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "불편함이나 작은 즐거움 중 하나만 골라도 좋아요."},
	{Key: "everyday_commute_05", Part: PartDescription, Scene: "횡단보도 신호가 바로 바뀌어서 덜 기다렸어요.", Text: "길에서 느낀 점을 친구에게 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "불편함이나 작은 즐거움 중 하나만 골라도 좋아요."},
	{Key: "everyday_commute_06", Part: PartDescription, Scene: "가까운 거리는 걸어 보니 생각보다 빨리 도착했어요.", Text: "길에서 느낀 점을 친구에게 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "불편함이나 작은 즐거움 중 하나만 골라도 좋아요."},
	{Key: "everyday_commute_07", Part: PartDescription, Scene: "길을 잘못 들었지만 예쁜 나무를 발견했어요.", Text: "길에서 느낀 점을 친구에게 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "불편함이나 작은 즐거움 중 하나만 골라도 좋아요."},
	{Key: "everyday_commute_08", Part: PartDescription, Scene: "붐비는 시간대를 피하니 이동이 한결 편해요.", Text: "길에서 느낀 점을 친구에게 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "불편함이나 작은 즐거움 중 하나만 골라도 좋아요."},
	{Key: "everyday_shopping_01", Part: PartDescription, Scene: "필요한 물건을 사러 갔다가 색깔 때문에 고민 중이에요.", Text: "이 물건을 고른 마음을 친구에게 알려 주세요. 1~3문장으로 편하게 써 주세요.", Hint: "써 보기 전 기대나 써 본 느낌도 좋아요."},
	{Key: "everyday_shopping_02", Part: PartDescription, Scene: "세일하는 물건을 봤지만 당장 필요하지는 않아요.", Text: "이 물건을 고른 마음을 친구에게 알려 주세요. 1~3문장으로 편하게 써 주세요.", Hint: "써 보기 전 기대나 써 본 느낌도 좋아요."},
	{Key: "everyday_shopping_03", Part: PartDescription, Scene: "온라인 사진보다 실제 물건의 색이 더 마음에 들어요.", Text: "이 물건을 고른 마음을 친구에게 알려 주세요. 1~3문장으로 편하게 써 주세요.", Hint: "써 보기 전 기대나 써 본 느낌도 좋아요."},
	{Key: "everyday_shopping_04", Part: PartDescription, Scene: "가격은 조금 높지만 오래 쓸 것 같은 물건을 발견했어요.", Text: "이 물건을 고른 마음을 친구에게 알려 주세요. 1~3문장으로 편하게 써 주세요.", Hint: "써 보기 전 기대나 써 본 느낌도 좋아요."},
	{Key: "everyday_shopping_05", Part: PartDescription, Scene: "작은 수납함 하나로 책상이 깔끔해졌어요.", Text: "이 물건을 고른 마음을 친구에게 알려 주세요. 1~3문장으로 편하게 써 주세요.", Hint: "써 보기 전 기대나 써 본 느낌도 좋아요."},
	{Key: "everyday_shopping_06", Part: PartDescription, Scene: "편할 줄 알고 산 신발이 처음엔 조금 뻣뻣해요.", Text: "이 물건을 고른 마음을 친구에게 알려 주세요. 1~3문장으로 편하게 써 주세요.", Hint: "써 보기 전 기대나 써 본 느낌도 좋아요."},
	{Key: "everyday_shopping_07", Part: PartDescription, Scene: "장바구니에 담아 뒀던 물건을 다시 보니 마음이 바뀌어요.", Text: "이 물건을 고른 마음을 친구에게 알려 주세요. 1~3문장으로 편하게 써 주세요.", Hint: "써 보기 전 기대나 써 본 느낌도 좋아요."},
	{Key: "everyday_shopping_08", Part: PartDescription, Scene: "포장이 단순해서 물건을 꺼내기 편했어요.", Text: "이 물건을 고른 마음을 친구에게 알려 주세요. 1~3문장으로 편하게 써 주세요.", Hint: "써 보기 전 기대나 써 본 느낌도 좋아요."},
	{Key: "everyday_gift_01", Part: PartDescription, Scene: "친구에게 간식 하나를 가볍게 건네려 해요.", Text: "상대에게 어떤 말을 건네고 싶은지 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "비싼 선물이나 특별한 날을 떠올릴 필요는 없어요."},
	{Key: "everyday_gift_02", Part: PartDescription, Scene: "작은 쪽지를 선물에 함께 넣고 싶어요.", Text: "상대에게 어떤 말을 건네고 싶은지 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "비싼 선물이나 특별한 날을 떠올릴 필요는 없어요."},
	{Key: "everyday_gift_03", Part: PartDescription, Scene: "친구가 좋아하는 색의 물건을 우연히 발견했어요.", Text: "상대에게 어떤 말을 건네고 싶은지 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "비싼 선물이나 특별한 날을 떠올릴 필요는 없어요."},
	{Key: "everyday_gift_04", Part: PartDescription, Scene: "뜻밖에 작은 선물을 받아서 기분이 좋아요.", Text: "상대에게 어떤 말을 건네고 싶은지 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "비싼 선물이나 특별한 날을 떠올릴 필요는 없어요."},
	{Key: "everyday_gift_05", Part: PartDescription, Scene: "선물을 고르다가 내 취향과 친구 취향이 다르다는 걸 느껴요.", Text: "상대에게 어떤 말을 건네고 싶은지 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "비싼 선물이나 특별한 날을 떠올릴 필요는 없어요."},
	{Key: "everyday_gift_06", Part: PartDescription, Scene: "친구가 준 물건을 잘 쓰고 있다는 말을 전하려 해요.", Text: "상대에게 어떤 말을 건네고 싶은지 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "비싼 선물이나 특별한 날을 떠올릴 필요는 없어요."},
	{Key: "everyday_gift_07", Part: PartDescription, Scene: "직접 만든 작은 것을 누군가에게 보여주고 싶어요.", Text: "상대에게 어떤 말을 건네고 싶은지 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "비싼 선물이나 특별한 날을 떠올릴 필요는 없어요."},
	{Key: "everyday_gift_08", Part: PartDescription, Scene: "친구가 선물은 필요 없다며 같이 시간을 보내자고 해요.", Text: "상대에게 어떤 말을 건네고 싶은지 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "비싼 선물이나 특별한 날을 떠올릴 필요는 없어요."},
	{Key: "everyday_home_01", Part: PartDescription, Scene: "창문을 열었더니 시원한 바람이 들어와요.", Text: "집에서 생긴 작은 변화를 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "집이 크거나 특별할 필요는 없어요."},
	{Key: "everyday_home_02", Part: PartDescription, Scene: "밀린 빨래를 끝내니 마음이 조금 가벼워졌어요.", Text: "집에서 생긴 작은 변화를 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "집이 크거나 특별할 필요는 없어요."},
	{Key: "everyday_home_03", Part: PartDescription, Scene: "가구를 조금 옮겼더니 방 분위기가 달라졌어요.", Text: "집에서 생긴 작은 변화를 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "집이 크거나 특별할 필요는 없어요."},
	{Key: "everyday_home_04", Part: PartDescription, Scene: "책상 위 물건을 정리하다 잊고 있던 메모를 찾았어요.", Text: "집에서 생긴 작은 변화를 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "집이 크거나 특별할 필요는 없어요."},
	{Key: "everyday_home_05", Part: PartDescription, Scene: "불을 조금 낮추니 저녁이 더 편안하게 느껴져요.", Text: "집에서 생긴 작은 변화를 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "집이 크거나 특별할 필요는 없어요."},
	{Key: "everyday_home_06", Part: PartDescription, Scene: "새로 꺼낸 이불이 보송해서 기분이 좋아요.", Text: "집에서 생긴 작은 변화를 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "집이 크거나 특별할 필요는 없어요."},
	{Key: "everyday_home_07", Part: PartDescription, Scene: "청소를 시작하기 전에는 귀찮았는데 끝내니 뿌듯해요.", Text: "집에서 생긴 작은 변화를 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "집이 크거나 특별할 필요는 없어요."},
	{Key: "everyday_home_08", Part: PartDescription, Scene: "집 안에 둔 작은 화분에서 새잎이 나왔어요.", Text: "집에서 생긴 작은 변화를 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "집이 크거나 특별할 필요는 없어요."},
	{Key: "everyday_weekend_01", Part: PartDescription, Scene: "주말에 알람 없이 조금 늦게 일어났어요.", Text: "이 시간을 어떻게 보내고 싶은지 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "계획 없이 쉬는 것도 좋은 답이에요."},
	{Key: "everyday_weekend_02", Part: PartDescription, Scene: "오늘은 약속이 없어서 천천히 아침을 먹어요.", Text: "이 시간을 어떻게 보내고 싶은지 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "계획 없이 쉬는 것도 좋은 답이에요."},
	{Key: "everyday_weekend_03", Part: PartDescription, Scene: "잠깐 나갔다 오려다가 집이 더 편하게 느껴져요.", Text: "이 시간을 어떻게 보내고 싶은지 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "계획 없이 쉬는 것도 좋은 답이에요."},
	{Key: "everyday_weekend_04", Part: PartDescription, Scene: "평소 미뤄 둔 작은 일을 주말에 하나 끝냈어요.", Text: "이 시간을 어떻게 보내고 싶은지 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "계획 없이 쉬는 것도 좋은 답이에요."},
	{Key: "everyday_weekend_05", Part: PartDescription, Scene: "산책을 하려는데 친구가 같이 걷자고 연락했어요.", Text: "이 시간을 어떻게 보내고 싶은지 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "계획 없이 쉬는 것도 좋은 답이에요."},
	{Key: "everyday_weekend_06", Part: PartDescription, Scene: "낮잠을 짧게 자려고 했는데 생각보다 오래 잤어요.", Text: "이 시간을 어떻게 보내고 싶은지 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "계획 없이 쉬는 것도 좋은 답이에요."},
	{Key: "everyday_weekend_07", Part: PartDescription, Scene: "동네만 가볍게 둘러봤는데 기분이 좋아졌어요.", Text: "이 시간을 어떻게 보내고 싶은지 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "계획 없이 쉬는 것도 좋은 답이에요."},
	{Key: "everyday_weekend_08", Part: PartDescription, Scene: "다음 주를 위해 조금 준비할지 더 쉴지 고민돼요.", Text: "이 시간을 어떻게 보내고 싶은지 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "계획 없이 쉬는 것도 좋은 답이에요."},
	{Key: "everyday_weather_01", Part: PartDescription, Scene: "아침에 햇빛이 밝아서 커튼을 활짝 열었어요.", Text: "날씨가 바꾼 기분을 친구에게 전해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "풍경을 길게 묘사하지 않아도 괜찮아요."},
	{Key: "everyday_weather_02", Part: PartDescription, Scene: "갑자기 바람이 차가워져 겉옷을 챙겼어요.", Text: "날씨가 바꾼 기분을 친구에게 전해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "풍경을 길게 묘사하지 않아도 괜찮아요."},
	{Key: "everyday_weather_03", Part: PartDescription, Scene: "비가 그친 뒤 공기가 맑게 느껴져요.", Text: "날씨가 바꾼 기분을 친구에게 전해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "풍경을 길게 묘사하지 않아도 괜찮아요."},
	{Key: "everyday_weather_04", Part: PartDescription, Scene: "눈이 조금 내려서 평소 길이 새롭게 보여요.", Text: "날씨가 바꾼 기분을 친구에게 전해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "풍경을 길게 묘사하지 않아도 괜찮아요."},
	{Key: "everyday_weather_05", Part: PartDescription, Scene: "더운 오후에 그늘을 찾으니 한결 시원해요.", Text: "날씨가 바꾼 기분을 친구에게 전해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "풍경을 길게 묘사하지 않아도 괜찮아요."},
	{Key: "everyday_weather_06", Part: PartDescription, Scene: "흐린 날이라 괜히 느긋하게 쉬고 싶어요.", Text: "날씨가 바꾼 기분을 친구에게 전해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "풍경을 길게 묘사하지 않아도 괜찮아요."},
	{Key: "everyday_weather_07", Part: PartDescription, Scene: "저녁 바람이 선선해서 조금 더 걷고 싶어요.", Text: "날씨가 바꾼 기분을 친구에게 전해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "풍경을 길게 묘사하지 않아도 괜찮아요."},
	{Key: "everyday_weather_08", Part: PartDescription, Scene: "날씨가 좋아서 예정에 없던 산책을 하려 해요.", Text: "날씨가 바꾼 기분을 친구에게 전해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "풍경을 길게 묘사하지 않아도 괜찮아요."},
	{Key: "everyday_plans_01", Part: PartDescription, Scene: "하려던 일이 일찍 끝나서 시간이 조금 남았어요.", Text: "계획을 정하면서 든 생각을 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "작은 선택의 이유면 충분해요."},
	{Key: "everyday_plans_02", Part: PartDescription, Scene: "내일 해야 할 일을 세 가지 적어 봤어요.", Text: "계획을 정하면서 든 생각을 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "작은 선택의 이유면 충분해요."},
	{Key: "everyday_plans_03", Part: PartDescription, Scene: "한 번에 다 하려니 부담돼서 하나만 먼저 하기로 했어요.", Text: "계획을 정하면서 든 생각을 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "작은 선택의 이유면 충분해요."},
	{Key: "everyday_plans_04", Part: PartDescription, Scene: "약속 시간을 조금 늦추자는 연락을 받았어요.", Text: "계획을 정하면서 든 생각을 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "작은 선택의 이유면 충분해요."},
	{Key: "everyday_plans_05", Part: PartDescription, Scene: "밖에서 만나려던 계획을 비 때문에 실내로 바꿨어요.", Text: "계획을 정하면서 든 생각을 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "작은 선택의 이유면 충분해요."},
	{Key: "everyday_plans_06", Part: PartDescription, Scene: "오늘 계획에서 가장 하기 싫은 일을 먼저 끝냈어요.", Text: "계획을 정하면서 든 생각을 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "작은 선택의 이유면 충분해요."},
	{Key: "everyday_plans_07", Part: PartDescription, Scene: "어디에 갈지 정하지 않고 걷기로 했어요.", Text: "계획을 정하면서 든 생각을 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "작은 선택의 이유면 충분해요."},
	{Key: "everyday_plans_08", Part: PartDescription, Scene: "계획을 너무 꽉 채운 것 같아 하나를 빼려 해요.", Text: "계획을 정하면서 든 생각을 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "작은 선택의 이유면 충분해요."},
	{Key: "everyday_friends_01", Part: PartDescription, Scene: "친구가 새로운 취미를 시작했다며 이야기해 줬어요.", Text: "친구에게 건넬 말을 평소처럼 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "격식을 차리지 않아도 괜찮아요."},
	{Key: "everyday_friends_02", Part: PartDescription, Scene: "친구가 별일 아닌 실수를 해서 속상해해요.", Text: "친구에게 건넬 말을 평소처럼 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "격식을 차리지 않아도 괜찮아요."},
	{Key: "everyday_friends_03", Part: PartDescription, Scene: "친구와 같은 일을 두고 다른 생각을 하고 있어요.", Text: "친구에게 건넬 말을 평소처럼 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "격식을 차리지 않아도 괜찮아요."},
	{Key: "everyday_friends_04", Part: PartDescription, Scene: "친구가 바쁜 하루를 보냈다며 지쳤다고 해요.", Text: "친구에게 건넬 말을 평소처럼 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "격식을 차리지 않아도 괜찮아요."},
	{Key: "everyday_friends_05", Part: PartDescription, Scene: "친구가 맛있는 간식을 발견했다며 추천해 줬어요.", Text: "친구에게 건넬 말을 평소처럼 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "격식을 차리지 않아도 괜찮아요."},
	{Key: "everyday_friends_06", Part: PartDescription, Scene: "친구가 약속에 조금 늦는다고 먼저 연락했어요.", Text: "친구에게 건넬 말을 평소처럼 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "격식을 차리지 않아도 괜찮아요."},
	{Key: "everyday_friends_07", Part: PartDescription, Scene: "친구와 오랜만에 짧은 메시지를 주고받았어요.", Text: "친구에게 건넬 말을 평소처럼 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "격식을 차리지 않아도 괜찮아요."},
	{Key: "everyday_friends_08", Part: PartDescription, Scene: "친구가 작은 목표를 이뤘다며 기뻐해요.", Text: "친구에게 건넬 말을 평소처럼 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "격식을 차리지 않아도 괜찮아요."},
	{Key: "everyday_surprises_01", Part: PartDescription, Scene: "일기예보와 달리 산책하는 동안 비가 오지 않았어요.", Text: "뜻밖의 순간에 든 마음을 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "좋거나 아쉬운 감정을 자연스럽게 말해 주세요."},
	{Key: "everyday_surprises_02", Part: PartDescription, Scene: "잃어버린 줄 알았던 물건이 가방 안에 있었어요.", Text: "뜻밖의 순간에 든 마음을 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "좋거나 아쉬운 감정을 자연스럽게 말해 주세요."},
	{Key: "everyday_surprises_03", Part: PartDescription, Scene: "별 기대 없이 본 영상이 웃겨서 계속 웃었어요.", Text: "뜻밖의 순간에 든 마음을 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "좋거나 아쉬운 감정을 자연스럽게 말해 주세요."},
	{Key: "everyday_surprises_04", Part: PartDescription, Scene: "집에 오는 길에 마음에 드는 노래를 들었어요.", Text: "뜻밖의 순간에 든 마음을 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "좋거나 아쉬운 감정을 자연스럽게 말해 주세요."},
	{Key: "everyday_surprises_05", Part: PartDescription, Scene: "자주 보던 가게가 새로 단장했어요.", Text: "뜻밖의 순간에 든 마음을 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "좋거나 아쉬운 감정을 자연스럽게 말해 주세요."},
	{Key: "everyday_surprises_06", Part: PartDescription, Scene: "평소 조용하던 골목에 사람들이 모여 있어요.", Text: "뜻밖의 순간에 든 마음을 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "좋거나 아쉬운 감정을 자연스럽게 말해 주세요."},
	{Key: "everyday_surprises_07", Part: PartDescription, Scene: "주문한 물건이 예상보다 하루 일찍 도착했어요.", Text: "뜻밖의 순간에 든 마음을 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "좋거나 아쉬운 감정을 자연스럽게 말해 주세요."},
	{Key: "everyday_surprises_08", Part: PartDescription, Scene: "어렵게 느껴지던 일이 해 보니 생각보다 간단했어요.", Text: "뜻밖의 순간에 든 마음을 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "좋거나 아쉬운 감정을 자연스럽게 말해 주세요."},
	{Key: "everyday_waiting_01", Part: PartDescription, Scene: "주문한 음식이 평소보다 조금 늦게 나와요.", Text: "기다리는 동안의 마음을 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "화가 나지 않았다면 그 이유를 써도 좋아요."},
	{Key: "everyday_waiting_02", Part: PartDescription, Scene: "엘리베이터를 기다리다 계단을 이용하기로 했어요.", Text: "기다리는 동안의 마음을 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "화가 나지 않았다면 그 이유를 써도 좋아요."},
	{Key: "everyday_waiting_03", Part: PartDescription, Scene: "버스 도착 시간이 몇 분씩 밀리고 있어요.", Text: "기다리는 동안의 마음을 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "화가 나지 않았다면 그 이유를 써도 좋아요."},
	{Key: "everyday_waiting_04", Part: PartDescription, Scene: "친구를 기다리는 동안 근처를 구경했어요.", Text: "기다리는 동안의 마음을 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "화가 나지 않았다면 그 이유를 써도 좋아요."},
	{Key: "everyday_waiting_05", Part: PartDescription, Scene: "온라인 주문의 배송 알림이 늦게 왔어요.", Text: "기다리는 동안의 마음을 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "화가 나지 않았다면 그 이유를 써도 좋아요."},
	{Key: "everyday_waiting_06", Part: PartDescription, Scene: "가게 앞에 줄이 길어서 다른 곳에 가려 해요.", Text: "기다리는 동안의 마음을 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "화가 나지 않았다면 그 이유를 써도 좋아요."},
	{Key: "everyday_waiting_07", Part: PartDescription, Scene: "예약 시간보다 일찍 도착해서 잠깐 쉬고 있어요.", Text: "기다리는 동안의 마음을 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "화가 나지 않았다면 그 이유를 써도 좋아요."},
	{Key: "everyday_waiting_08", Part: PartDescription, Scene: "급하지 않은 날이라 기다림이 크게 불편하지 않아요.", Text: "기다리는 동안의 마음을 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "화가 나지 않았다면 그 이유를 써도 좋아요."},
	{Key: "everyday_choices_01", Part: PartDescription, Scene: "가까운 곳에서 편하게 쉴지 조금 멀리 나갈지 고민돼요.", Text: "무엇을 선택하고 싶은지 이유를 알려 주세요. 1~3문장으로 편하게 써 주세요.", Hint: "선택에는 정답이 없어요."},
	{Key: "everyday_choices_02", Part: PartDescription, Scene: "간단한 간식과 든든한 식사 사이에서 고민 중이에요.", Text: "무엇을 선택하고 싶은지 이유를 알려 주세요. 1~3문장으로 편하게 써 주세요.", Hint: "선택에는 정답이 없어요."},
	{Key: "everyday_choices_03", Part: PartDescription, Scene: "오늘은 조용한 음악과 신나는 음악 중 하나를 듣고 싶어요.", Text: "무엇을 선택하고 싶은지 이유를 알려 주세요. 1~3문장으로 편하게 써 주세요.", Hint: "선택에는 정답이 없어요."},
	{Key: "everyday_choices_04", Part: PartDescription, Scene: "물건을 바로 살지 며칠 더 생각할지 고민돼요.", Text: "무엇을 선택하고 싶은지 이유를 알려 주세요. 1~3문장으로 편하게 써 주세요.", Hint: "선택에는 정답이 없어요."},
	{Key: "everyday_choices_05", Part: PartDescription, Scene: "친구를 만나거나 혼자 시간을 보내는 둘 다 좋아 보여요.", Text: "무엇을 선택하고 싶은지 이유를 알려 주세요. 1~3문장으로 편하게 써 주세요.", Hint: "선택에는 정답이 없어요."},
	{Key: "everyday_choices_06", Part: PartDescription, Scene: "편한 옷과 조금 차려입는 옷 사이에서 고민돼요.", Text: "무엇을 선택하고 싶은지 이유를 알려 주세요. 1~3문장으로 편하게 써 주세요.", Hint: "선택에는 정답이 없어요."},
	{Key: "everyday_choices_07", Part: PartDescription, Scene: "새로운 길로 가거나 익숙한 길로 돌아갈 수 있어요.", Text: "무엇을 선택하고 싶은지 이유를 알려 주세요. 1~3문장으로 편하게 써 주세요.", Hint: "선택에는 정답이 없어요."},
	{Key: "everyday_choices_08", Part: PartDescription, Scene: "사진을 찍을지 그냥 풍경을 보고 있을지 고민돼요.", Text: "무엇을 선택하고 싶은지 이유를 알려 주세요. 1~3문장으로 편하게 써 주세요.", Hint: "선택에는 정답이 없어요."},
	{Key: "everyday_comfort_01", Part: PartDescription, Scene: "해야 할 일을 끝내고 따뜻한 음료를 마셔요.", Text: "마음이 편해진 이유를 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "대단한 일이 없어도 괜찮아요."},
	{Key: "everyday_comfort_02", Part: PartDescription, Scene: "친구가 괜찮다는 한마디를 건네 줬어요.", Text: "마음이 편해진 이유를 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "대단한 일이 없어도 괜찮아요."},
	{Key: "everyday_comfort_03", Part: PartDescription, Scene: "잠깐 눈을 감고 쉬었더니 머리가 맑아져요.", Text: "마음이 편해진 이유를 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "대단한 일이 없어도 괜찮아요."},
	{Key: "everyday_comfort_04", Part: PartDescription, Scene: "마음에 드는 노래를 천천히 다시 듣고 있어요.", Text: "마음이 편해진 이유를 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "대단한 일이 없어도 괜찮아요."},
	{Key: "everyday_comfort_05", Part: PartDescription, Scene: "비가 오는 소리를 들으며 집에서 쉬고 있어요.", Text: "마음이 편해진 이유를 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "대단한 일이 없어도 괜찮아요."},
	{Key: "everyday_comfort_06", Part: PartDescription, Scene: "정리된 책상을 보니 다시 시작할 힘이 나요.", Text: "마음이 편해진 이유를 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "대단한 일이 없어도 괜찮아요."},
	{Key: "everyday_comfort_07", Part: PartDescription, Scene: "천천히 걷다 보니 복잡했던 생각이 줄었어요.", Text: "마음이 편해진 이유를 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "대단한 일이 없어도 괜찮아요."},
	{Key: "everyday_comfort_08", Part: PartDescription, Scene: "별말 없이 함께 있어 주는 친구가 고마워요.", Text: "마음이 편해진 이유를 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "대단한 일이 없어도 괜찮아요."},
	{Key: "everyday_everyday_app_01", Part: PartDescription, Scene: "메모를 휴대폰에 적어 두니 잊지 않아서 편해요.", Text: "이 기능을 써 본 느낌을 쉽게 설명해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "앱 이름이나 기술 용어를 몰라도 괜찮아요."},
	{Key: "everyday_everyday_app_02", Part: PartDescription, Scene: "앱 알림이 너무 자주 와서 몇 개를 껐어요.", Text: "이 기능을 써 본 느낌을 쉽게 설명해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "앱 이름이나 기술 용어를 몰라도 괜찮아요."},
	{Key: "everyday_everyday_app_03", Part: PartDescription, Scene: "글자가 작아서 화면을 조금 확대했어요.", Text: "이 기능을 써 본 느낌을 쉽게 설명해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "앱 이름이나 기술 용어를 몰라도 괜찮아요."},
	{Key: "everyday_everyday_app_04", Part: PartDescription, Scene: "검색하던 정보를 생각보다 쉽게 찾았어요.", Text: "이 기능을 써 본 느낌을 쉽게 설명해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "앱 이름이나 기술 용어를 몰라도 괜찮아요."},
	{Key: "everyday_everyday_app_05", Part: PartDescription, Scene: "평소 쓰던 버튼 위치가 바뀌어 잠깐 헤맸어요.", Text: "이 기능을 써 본 느낌을 쉽게 설명해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "앱 이름이나 기술 용어를 몰라도 괜찮아요."},
	{Key: "everyday_everyday_app_06", Part: PartDescription, Scene: "사진을 한 폴더에 모으니 찾기가 쉬워졌어요.", Text: "이 기능을 써 본 느낌을 쉽게 설명해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "앱 이름이나 기술 용어를 몰라도 괜찮아요."},
	{Key: "everyday_everyday_app_07", Part: PartDescription, Scene: "앱에서 하던 일이 저장돼 있어서 안심했어요.", Text: "이 기능을 써 본 느낌을 쉽게 설명해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "앱 이름이나 기술 용어를 몰라도 괜찮아요."},
	{Key: "everyday_everyday_app_08", Part: PartDescription, Scene: "설정이 많아서 필요한 것만 먼저 골랐어요.", Text: "이 기능을 써 본 느낌을 쉽게 설명해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "앱 이름이나 기술 용어를 몰라도 괜찮아요."},
	{Key: "everyday_stories_01", Part: PartDescription, Scene: "짧은 이야기를 읽었는데 마지막 문장이 오래 남아요.", Text: "짧은 이야기를 본 느낌을 친구에게 전해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "작품 제목이나 줄거리를 정확히 쓸 필요는 없어요."},
	{Key: "everyday_stories_02", Part: PartDescription, Scene: "재미있는 장면을 보고 친구에게 보여주고 싶어요.", Text: "짧은 이야기를 본 느낌을 친구에게 전해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "작품 제목이나 줄거리를 정확히 쓸 필요는 없어요."},
	{Key: "everyday_stories_03", Part: PartDescription, Scene: "예상하던 결말과 달라서 조금 놀랐어요.", Text: "짧은 이야기를 본 느낌을 친구에게 전해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "작품 제목이나 줄거리를 정확히 쓸 필요는 없어요."},
	{Key: "everyday_stories_04", Part: PartDescription, Scene: "쉬려고 영상을 봤는데 생각할 거리가 생겼어요.", Text: "짧은 이야기를 본 느낌을 친구에게 전해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "작품 제목이나 줄거리를 정확히 쓸 필요는 없어요."},
	{Key: "everyday_stories_05", Part: PartDescription, Scene: "짧은 글 하나가 오늘 기분과 잘 맞아요.", Text: "짧은 이야기를 본 느낌을 친구에게 전해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "작품 제목이나 줄거리를 정확히 쓸 필요는 없어요."},
	{Key: "everyday_stories_06", Part: PartDescription, Scene: "다시 본 장면이 처음 볼 때와 다르게 느껴져요.", Text: "짧은 이야기를 본 느낌을 친구에게 전해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "작품 제목이나 줄거리를 정확히 쓸 필요는 없어요."},
	{Key: "everyday_stories_07", Part: PartDescription, Scene: "내용은 좋지만 설명이 길어서 조금 지루해요.", Text: "짧은 이야기를 본 느낌을 친구에게 전해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "작품 제목이나 줄거리를 정확히 쓸 필요는 없어요."},
	{Key: "everyday_stories_08", Part: PartDescription, Scene: "가볍게 보기 시작했는데 끝까지 보고 싶어졌어요.", Text: "짧은 이야기를 본 느낌을 친구에게 전해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "작품 제목이나 줄거리를 정확히 쓸 필요는 없어요."},
	{Key: "everyday_photos_01", Part: PartDescription, Scene: "노을 색이 예뻐서 휴대폰으로 한 장 찍었어요.", Text: "사진을 찍거나 본 마음을 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "사진을 올릴 필요 없이 상황만 상상하면 돼요."},
	{Key: "everyday_photos_02", Part: PartDescription, Scene: "사진보다 실제 풍경이 훨씬 멋지게 느껴져요.", Text: "사진을 찍거나 본 마음을 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "사진을 올릴 필요 없이 상황만 상상하면 돼요."},
	{Key: "everyday_photos_03", Part: PartDescription, Scene: "초점이 조금 흐렸지만 마음에 드는 사진이에요.", Text: "사진을 찍거나 본 마음을 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "사진을 올릴 필요 없이 상황만 상상하면 돼요."},
	{Key: "everyday_photos_04", Part: PartDescription, Scene: "친구가 찍어 준 사진이 자연스러워서 좋아요.", Text: "사진을 찍거나 본 마음을 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "사진을 올릴 필요 없이 상황만 상상하면 돼요."},
	{Key: "everyday_photos_05", Part: PartDescription, Scene: "같은 장소를 다른 각도로 찍으니 느낌이 달라요.", Text: "사진을 찍거나 본 마음을 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "사진을 올릴 필요 없이 상황만 상상하면 돼요."},
	{Key: "everyday_photos_06", Part: PartDescription, Scene: "예전 사진을 보다가 그날의 기분이 떠올랐어요.", Text: "사진을 찍거나 본 마음을 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "사진을 올릴 필요 없이 상황만 상상하면 돼요."},
	{Key: "everyday_photos_07", Part: PartDescription, Scene: "음식을 찍으려다가 따뜻할 때 먹기로 했어요.", Text: "사진을 찍거나 본 마음을 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "사진을 올릴 필요 없이 상황만 상상하면 돼요."},
	{Key: "everyday_photos_08", Part: PartDescription, Scene: "잘 찍으려 애쓰지 않은 사진이 더 편하게 보여요.", Text: "사진을 찍거나 본 마음을 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "사진을 올릴 필요 없이 상황만 상상하면 돼요."},
	{Key: "everyday_small_tasks_01", Part: PartDescription, Scene: "미뤄 둔 메일 한 통을 보내고 나니 속이 시원해요.", Text: "작은 일을 해낸 기분을 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "성공한 부분이나 아쉬운 부분 모두 좋아요."},
	{Key: "everyday_small_tasks_02", Part: PartDescription, Scene: "정리할 물건을 조금씩 나누니 덜 부담스러워요.", Text: "작은 일을 해낸 기분을 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "성공한 부분이나 아쉬운 부분 모두 좋아요."},
	{Key: "everyday_small_tasks_03", Part: PartDescription, Scene: "간단한 할 일을 적고 하나씩 지워 봤어요.", Text: "작은 일을 해낸 기분을 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "성공한 부분이나 아쉬운 부분 모두 좋아요."},
	{Key: "everyday_small_tasks_04", Part: PartDescription, Scene: "처음 해 보는 일을 설명을 보며 천천히 마쳤어요.", Text: "작은 일을 해낸 기분을 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "성공한 부분이나 아쉬운 부분 모두 좋아요."},
	{Key: "everyday_small_tasks_05", Part: PartDescription, Scene: "막히던 부분을 친구에게 물어보니 바로 해결됐어요.", Text: "작은 일을 해낸 기분을 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "성공한 부분이나 아쉬운 부분 모두 좋아요."},
	{Key: "everyday_small_tasks_06", Part: PartDescription, Scene: "완벽하게 하려다 시간이 오래 걸려 잠깐 멈췄어요.", Text: "작은 일을 해낸 기분을 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "성공한 부분이나 아쉬운 부분 모두 좋아요."},
	{Key: "everyday_small_tasks_07", Part: PartDescription, Scene: "오늘은 한 가지 일을 끝낸 것만으로 만족하려 해요.", Text: "작은 일을 해낸 기분을 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "성공한 부분이나 아쉬운 부분 모두 좋아요."},
	{Key: "everyday_small_tasks_08", Part: PartDescription, Scene: "내일의 나를 위해 필요한 물건을 미리 챙겼어요.", Text: "작은 일을 해낸 기분을 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "성공한 부분이나 아쉬운 부분 모두 좋아요."},
	{Key: "everyday_neighborhood_01", Part: PartDescription, Scene: "집 근처에 앉아서 쉴 벤치가 하나 있어요.", Text: "동네에서 발견한 점을 친구에게 소개해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "실제 장소 이름을 쓸 필요는 없어요."},
	{Key: "everyday_neighborhood_02", Part: PartDescription, Scene: "늘 지나던 골목에서 작은 꽃을 발견했어요.", Text: "동네에서 발견한 점을 친구에게 소개해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "실제 장소 이름을 쓸 필요는 없어요."},
	{Key: "everyday_neighborhood_03", Part: PartDescription, Scene: "새로 생긴 가게 앞을 지나며 한번 들어가 보고 싶어요.", Text: "동네에서 발견한 점을 친구에게 소개해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "실제 장소 이름을 쓸 필요는 없어요."},
	{Key: "everyday_neighborhood_04", Part: PartDescription, Scene: "가까운 공원이 생각보다 조용해요.", Text: "동네에서 발견한 점을 친구에게 소개해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "실제 장소 이름을 쓸 필요는 없어요."},
	{Key: "everyday_neighborhood_05", Part: PartDescription, Scene: "동네 길에 그늘이 많아서 걷기 편해요.", Text: "동네에서 발견한 점을 친구에게 소개해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "실제 장소 이름을 쓸 필요는 없어요."},
	{Key: "everyday_neighborhood_06", Part: PartDescription, Scene: "평소 문이 닫혀 있던 가게가 오늘은 열려 있어요.", Text: "동네에서 발견한 점을 친구에게 소개해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "실제 장소 이름을 쓸 필요는 없어요."},
	{Key: "everyday_neighborhood_07", Part: PartDescription, Scene: "집 근처에 늦게까지 하는 가게가 있어 든든해요.", Text: "동네에서 발견한 점을 친구에게 소개해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "실제 장소 이름을 쓸 필요는 없어요."},
	{Key: "everyday_neighborhood_08", Part: PartDescription, Scene: "동네에서 편하게 걸을 수 있는 길을 하나 찾았어요.", Text: "동네에서 발견한 점을 친구에게 소개해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "실제 장소 이름을 쓸 필요는 없어요."},
	{Key: "everyday_feelings_01", Part: PartDescription, Scene: "작은 일에도 웃음이 나는 날이에요.", Text: "지금의 감정을 편하게 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "감정 이름을 정확히 붙이지 않아도 괜찮아요."},
	{Key: "everyday_feelings_02", Part: PartDescription, Scene: "이유는 모르겠지만 오늘은 조금 느긋해요.", Text: "지금의 감정을 편하게 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "감정 이름을 정확히 붙이지 않아도 괜찮아요."},
	{Key: "everyday_feelings_03", Part: PartDescription, Scene: "기대했던 일이 취소돼서 아쉬워요.", Text: "지금의 감정을 편하게 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "감정 이름을 정확히 붙이지 않아도 괜찮아요."},
	{Key: "everyday_feelings_04", Part: PartDescription, Scene: "처음 해 보는 일을 앞두고 조금 긴장돼요.", Text: "지금의 감정을 편하게 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "감정 이름을 정확히 붙이지 않아도 괜찮아요."},
	{Key: "everyday_feelings_05", Part: PartDescription, Scene: "친구의 반가운 연락을 받고 기분이 좋아졌어요.", Text: "지금의 감정을 편하게 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "감정 이름을 정확히 붙이지 않아도 괜찮아요."},
	{Key: "everyday_feelings_06", Part: PartDescription, Scene: "할 일이 많아서 머릿속이 조금 복잡해요.", Text: "지금의 감정을 편하게 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "감정 이름을 정확히 붙이지 않아도 괜찮아요."},
	{Key: "everyday_feelings_07", Part: PartDescription, Scene: "일이 잘 풀려서 누구에게든 이야기하고 싶어요.", Text: "지금의 감정을 편하게 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "감정 이름을 정확히 붙이지 않아도 괜찮아요."},
	{Key: "everyday_feelings_08", Part: PartDescription, Scene: "혼자 조용히 있고 싶은 저녁이에요.", Text: "지금의 감정을 편하게 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "감정 이름을 정확히 붙이지 않아도 괜찮아요."},
	{Key: "everyday_memories_01", Part: PartDescription, Scene: "어떤 냄새를 맡으니 예전에 먹던 간식이 떠올라요.", Text: "떠오른 순간을 친구에게 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "실제 기억이 없다면 주어진 상황만 상상해도 좋아요."},
	{Key: "everyday_memories_02", Part: PartDescription, Scene: "익숙한 음악을 듣고 한동안 안 만난 친구가 생각나요.", Text: "떠오른 순간을 친구에게 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "실제 기억이 없다면 주어진 상황만 상상해도 좋아요."},
	{Key: "everyday_memories_03", Part: PartDescription, Scene: "오래된 메모를 보니 그때의 관심사가 새로워 보여요.", Text: "떠오른 순간을 친구에게 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "실제 기억이 없다면 주어진 상황만 상상해도 좋아요."},
	{Key: "everyday_memories_04", Part: PartDescription, Scene: "예전 사진 속 물건을 지금도 잘 쓰고 있어요.", Text: "떠오른 순간을 친구에게 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "실제 기억이 없다면 주어진 상황만 상상해도 좋아요."},
	{Key: "everyday_memories_05", Part: PartDescription, Scene: "전에 걷던 길을 다시 지나니 반가워요.", Text: "떠오른 순간을 친구에게 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "실제 기억이 없다면 주어진 상황만 상상해도 좋아요."},
	{Key: "everyday_memories_06", Part: PartDescription, Scene: "처음엔 낯설던 장소가 이제는 익숙하게 느껴져요.", Text: "떠오른 순간을 친구에게 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "실제 기억이 없다면 주어진 상황만 상상해도 좋아요."},
	{Key: "everyday_memories_07", Part: PartDescription, Scene: "친구와 나눴던 사소한 농담이 문득 떠올랐어요.", Text: "떠오른 순간을 친구에게 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "실제 기억이 없다면 주어진 상황만 상상해도 좋아요."},
	{Key: "everyday_memories_08", Part: PartDescription, Scene: "한때 좋아하던 음식을 오랜만에 다시 먹었어요.", Text: "떠오른 순간을 친구에게 이야기해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "실제 기억이 없다면 주어진 상황만 상상해도 좋아요."},
	{Key: "everyday_recommendations_01", Part: PartDescription, Scene: "친구가 너무 오래 앉아 있어서 잠깐 걷자고 하려 해요.", Text: "친구에게 가볍게 제안하는 말을 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "꼭 알아야 하는 정보나 지식은 없어도 돼요."},
	{Key: "everyday_recommendations_02", Part: PartDescription, Scene: "친구가 오늘 저녁은 간단히 먹고 싶대요.", Text: "친구에게 가볍게 제안하는 말을 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "꼭 알아야 하는 정보나 지식은 없어도 돼요."},
	{Key: "everyday_recommendations_03", Part: PartDescription, Scene: "친구가 물건을 사기 전에 고민하고 있어요.", Text: "친구에게 가볍게 제안하는 말을 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "꼭 알아야 하는 정보나 지식은 없어도 돼요."},
	{Key: "everyday_recommendations_04", Part: PartDescription, Scene: "친구가 쉬는 날에도 할 일을 잔뜩 적었어요.", Text: "친구에게 가볍게 제안하는 말을 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "꼭 알아야 하는 정보나 지식은 없어도 돼요."},
	{Key: "everyday_recommendations_05", Part: PartDescription, Scene: "친구가 새로운 취미를 가볍게 해 보고 싶대요.", Text: "친구에게 가볍게 제안하는 말을 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "꼭 알아야 하는 정보나 지식은 없어도 돼요."},
	{Key: "everyday_recommendations_06", Part: PartDescription, Scene: "친구가 집중이 안 돼서 자리를 옮길까 고민해요.", Text: "친구에게 가볍게 제안하는 말을 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "꼭 알아야 하는 정보나 지식은 없어도 돼요."},
	{Key: "everyday_recommendations_07", Part: PartDescription, Scene: "친구가 기분 전환할 작은 일을 찾고 있어요.", Text: "친구에게 가볍게 제안하는 말을 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "꼭 알아야 하는 정보나 지식은 없어도 돼요."},
	{Key: "everyday_recommendations_08", Part: PartDescription, Scene: "친구에게 요즘 마음에 드는 쉬는 방법을 알려주려 해요.", Text: "친구에게 가볍게 제안하는 말을 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "꼭 알아야 하는 정보나 지식은 없어도 돼요."},
	{Key: "everyday_story_openings_01", Part: PartOpening, Scene: "오늘은 평소와 다르게 걸어서 나왔다는 이야기를 하려 해요.", Text: "이야기를 시작하는 첫마디를 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "친구에게 보내는 짧은 메시지처럼 시작해 주세요."},
	{Key: "everyday_story_openings_02", Part: PartOpening, Scene: "우연히 맛있는 간식을 찾았다는 이야기를 꺼내려 해요.", Text: "이야기를 시작하는 첫마디를 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "친구에게 보내는 짧은 메시지처럼 시작해 주세요."},
	{Key: "everyday_story_openings_03", Part: PartOpening, Scene: "별일 없던 하루에 작은 즐거움이 있었다고 말하려 해요.", Text: "이야기를 시작하는 첫마디를 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "친구에게 보내는 짧은 메시지처럼 시작해 주세요."},
	{Key: "everyday_story_openings_04", Part: PartOpening, Scene: "비 오는 날 집에서 쉰 이야기를 시작하려 해요.", Text: "이야기를 시작하는 첫마디를 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "친구에게 보내는 짧은 메시지처럼 시작해 주세요."},
	{Key: "everyday_story_openings_05", Part: PartOpening, Scene: "처음 써 본 작은 물건을 소개하려 해요.", Text: "이야기를 시작하는 첫마디를 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "친구에게 보내는 짧은 메시지처럼 시작해 주세요."},
	{Key: "everyday_story_openings_06", Part: PartOpening, Scene: "새로 발견한 산책길 이야기를 꺼내려 해요.", Text: "이야기를 시작하는 첫마디를 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "친구에게 보내는 짧은 메시지처럼 시작해 주세요."},
	{Key: "everyday_story_openings_07", Part: PartOpening, Scene: "조금 웃긴 실수를 했다는 이야기를 시작하려 해요.", Text: "이야기를 시작하는 첫마디를 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "친구에게 보내는 짧은 메시지처럼 시작해 주세요."},
	{Key: "everyday_story_openings_08", Part: PartOpening, Scene: "갑자기 계획을 바꿨다는 이야기를 전하려 해요.", Text: "이야기를 시작하는 첫마디를 써 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "친구에게 보내는 짧은 메시지처럼 시작해 주세요."},
	{Key: "everyday_story_closings_01", Part: PartClosing, Scene: "친구에게 새 간식을 추천하는 이야기를 다 했어요.", Text: "마지막 한마디로 이야기를 마무리해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "끝인사나 다음에 하고 싶은 일을 써도 좋아요."},
	{Key: "everyday_story_closings_02", Part: PartClosing, Scene: "조용한 가게에서 쉬었던 이야기를 마무리하려 해요.", Text: "마지막 한마디로 이야기를 마무리해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "끝인사나 다음에 하고 싶은 일을 써도 좋아요."},
	{Key: "everyday_story_closings_03", Part: PartClosing, Scene: "처음 써 본 물건의 좋고 아쉬운 점을 다 이야기했어요.", Text: "마지막 한마디로 이야기를 마무리해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "끝인사나 다음에 하고 싶은 일을 써도 좋아요."},
	{Key: "everyday_story_closings_04", Part: PartClosing, Scene: "기다리는 동안 생긴 작은 일을 이야기했어요.", Text: "마지막 한마디로 이야기를 마무리해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "끝인사나 다음에 하고 싶은 일을 써도 좋아요."},
	{Key: "everyday_story_closings_05", Part: PartClosing, Scene: "주말에 쉬기로 한 이유를 친구에게 설명했어요.", Text: "마지막 한마디로 이야기를 마무리해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "끝인사나 다음에 하고 싶은 일을 써도 좋아요."},
	{Key: "everyday_story_closings_06", Part: PartClosing, Scene: "새로 찾은 산책길 이야기를 끝내려 해요.", Text: "마지막 한마디로 이야기를 마무리해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "끝인사나 다음에 하고 싶은 일을 써도 좋아요."},
	{Key: "everyday_story_closings_07", Part: PartClosing, Scene: "계획을 바꾼 하루 이야기를 마무리하려 해요.", Text: "마지막 한마디로 이야기를 마무리해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "끝인사나 다음에 하고 싶은 일을 써도 좋아요."},
	{Key: "everyday_story_closings_08", Part: PartClosing, Scene: "친구에게 오늘 하루의 기분을 다 전했어요.", Text: "마지막 한마디로 이야기를 마무리해 보세요. 1~3문장으로 편하게 써 주세요.", Hint: "끝인사나 다음에 하고 싶은 일을 써도 좋아요."},
}
