// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deletePaymentMethod = `-- name: DeletePaymentMethod :exec
DELETE FROM payment_methods WHERE user_id = ?
`

func (q *Queries) DeletePaymentMethod(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deletePaymentMethod, userID)
	return err
}

const getPaymentMethod = `-- name: GetPaymentMethod :one
SELECT user_id, provider, billing_key, customer_key, card_label, registered_at
FROM payment_methods WHERE user_id = ?
`

func (q *Queries) GetPaymentMethod(ctx context.Context, userID string) (PaymentMethod, error) {
	row := q.db.QueryRowContext(ctx, getPaymentMethod, userID)
	var i PaymentMethod
	err := row.Scan(
		&i.UserID,
		&i.Provider,
		&i.BillingKey,
		&i.CustomerKey,
		&i.CardLabel,
		&i.RegisteredAt,
	)
	return i, err
}

const getSubscription = `-- name: GetSubscription :one

SELECT user_id, tier, term, anchor_at, term_start, term_end, next_grant_at, auto_renew,
       scheduled_tier, scheduled_term, status, created_at, updated_at
FROM subscriptions WHERE user_id = ?
`

// Billing owns these reads and notification writes. billing_events deliberately has no
// UPDATE or DELETE query: its history is append-only at the application boundary.
func (q *Queries) GetSubscription(ctx context.Context, userID string) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscription, userID)
	var i Subscription
	err := row.Scan(
		&i.UserID,
		&i.Tier,
		&i.Term,
		&i.AnchorAt,
		&i.TermStart,
		&i.TermEnd,
		&i.NextGrantAt,
		&i.AutoRenew,
		&i.ScheduledTier,
		&i.ScheduledTerm,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBillingEvent = `-- name: InsertBillingEvent :exec
INSERT INTO billing_events (
    user_id, kind, tier, term, credits, usd_cents, krw_per_usd_e4, rate_date,
    krw, provider_payment_key, order_id, note, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertBillingEventParams struct {
	UserID             string
	Kind               string
	Tier               sql.NullString
	Term               sql.NullString
	Credits            sql.NullInt64
	UsdCents           sql.NullInt64
	KrwPerUsdE4        sql.NullInt64
	RateDate           sql.NullString
	Krw                sql.NullInt64
	ProviderPaymentKey sql.NullString
	OrderID            sql.NullString
	Note               sql.NullString
	CreatedAt          string
}

func (q *Queries) InsertBillingEvent(ctx context.Context, arg InsertBillingEventParams) error {
	_, err := q.db.ExecContext(ctx, insertBillingEvent,
		arg.UserID,
		arg.Kind,
		arg.Tier,
		arg.Term,
		arg.Credits,
		arg.UsdCents,
		arg.KrwPerUsdE4,
		arg.RateDate,
		arg.Krw,
		arg.ProviderPaymentKey,
		arg.OrderID,
		arg.Note,
		arg.CreatedAt,
	)
	return err
}

const insertProviderNotification = `-- name: InsertProviderNotification :exec
INSERT INTO provider_notifications (
    provider, event_type, payment_key, order_id, status, payload, received_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertProviderNotificationParams struct {
	Provider   string
	EventType  string
	PaymentKey sql.NullString
	OrderID    sql.NullString
	Status     sql.NullString
	Payload    string
	ReceivedAt string
}

func (q *Queries) InsertProviderNotification(ctx context.Context, arg InsertProviderNotificationParams) error {
	_, err := q.db.ExecContext(ctx, insertProviderNotification,
		arg.Provider,
		arg.EventType,
		arg.PaymentKey,
		arg.OrderID,
		arg.Status,
		arg.Payload,
		arg.ReceivedAt,
	)
	return err
}

const listBillingEvents = `-- name: ListBillingEvents :many
SELECT id, user_id, kind, tier, term, credits, usd_cents, krw_per_usd_e4, rate_date,
       krw, provider_payment_key, order_id, note, created_at
FROM billing_events WHERE user_id = ? ORDER BY created_at DESC, id DESC LIMIT ?
`

type ListBillingEventsParams struct {
	UserID string
	Limit  int64
}

func (q *Queries) ListBillingEvents(ctx context.Context, arg ListBillingEventsParams) ([]BillingEvent, error) {
	rows, err := q.db.QueryContext(ctx, listBillingEvents, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillingEvent
	for rows.Next() {
		var i BillingEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Tier,
			&i.Term,
			&i.Credits,
			&i.UsdCents,
			&i.KrwPerUsdE4,
			&i.RateDate,
			&i.Krw,
			&i.ProviderPaymentKey,
			&i.OrderID,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCreditPurchases = `-- name: ListCreditPurchases :many
SELECT id, user_id, lot_id, credits, usd_cents, krw, provider_payment_key, order_id,
       charged_at, refunded_at
FROM credit_purchases WHERE user_id = ? ORDER BY charged_at DESC, id DESC
`

func (q *Queries) ListCreditPurchases(ctx context.Context, userID string) ([]CreditPurchase, error) {
	rows, err := q.db.QueryContext(ctx, listCreditPurchases, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreditPurchase
	for rows.Next() {
		var i CreditPurchase
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LotID,
			&i.Credits,
			&i.UsdCents,
			&i.Krw,
			&i.ProviderPaymentKey,
			&i.OrderID,
			&i.ChargedAt,
			&i.RefundedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueSubscriptions = `-- name: ListDueSubscriptions :many
SELECT user_id, tier, term, anchor_at, term_start, term_end, next_grant_at, auto_renew,
       scheduled_tier, scheduled_term, status, created_at, updated_at
FROM subscriptions
WHERE status = 'active' AND next_grant_at <= ?
ORDER BY next_grant_at, user_id
`

func (q *Queries) ListDueSubscriptions(ctx context.Context, nextGrantAt string) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, listDueSubscriptions, nextGrantAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.UserID,
			&i.Tier,
			&i.Term,
			&i.AnchorAt,
			&i.TermStart,
			&i.TermEnd,
			&i.NextGrantAt,
			&i.AutoRenew,
			&i.ScheduledTier,
			&i.ScheduledTerm,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPaymentMethod = `-- name: UpsertPaymentMethod :exec
INSERT INTO payment_methods (
    user_id, provider, billing_key, customer_key, card_label, registered_at
) VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(user_id) DO UPDATE SET
    provider = excluded.provider,
    billing_key = excluded.billing_key,
    customer_key = excluded.customer_key,
    card_label = excluded.card_label,
    registered_at = excluded.registered_at
`

type UpsertPaymentMethodParams struct {
	UserID       string
	Provider     string
	BillingKey   string
	CustomerKey  string
	CardLabel    string
	RegisteredAt string
}

func (q *Queries) UpsertPaymentMethod(ctx context.Context, arg UpsertPaymentMethodParams) error {
	_, err := q.db.ExecContext(ctx, upsertPaymentMethod,
		arg.UserID,
		arg.Provider,
		arg.BillingKey,
		arg.CustomerKey,
		arg.CardLabel,
		arg.RegisteredAt,
	)
	return err
}

const upsertSubscription = `-- name: UpsertSubscription :exec
INSERT INTO subscriptions (
    user_id, tier, term, anchor_at, term_start, term_end, next_grant_at, auto_renew,
    scheduled_tier, scheduled_term, status, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(user_id) DO UPDATE SET
    tier = excluded.tier,
    term = excluded.term,
    anchor_at = excluded.anchor_at,
    term_start = excluded.term_start,
    term_end = excluded.term_end,
    next_grant_at = excluded.next_grant_at,
    auto_renew = excluded.auto_renew,
    scheduled_tier = excluded.scheduled_tier,
    scheduled_term = excluded.scheduled_term,
    status = excluded.status,
    updated_at = excluded.updated_at
`

type UpsertSubscriptionParams struct {
	UserID        string
	Tier          string
	Term          string
	AnchorAt      string
	TermStart     string
	TermEnd       string
	NextGrantAt   string
	AutoRenew     int64
	ScheduledTier sql.NullString
	ScheduledTerm sql.NullString
	Status        string
	CreatedAt     string
	UpdatedAt     string
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, upsertSubscription,
		arg.UserID,
		arg.Tier,
		arg.Term,
		arg.AnchorAt,
		arg.TermStart,
		arg.TermEnd,
		arg.NextGrantAt,
		arg.AutoRenew,
		arg.ScheduledTier,
		arg.ScheduledTerm,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
