// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type CreditPurchase struct {
	ID                 string
	UserID             string
	LotID              string
	PackID             sql.NullString
	Credits            int64
	Krw                int64
	ProviderPaymentKey string
	OrderID            string
	ChargedAt          string
	RefundedAt         sql.NullString
}

type PaymentMethod struct {
	UserID       string
	Provider     string
	BillingKey   string
	CustomerKey  string
	CardLabel    string
	RegisteredAt string
}

type SupportCoverage struct {
	UserID     string
	CoverageID string
	Tier       string
	AnchorAt   string
	UpdatedAt  string
}
