// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"
	"database/sql"
)

const consumeLink = `-- name: ConsumeLink :one
UPDATE auth_links SET used_at = ?
WHERE token_hash = ?
  AND purpose = ?
  AND used_at IS NULL
  AND expires_at > ?
RETURNING token_hash, user_id, purpose, email, expires_at, used_at, created_at
`

type ConsumeLinkParams struct {
	UsedAt    sql.NullString
	TokenHash string
	Purpose   string
	ExpiresAt string
}

func (q *Queries) ConsumeLink(ctx context.Context, arg ConsumeLinkParams) (AuthLink, error) {
	row := q.db.QueryRowContext(ctx, consumeLink,
		arg.UsedAt,
		arg.TokenHash,
		arg.Purpose,
		arg.ExpiresAt,
	)
	var i AuthLink
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.Purpose,
		&i.Email,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createLink = `-- name: CreateLink :exec
INSERT INTO auth_links (
  token_hash, user_id, purpose, email, expires_at, used_at, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateLinkParams struct {
	TokenHash string
	UserID    string
	Purpose   string
	Email     string
	ExpiresAt string
	UsedAt    sql.NullString
	CreatedAt string
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) error {
	_, err := q.db.ExecContext(ctx, createLink,
		arg.TokenHash,
		arg.UserID,
		arg.Purpose,
		arg.Email,
		arg.ExpiresAt,
		arg.UsedAt,
		arg.CreatedAt,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token, user_id, expires_at, created_at) VALUES (?, ?, ?, ?)
`

type CreateSessionParams struct {
	Token     string
	UserID    string
	ExpiresAt string
	CreatedAt string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.Token,
		arg.UserID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec

INSERT INTO users (
  id, password_hash, email, email_verified_at, email_unreachable_at,
  failed_logins, locked_until, google_subject, plan, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID                 string
	PasswordHash       string
	Email              sql.NullString
	EmailVerifiedAt    sql.NullString
	EmailUnreachableAt sql.NullString
	FailedLogins       int64
	LockedUntil        sql.NullString
	GoogleSubject      sql.NullString
	Plan               string
	CreatedAt          string
}

// Queries for the auth context. sqlc compiles these into internal/auth/store/sqlc;
// internal/auth/store maps the generated rows to domain types.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.PasswordHash,
		arg.Email,
		arg.EmailVerifiedAt,
		arg.EmailUnreachableAt,
		arg.FailedLogins,
		arg.LockedUntil,
		arg.GoogleSubject,
		arg.Plan,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const deleteSessionsForUser = `-- name: DeleteSessionsForUser :exec
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteSessionsForUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsForUser, userID)
	return err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT token, user_id, expires_at, created_at FROM sessions WHERE token = ?
`

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByToken, token)
	var i Session
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, password_hash, email, email_verified_at, email_unreachable_at,
       failed_logins, locked_until, google_subject, plan, created_at
FROM users WHERE id = ?
`

type GetUserRow struct {
	ID                 string
	PasswordHash       string
	Email              sql.NullString
	EmailVerifiedAt    sql.NullString
	EmailUnreachableAt sql.NullString
	FailedLogins       int64
	LockedUntil        sql.NullString
	GoogleSubject      sql.NullString
	Plan               string
	CreatedAt          string
}

func (q *Queries) GetUser(ctx context.Context, id string) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.PasswordHash,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.EmailUnreachableAt,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.GoogleSubject,
		&i.Plan,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, password_hash, email, email_verified_at, email_unreachable_at,
       failed_logins, locked_until, google_subject, plan, created_at
FROM users WHERE email = ?
`

type GetUserByEmailRow struct {
	ID                 string
	PasswordHash       string
	Email              sql.NullString
	EmailVerifiedAt    sql.NullString
	EmailUnreachableAt sql.NullString
	FailedLogins       int64
	LockedUntil        sql.NullString
	GoogleSubject      sql.NullString
	Plan               string
	CreatedAt          string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email sql.NullString) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.PasswordHash,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.EmailUnreachableAt,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.GoogleSubject,
		&i.Plan,
		&i.CreatedAt,
	)
	return i, err
}

const getUserCreatedAt = `-- name: GetUserCreatedAt :one
SELECT created_at FROM users WHERE id = ?
`

// The usage anchor needs only this instant; never load the password hash for it.
func (q *Queries) GetUserCreatedAt(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserCreatedAt, id)
	var created_at string
	err := row.Scan(&created_at)
	return created_at, err
}

const getUserPlan = `-- name: GetUserPlan :one
SELECT plan FROM users WHERE id = ?
`

func (q *Queries) GetUserPlan(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserPlan, id)
	var plan string
	err := row.Scan(&plan)
	return plan, err
}

const invalidateLinks = `-- name: InvalidateLinks :exec
UPDATE auth_links SET used_at = ?
WHERE user_id = ? AND purpose = ? AND used_at IS NULL
`

type InvalidateLinksParams struct {
	UsedAt  sql.NullString
	UserID  string
	Purpose string
}

func (q *Queries) InvalidateLinks(ctx context.Context, arg InvalidateLinksParams) error {
	_, err := q.db.ExecContext(ctx, invalidateLinks, arg.UsedAt, arg.UserID, arg.Purpose)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, email_verified_at, email_unreachable_at, failed_logins,
       locked_until, google_subject, plan, created_at
FROM users ORDER BY created_at, id
`

type ListUsersRow struct {
	ID                 string
	Email              sql.NullString
	EmailVerifiedAt    sql.NullString
	EmailUnreachableAt sql.NullString
	FailedLogins       int64
	LockedUntil        sql.NullString
	GoogleSubject      sql.NullString
	Plan               string
	CreatedAt          string
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.EmailVerifiedAt,
			&i.EmailUnreachableAt,
			&i.FailedLogins,
			&i.LockedUntil,
			&i.GoogleSubject,
			&i.Plan,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailUnreachable = `-- name: MarkEmailUnreachable :exec
UPDATE users SET email_unreachable_at = ? WHERE id = ?
`

type MarkEmailUnreachableParams struct {
	EmailUnreachableAt sql.NullString
	ID                 string
}

func (q *Queries) MarkEmailUnreachable(ctx context.Context, arg MarkEmailUnreachableParams) error {
	_, err := q.db.ExecContext(ctx, markEmailUnreachable, arg.EmailUnreachableAt, arg.ID)
	return err
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE users SET email_verified_at = ? WHERE id = ?
`

type MarkEmailVerifiedParams struct {
	EmailVerifiedAt sql.NullString
	ID              string
}

func (q *Queries) MarkEmailVerified(ctx context.Context, arg MarkEmailVerifiedParams) error {
	_, err := q.db.ExecContext(ctx, markEmailVerified, arg.EmailVerifiedAt, arg.ID)
	return err
}

const setEmail = `-- name: SetEmail :exec
UPDATE users
SET email = NULLIF(?1, ''),
    email_verified_at = ?2
WHERE id = ?3
`

type SetEmailParams struct {
	Email           interface{}
	EmailVerifiedAt sql.NullString
	ID              string
}

func (q *Queries) SetEmail(ctx context.Context, arg SetEmailParams) error {
	_, err := q.db.ExecContext(ctx, setEmail, arg.Email, arg.EmailVerifiedAt, arg.ID)
	return err
}

const setUserPlan = `-- name: SetUserPlan :execrows
UPDATE users SET plan = ?
WHERE users.id = ?
  AND (users.plan <> 'master' OR (SELECT COUNT(*) FROM users AS m WHERE m.plan = 'master') > 1)
`

type SetUserPlanParams struct {
	Plan string
	ID   string
}

// The last-master guard is part of the statement, not a check before it: two concurrent
// demotions that each counted two masters would both commit and leave the deployment with
// none, and nothing could promote anyone back.
func (q *Queries) SetUserPlan(ctx context.Context, arg SetUserPlanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setUserPlan, arg.Plan, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
