// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type Session struct {
	Token     string
	UserID    string
	ExpiresAt string
	CreatedAt string
}

type User struct {
	ID           string
	PasswordHash string
	CreatedAt    string
}
