// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type AuthLink struct {
	TokenHash string
	UserID    string
	Purpose   string
	Email     string
	ExpiresAt string
	UsedAt    sql.NullString
	CreatedAt string
}

type Session struct {
	Token     string
	UserID    string
	ExpiresAt string
	CreatedAt string
}
