// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type PublishAsset struct {
	JobID          string
	UserID         string
	Ordinal        int64
	Filename       string
	SourceFilename string
	StagedKey      string
	Bytes          int64
	CreatedAt      string
}

type PublishJob struct {
	ID                  string
	UserID              string
	PostSlug            string
	PostCreatedAt       string
	AgentID             string
	Platform            string
	Status              string
	Stage               string
	ProgressSeq         int64
	Attempt             int64
	ContentRevision     int64
	ManifestJson        sql.NullString
	SettingsJson        string
	LeaseTokenHash      sql.NullString
	LeaseExpiresAt      sql.NullString
	ErrorCode           sql.NullString
	ErrorMessage        sql.NullString
	PlatformPostUrl     sql.NullString
	CreatedAt           string
	ClaimedAt           sql.NullString
	CommittedAt         sql.NullString
	PublishedAt         sql.NullString
	UpdatedAt           string
	TargetLanguage      sql.NullString
	ContentLanguage     sql.NullString
	VoiceSourceLanguage sql.NullString
	ErrorReason         sql.NullString
	ErrorParams         sql.NullString
	TechnicalDetail     sql.NullString
}

type PublishingAgent struct {
	ID                   string
	UserID               string
	TokenHash            string
	Label                string
	Platform             string
	PlatformAccountID    string
	PlatformAccountLabel string
	BrowserLabel         string
	CategoriesJson       string
	DefaultCategoryID    string
	DefaultVisibility    string
	CompatibilityReady   int64
	HermesVersion        string
	LastSeenAt           sql.NullString
	RevokedAt            sql.NullString
	CreatedAt            string
	UpdatedAt            string
}
