// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: publishing.sql

package sqlc

import (
	"context"
	"database/sql"
)

const cancelPublishJob = `-- name: CancelPublishJob :execrows
UPDATE publish_jobs
SET status='canceled',manifest_json=NULL,lease_token_hash=NULL,lease_expires_at=NULL,updated_at=?
WHERE id=? AND user_id=? AND status IN ('queued','running','needs_attention')
  AND committed_at IS NULL AND stage NOT IN ('committing','verifying','published')
`

type CancelPublishJobParams struct {
	UpdatedAt string
	ID        string
	UserID    string
}

func (q *Queries) CancelPublishJob(ctx context.Context, arg CancelPublishJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelPublishJob, arg.UpdatedAt, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const claimQueuedPublishJob = `-- name: ClaimQueuedPublishJob :one
UPDATE publish_jobs
SET status='running',stage='claimed',progress_seq=1,attempt=attempt+1,
    lease_token_hash=?,lease_expires_at=?,claimed_at=COALESCE(claimed_at,?),updated_at=?
WHERE id=(
  SELECT j.id FROM publish_jobs j
  JOIN publishing_agents a ON a.id=j.agent_id AND a.user_id=j.user_id
  WHERE j.status='queued' AND a.id=? AND a.user_id=? AND a.revoked_at IS NULL
  ORDER BY j.created_at,j.id LIMIT 1
)
RETURNING id, user_id, post_slug, post_created_at, agent_id, platform, status, stage, progress_seq, attempt, content_revision, manifest_json, settings_json, lease_token_hash, lease_expires_at, error_code, error_message, platform_post_url, created_at, claimed_at, committed_at, published_at, updated_at
`

type ClaimQueuedPublishJobParams struct {
	LeaseTokenHash sql.NullString
	LeaseExpiresAt sql.NullString
	ClaimedAt      sql.NullString
	UpdatedAt      string
	ID             string
	UserID         string
}

func (q *Queries) ClaimQueuedPublishJob(ctx context.Context, arg ClaimQueuedPublishJobParams) (PublishJob, error) {
	row := q.db.QueryRowContext(ctx, claimQueuedPublishJob,
		arg.LeaseTokenHash,
		arg.LeaseExpiresAt,
		arg.ClaimedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	var i PublishJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PostSlug,
		&i.PostCreatedAt,
		&i.AgentID,
		&i.Platform,
		&i.Status,
		&i.Stage,
		&i.ProgressSeq,
		&i.Attempt,
		&i.ContentRevision,
		&i.ManifestJson,
		&i.SettingsJson,
		&i.LeaseTokenHash,
		&i.LeaseExpiresAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.PlatformPostUrl,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.CommittedAt,
		&i.PublishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completePublishJob = `-- name: CompletePublishJob :execrows
UPDATE publish_jobs
SET status='published',stage='published',progress_seq=?,platform_post_url=?,published_at=?,
    manifest_json=NULL,lease_token_hash=NULL,lease_expires_at=NULL,error_code=NULL,error_message=NULL,updated_at=?
WHERE publish_jobs.id=? AND publish_jobs.user_id=? AND publish_jobs.agent_id=?
  AND publish_jobs.status='running' AND publish_jobs.stage='verifying'
  AND publish_jobs.lease_token_hash=? AND publish_jobs.lease_expires_at>?
  AND publish_jobs.progress_seq<?
  AND EXISTS (
    SELECT 1 FROM publishing_agents AS active_agent
    WHERE active_agent.id=publish_jobs.agent_id
      AND active_agent.user_id=publish_jobs.user_id
      AND active_agent.revoked_at IS NULL
  )
`

type CompletePublishJobParams struct {
	ProgressSeq     int64
	PlatformPostUrl sql.NullString
	PublishedAt     sql.NullString
	UpdatedAt       string
	ID              string
	UserID          string
	AgentID         string
	LeaseTokenHash  sql.NullString
	LeaseExpiresAt  sql.NullString
	ProgressSeq_2   int64
}

func (q *Queries) CompletePublishJob(ctx context.Context, arg CompletePublishJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completePublishJob,
		arg.ProgressSeq,
		arg.PlatformPostUrl,
		arg.PublishedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
		arg.AgentID,
		arg.LeaseTokenHash,
		arg.LeaseExpiresAt,
		arg.ProgressSeq_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const consumePairing = `-- name: ConsumePairing :one
UPDATE publishing_pairings SET consumed_at = ?
WHERE code_hash = ? AND consumed_at IS NULL AND expires_at > ?
RETURNING user_id,label
`

type ConsumePairingParams struct {
	ConsumedAt sql.NullString
	CodeHash   string
	ExpiresAt  string
}

type ConsumePairingRow struct {
	UserID string
	Label  string
}

func (q *Queries) ConsumePairing(ctx context.Context, arg ConsumePairingParams) (ConsumePairingRow, error) {
	row := q.db.QueryRowContext(ctx, consumePairing, arg.ConsumedAt, arg.CodeHash, arg.ExpiresAt)
	var i ConsumePairingRow
	err := row.Scan(&i.UserID, &i.Label)
	return i, err
}

const createAgent = `-- name: CreateAgent :exec
INSERT INTO publishing_agents(
  id,user_id,token_hash,label,platform,browser_label,created_at,updated_at
) VALUES(?,?,?,?,'naver_blog',?,?,?)
`

type CreateAgentParams struct {
	ID           string
	UserID       string
	TokenHash    string
	Label        string
	BrowserLabel string
	CreatedAt    string
	UpdatedAt    string
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) error {
	_, err := q.db.ExecContext(ctx, createAgent,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.Label,
		arg.BrowserLabel,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createPairingBelowLimit = `-- name: CreatePairingBelowLimit :execrows
INSERT INTO publishing_pairings(code_hash,user_id,label,expires_at,created_at)
SELECT ?1,?2,?3,?4,?5
WHERE (SELECT count(*) FROM publishing_pairings AS pending
       WHERE pending.consumed_at IS NULL AND pending.expires_at > ?6)
      < CAST(?7 AS INTEGER)
`

type CreatePairingBelowLimitParams struct {
	CodeHash         string
	UserID           string
	Label            string
	PairingExpiresAt string
	CreatedAt        string
	Now              string
	MaxPending       int64
}

func (q *Queries) CreatePairingBelowLimit(ctx context.Context, arg CreatePairingBelowLimitParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createPairingBelowLimit,
		arg.CodeHash,
		arg.UserID,
		arg.Label,
		arg.PairingExpiresAt,
		arg.CreatedAt,
		arg.Now,
		arg.MaxPending,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createPublishAsset = `-- name: CreatePublishAsset :exec
INSERT INTO publish_assets(job_id,user_id,ordinal,filename,source_filename,staged_key,bytes,created_at)
VALUES(?,?,?,?,?,?,?,?)
`

type CreatePublishAssetParams struct {
	JobID          string
	UserID         string
	Ordinal        int64
	Filename       string
	SourceFilename string
	StagedKey      string
	Bytes          int64
	CreatedAt      string
}

func (q *Queries) CreatePublishAsset(ctx context.Context, arg CreatePublishAssetParams) error {
	_, err := q.db.ExecContext(ctx, createPublishAsset,
		arg.JobID,
		arg.UserID,
		arg.Ordinal,
		arg.Filename,
		arg.SourceFilename,
		arg.StagedKey,
		arg.Bytes,
		arg.CreatedAt,
	)
	return err
}

const createPublishJob = `-- name: CreatePublishJob :exec
INSERT INTO publish_jobs(
  id,user_id,post_slug,post_created_at,agent_id,platform,status,stage,progress_seq,attempt,
  content_revision,manifest_json,settings_json,created_at,updated_at
) VALUES(?,?,?,?,?,'naver_blog','queued','queued',0,0,?,?,?,?,?)
`

type CreatePublishJobParams struct {
	ID              string
	UserID          string
	PostSlug        string
	PostCreatedAt   string
	AgentID         string
	ContentRevision int64
	ManifestJson    sql.NullString
	SettingsJson    string
	CreatedAt       string
	UpdatedAt       string
}

func (q *Queries) CreatePublishJob(ctx context.Context, arg CreatePublishJobParams) error {
	_, err := q.db.ExecContext(ctx, createPublishJob,
		arg.ID,
		arg.UserID,
		arg.PostSlug,
		arg.PostCreatedAt,
		arg.AgentID,
		arg.ContentRevision,
		arg.ManifestJson,
		arg.SettingsJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deletePublishAssets = `-- name: DeletePublishAssets :exec
DELETE FROM publish_assets WHERE job_id=?
`

func (q *Queries) DeletePublishAssets(ctx context.Context, jobID string) error {
	_, err := q.db.ExecContext(ctx, deletePublishAssets, jobID)
	return err
}

const failPublishJob = `-- name: FailPublishJob :execrows
UPDATE publish_jobs
SET status=CASE
      WHEN committed_at IS NOT NULL OR stage IN ('committing','verifying','published') THEN ?1
      ELSE ?2
    END,
    progress_seq=?3,
    error_code=CASE
      WHEN committed_at IS NOT NULL OR stage IN ('committing','verifying','published') THEN ?4
      ELSE ?5
    END,
    error_message=CASE
      WHEN committed_at IS NOT NULL OR stage IN ('committing','verifying','published') THEN ?6
      ELSE ?7
    END,
    manifest_json=CASE
      WHEN committed_at IS NULL AND stage NOT IN ('committing','verifying','published')
        AND ?2='needs_attention' THEN manifest_json
      ELSE NULL
    END,
    lease_token_hash=NULL,lease_expires_at=NULL,updated_at=?8
WHERE publish_jobs.id=?9 AND publish_jobs.user_id=?10
  AND publish_jobs.agent_id=?11 AND publish_jobs.status='running'
  AND publish_jobs.lease_token_hash=?12
  AND publish_jobs.lease_expires_at>?13
  AND publish_jobs.progress_seq<?3
  AND EXISTS (
    SELECT 1 FROM publishing_agents AS active_agent
    WHERE active_agent.id=publish_jobs.agent_id
      AND active_agent.user_id=publish_jobs.user_id
      AND active_agent.revoked_at IS NULL
  )
`

type FailPublishJobParams struct {
	CommitStatus          string
	PrecommitStatus       string
	NextSeq               int64
	CommitErrorCode       sql.NullString
	PrecommitErrorCode    sql.NullString
	CommitErrorMessage    sql.NullString
	PrecommitErrorMessage sql.NullString
	UpdatedAt             string
	ID                    string
	UserID                string
	AgentID               string
	LeaseTokenHash        sql.NullString
	Now                   sql.NullString
}

func (q *Queries) FailPublishJob(ctx context.Context, arg FailPublishJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failPublishJob,
		arg.CommitStatus,
		arg.PrecommitStatus,
		arg.NextSeq,
		arg.CommitErrorCode,
		arg.PrecommitErrorCode,
		arg.CommitErrorMessage,
		arg.PrecommitErrorMessage,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
		arg.AgentID,
		arg.LeaseTokenHash,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getActiveAgentByTokenHash = `-- name: GetActiveAgentByTokenHash :one
SELECT id, user_id, token_hash, label, platform, platform_account_id, platform_account_label, browser_label, categories_json, default_category_id, default_visibility, compatibility_ready, hermes_version, last_seen_at, revoked_at, created_at, updated_at FROM publishing_agents WHERE token_hash = ? AND revoked_at IS NULL
`

func (q *Queries) GetActiveAgentByTokenHash(ctx context.Context, tokenHash string) (PublishingAgent, error) {
	row := q.db.QueryRowContext(ctx, getActiveAgentByTokenHash, tokenHash)
	var i PublishingAgent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Label,
		&i.Platform,
		&i.PlatformAccountID,
		&i.PlatformAccountLabel,
		&i.BrowserLabel,
		&i.CategoriesJson,
		&i.DefaultCategoryID,
		&i.DefaultVisibility,
		&i.CompatibilityReady,
		&i.HermesVersion,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestPublishJobForDeletedPost = `-- name: GetLatestPublishJobForDeletedPost :one
SELECT id, user_id, post_slug, post_created_at, agent_id, platform, status, stage, progress_seq, attempt, content_revision, manifest_json, settings_json, lease_token_hash, lease_expires_at, error_code, error_message, platform_post_url, created_at, claimed_at, committed_at, published_at, updated_at FROM publish_jobs WHERE post_slug=? AND user_id=?
ORDER BY created_at DESC,id DESC LIMIT 1
`

type GetLatestPublishJobForDeletedPostParams struct {
	PostSlug string
	UserID   string
}

// Used only after the post context confirms that no current slug incarnation
// exists, so a retained frozen needs-attention job remains explicitly retryable.
func (q *Queries) GetLatestPublishJobForDeletedPost(ctx context.Context, arg GetLatestPublishJobForDeletedPostParams) (PublishJob, error) {
	row := q.db.QueryRowContext(ctx, getLatestPublishJobForDeletedPost, arg.PostSlug, arg.UserID)
	var i PublishJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PostSlug,
		&i.PostCreatedAt,
		&i.AgentID,
		&i.Platform,
		&i.Status,
		&i.Stage,
		&i.ProgressSeq,
		&i.Attempt,
		&i.ContentRevision,
		&i.ManifestJson,
		&i.SettingsJson,
		&i.LeaseTokenHash,
		&i.LeaseExpiresAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.PlatformPostUrl,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.CommittedAt,
		&i.PublishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestPublishJobForPost = `-- name: GetLatestPublishJobForPost :one
SELECT id, user_id, post_slug, post_created_at, agent_id, platform, status, stage, progress_seq, attempt, content_revision, manifest_json, settings_json, lease_token_hash, lease_expires_at, error_code, error_message, platform_post_url, created_at, claimed_at, committed_at, published_at, updated_at FROM publish_jobs WHERE post_slug=? AND user_id=? AND post_created_at=?
ORDER BY created_at DESC,id DESC LIMIT 1
`

type GetLatestPublishJobForPostParams struct {
	PostSlug      string
	UserID        string
	PostCreatedAt string
}

func (q *Queries) GetLatestPublishJobForPost(ctx context.Context, arg GetLatestPublishJobForPostParams) (PublishJob, error) {
	row := q.db.QueryRowContext(ctx, getLatestPublishJobForPost, arg.PostSlug, arg.UserID, arg.PostCreatedAt)
	var i PublishJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PostSlug,
		&i.PostCreatedAt,
		&i.AgentID,
		&i.Platform,
		&i.Status,
		&i.Stage,
		&i.ProgressSeq,
		&i.Attempt,
		&i.ContentRevision,
		&i.ManifestJson,
		&i.SettingsJson,
		&i.LeaseTokenHash,
		&i.LeaseExpiresAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.PlatformPostUrl,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.CommittedAt,
		&i.PublishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOwnedAgent = `-- name: GetOwnedAgent :one
SELECT id, user_id, token_hash, label, platform, platform_account_id, platform_account_label, browser_label, categories_json, default_category_id, default_visibility, compatibility_ready, hermes_version, last_seen_at, revoked_at, created_at, updated_at FROM publishing_agents WHERE id = ? AND user_id = ?
`

type GetOwnedAgentParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetOwnedAgent(ctx context.Context, arg GetOwnedAgentParams) (PublishingAgent, error) {
	row := q.db.QueryRowContext(ctx, getOwnedAgent, arg.ID, arg.UserID)
	var i PublishingAgent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Label,
		&i.Platform,
		&i.PlatformAccountID,
		&i.PlatformAccountLabel,
		&i.BrowserLabel,
		&i.CategoriesJson,
		&i.DefaultCategoryID,
		&i.DefaultVisibility,
		&i.CompatibilityReady,
		&i.HermesVersion,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOwnedPublishJob = `-- name: GetOwnedPublishJob :one
SELECT id, user_id, post_slug, post_created_at, agent_id, platform, status, stage, progress_seq, attempt, content_revision, manifest_json, settings_json, lease_token_hash, lease_expires_at, error_code, error_message, platform_post_url, created_at, claimed_at, committed_at, published_at, updated_at FROM publish_jobs WHERE id=? AND user_id=?
`

type GetOwnedPublishJobParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetOwnedPublishJob(ctx context.Context, arg GetOwnedPublishJobParams) (PublishJob, error) {
	row := q.db.QueryRowContext(ctx, getOwnedPublishJob, arg.ID, arg.UserID)
	var i PublishJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PostSlug,
		&i.PostCreatedAt,
		&i.AgentID,
		&i.Platform,
		&i.Status,
		&i.Stage,
		&i.ProgressSeq,
		&i.Attempt,
		&i.ContentRevision,
		&i.ManifestJson,
		&i.SettingsJson,
		&i.LeaseTokenHash,
		&i.LeaseExpiresAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.PlatformPostUrl,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.CommittedAt,
		&i.PublishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentsByUser = `-- name: ListAgentsByUser :many
SELECT id, user_id, token_hash, label, platform, platform_account_id, platform_account_label, browser_label, categories_json, default_category_id, default_visibility, compatibility_ready, hermes_version, last_seen_at, revoked_at, created_at, updated_at FROM publishing_agents WHERE user_id = ? ORDER BY created_at DESC,id DESC
`

func (q *Queries) ListAgentsByUser(ctx context.Context, userID string) ([]PublishingAgent, error) {
	rows, err := q.db.QueryContext(ctx, listAgentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublishingAgent
	for rows.Next() {
		var i PublishingAgent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.Label,
			&i.Platform,
			&i.PlatformAccountID,
			&i.PlatformAccountLabel,
			&i.BrowserLabel,
			&i.CategoriesJson,
			&i.DefaultCategoryID,
			&i.DefaultVisibility,
			&i.CompatibilityReady,
			&i.HermesVersion,
			&i.LastSeenAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveStagedKeys = `-- name: ListLiveStagedKeys :many
SELECT a.staged_key FROM publish_assets a
JOIN publish_jobs j ON j.id=a.job_id
WHERE j.status IN ('queued','running','needs_attention','outcome_unknown')
`

func (q *Queries) ListLiveStagedKeys(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listLiveStagedKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var staged_key string
		if err := rows.Scan(&staged_key); err != nil {
			return nil, err
		}
		items = append(items, staged_key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishAssets = `-- name: ListPublishAssets :many
SELECT job_id, user_id, ordinal, filename, source_filename, staged_key, bytes, created_at FROM publish_assets WHERE job_id=? ORDER BY ordinal
`

func (q *Queries) ListPublishAssets(ctx context.Context, jobID string) ([]PublishAsset, error) {
	rows, err := q.db.QueryContext(ctx, listPublishAssets, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublishAsset
	for rows.Next() {
		var i PublishAsset
		if err := rows.Scan(
			&i.JobID,
			&i.UserID,
			&i.Ordinal,
			&i.Filename,
			&i.SourceFilename,
			&i.StagedKey,
			&i.Bytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRetryablePublishJobs = `-- name: ListRetryablePublishJobs :many
SELECT id, user_id, post_slug, post_created_at, agent_id, platform, status, stage, progress_seq, attempt, content_revision, manifest_json, settings_json, lease_token_hash, lease_expires_at, error_code, error_message, platform_post_url, created_at, claimed_at, committed_at, published_at, updated_at FROM publish_jobs
WHERE user_id=? AND status='needs_attention' AND committed_at IS NULL
  AND manifest_json IS NOT NULL
ORDER BY updated_at DESC,id DESC
`

func (q *Queries) ListRetryablePublishJobs(ctx context.Context, userID string) ([]PublishJob, error) {
	rows, err := q.db.QueryContext(ctx, listRetryablePublishJobs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublishJob
	for rows.Next() {
		var i PublishJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PostSlug,
			&i.PostCreatedAt,
			&i.AgentID,
			&i.Platform,
			&i.Status,
			&i.Stage,
			&i.ProgressSeq,
			&i.Attempt,
			&i.ContentRevision,
			&i.ManifestJson,
			&i.SettingsJson,
			&i.LeaseTokenHash,
			&i.LeaseExpiresAt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.PlatformPostUrl,
			&i.CreatedAt,
			&i.ClaimedAt,
			&i.CommittedAt,
			&i.PublishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTerminalJobsWithAssets = `-- name: ListTerminalJobsWithAssets :many
SELECT DISTINCT j.id FROM publish_jobs j
JOIN publish_assets a ON a.job_id=j.id
WHERE j.status IN ('published','failed','outcome_unknown','canceled')
`

func (q *Queries) ListTerminalJobsWithAssets(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTerminalJobsWithAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockReadyAgentForPublish = `-- name: LockReadyAgentForPublish :execrows
UPDATE publishing_agents SET updated_at=updated_at
WHERE id=? AND user_id=? AND revoked_at IS NULL AND compatibility_ready=1
`

type LockReadyAgentForPublishParams struct {
	ID     string
	UserID string
}

// This no-op update reserves the serialized writer before Start re-reads the
// post and agent through their owning contexts. No relevant mutation can slip
// between that guard and CreatePublishJob in the same transaction.
func (q *Queries) LockReadyAgentForPublish(ctx context.Context, arg LockReadyAgentForPublishParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, lockReadyAgentForPublish, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markExpiredCommittedJobsUnknown = `-- name: MarkExpiredCommittedJobsUnknown :execrows
UPDATE publish_jobs
SET status='outcome_unknown',manifest_json=NULL,lease_token_hash=NULL,lease_expires_at=NULL,
    error_code=?,error_message=?,updated_at=?
WHERE status='running' AND stage IN ('committing','verifying') AND lease_expires_at<=?
`

type MarkExpiredCommittedJobsUnknownParams struct {
	ErrorCode      sql.NullString
	ErrorMessage   sql.NullString
	UpdatedAt      string
	LeaseExpiresAt sql.NullString
}

func (q *Queries) MarkExpiredCommittedJobsUnknown(ctx context.Context, arg MarkExpiredCommittedJobsUnknownParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markExpiredCommittedJobsUnknown,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.UpdatedAt,
		arg.LeaseExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const releaseUnusedPublishJobID = `-- name: ReleaseUnusedPublishJobID :execrows
DELETE FROM publish_job_ids
WHERE publish_job_ids.id=? AND publish_job_ids.user_id=?
  AND NOT EXISTS (SELECT 1 FROM publish_jobs WHERE publish_jobs.id=publish_job_ids.id)
`

type ReleaseUnusedPublishJobIDParams struct {
	ID     string
	UserID string
}

func (q *Queries) ReleaseUnusedPublishJobID(ctx context.Context, arg ReleaseUnusedPublishJobIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, releaseUnusedPublishJobID, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const renewPublishLease = `-- name: RenewPublishLease :execrows
UPDATE publish_jobs SET lease_expires_at=?,updated_at=?
WHERE publish_jobs.id=? AND publish_jobs.user_id=? AND publish_jobs.agent_id=? AND publish_jobs.status='running'
  AND publish_jobs.lease_token_hash=? AND publish_jobs.lease_expires_at>?
  AND EXISTS (
    SELECT 1 FROM publishing_agents AS active_agent
    WHERE active_agent.id=publish_jobs.agent_id
      AND active_agent.user_id=publish_jobs.user_id
      AND active_agent.revoked_at IS NULL
  )
`

type RenewPublishLeaseParams struct {
	LeaseExpiresAt   sql.NullString
	UpdatedAt        string
	ID               string
	UserID           string
	AgentID          string
	LeaseTokenHash   sql.NullString
	LeaseExpiresAt_2 sql.NullString
}

func (q *Queries) RenewPublishLease(ctx context.Context, arg RenewPublishLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renewPublishLease,
		arg.LeaseExpiresAt,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
		arg.AgentID,
		arg.LeaseTokenHash,
		arg.LeaseExpiresAt_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const requeueExpiredPreCommitJobs = `-- name: RequeueExpiredPreCommitJobs :execrows
UPDATE publish_jobs
SET status='queued',stage='queued',progress_seq=0,lease_token_hash=NULL,lease_expires_at=NULL,updated_at=?
WHERE status='running' AND stage NOT IN ('committing','verifying','published') AND lease_expires_at<=?
`

type RequeueExpiredPreCommitJobsParams struct {
	UpdatedAt      string
	LeaseExpiresAt sql.NullString
}

func (q *Queries) RequeueExpiredPreCommitJobs(ctx context.Context, arg RequeueExpiredPreCommitJobsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, requeueExpiredPreCommitJobs, arg.UpdatedAt, arg.LeaseExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const reservePublishJobID = `-- name: ReservePublishJobID :execrows
INSERT INTO publish_job_ids(id,user_id,created_at) VALUES(?,?,?)
ON CONFLICT(id) DO NOTHING
`

type ReservePublishJobIDParams struct {
	ID        string
	UserID    string
	CreatedAt string
}

func (q *Queries) ReservePublishJobID(ctx context.Context, arg ReservePublishJobIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reservePublishJobID, arg.ID, arg.UserID, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const retryAttentionPublishJob = `-- name: RetryAttentionPublishJob :execrows
UPDATE publish_jobs
SET status='queued',stage='queued',progress_seq=0,error_code=NULL,error_message=NULL,updated_at=?
WHERE publish_jobs.id=? AND publish_jobs.user_id=? AND publish_jobs.status='needs_attention'
  AND publish_jobs.committed_at IS NULL AND publish_jobs.manifest_json IS NOT NULL
  AND EXISTS (
    SELECT 1 FROM publishing_agents AS active_agent
    WHERE active_agent.id=publish_jobs.agent_id
      AND active_agent.user_id=publish_jobs.user_id
      AND active_agent.revoked_at IS NULL
      AND active_agent.compatibility_ready=1
      AND TRIM(active_agent.browser_label)<>''
      AND active_agent.platform_account_id=json_extract(publish_jobs.manifest_json,'$.expected_platform_account_id')
      AND EXISTS (
        SELECT 1 FROM json_each(active_agent.categories_json) AS frozen_category
        WHERE json_extract(frozen_category.value,'$.ID')=json_extract(publish_jobs.manifest_json,'$.category_id')
          AND json_extract(frozen_category.value,'$.Name')=json_extract(publish_jobs.manifest_json,'$.category_name')
      )
      AND EXISTS (
        SELECT 1 FROM json_each(active_agent.categories_json) AS default_category
        WHERE json_extract(default_category.value,'$.ID')=active_agent.default_category_id
          AND TRIM(COALESCE(json_extract(default_category.value,'$.Name'),''))<>''
      )
  )
`

type RetryAttentionPublishJobParams struct {
	UpdatedAt string
	ID        string
	UserID    string
}

func (q *Queries) RetryAttentionPublishJob(ctx context.Context, arg RetryAttentionPublishJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, retryAttentionPublishJob, arg.UpdatedAt, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeOwnedAgent = `-- name: RevokeOwnedAgent :execrows
UPDATE publishing_agents SET revoked_at=?,updated_at=?
WHERE id=? AND user_id=? AND revoked_at IS NULL
`

type RevokeOwnedAgentParams struct {
	RevokedAt sql.NullString
	UpdatedAt string
	ID        string
	UserID    string
}

func (q *Queries) RevokeOwnedAgent(ctx context.Context, arg RevokeOwnedAgentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeOwnedAgent,
		arg.RevokedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const syncAgentProfile = `-- name: SyncAgentProfile :execrows
UPDATE publishing_agents
SET platform_account_id=?,platform_account_label=?,browser_label=?,categories_json=?,
    default_category_id=?,default_visibility=?,compatibility_ready=?,hermes_version=?,
    last_seen_at=?,updated_at=?
WHERE id=? AND user_id=? AND revoked_at IS NULL
`

type SyncAgentProfileParams struct {
	PlatformAccountID    string
	PlatformAccountLabel string
	BrowserLabel         string
	CategoriesJson       string
	DefaultCategoryID    string
	DefaultVisibility    string
	CompatibilityReady   int64
	HermesVersion        string
	LastSeenAt           sql.NullString
	UpdatedAt            string
	ID                   string
	UserID               string
}

func (q *Queries) SyncAgentProfile(ctx context.Context, arg SyncAgentProfileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, syncAgentProfile,
		arg.PlatformAccountID,
		arg.PlatformAccountLabel,
		arg.BrowserLabel,
		arg.CategoriesJson,
		arg.DefaultCategoryID,
		arg.DefaultVisibility,
		arg.CompatibilityReady,
		arg.HermesVersion,
		arg.LastSeenAt,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchAgent = `-- name: TouchAgent :execrows
UPDATE publishing_agents SET last_seen_at=?,updated_at=?
WHERE id=? AND user_id=? AND revoked_at IS NULL
`

type TouchAgentParams struct {
	LastSeenAt sql.NullString
	UpdatedAt  string
	ID         string
	UserID     string
}

func (q *Queries) TouchAgent(ctx context.Context, arg TouchAgentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchAgent,
		arg.LastSeenAt,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateOwnedAgentDefaults = `-- name: UpdateOwnedAgentDefaults :execrows
UPDATE publishing_agents
SET label=?,default_category_id=?,default_visibility=?,updated_at=?
WHERE id=? AND user_id=? AND revoked_at IS NULL
`

type UpdateOwnedAgentDefaultsParams struct {
	Label             string
	DefaultCategoryID string
	DefaultVisibility string
	UpdatedAt         string
	ID                string
	UserID            string
}

func (q *Queries) UpdateOwnedAgentDefaults(ctx context.Context, arg UpdateOwnedAgentDefaultsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateOwnedAgentDefaults,
		arg.Label,
		arg.DefaultCategoryID,
		arg.DefaultVisibility,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePublishProgress = `-- name: UpdatePublishProgress :execrows
UPDATE publish_jobs
SET stage=?1,progress_seq=?2,
    committed_at=CASE WHEN ?1='committing' THEN COALESCE(committed_at,?3) ELSE committed_at END,
    updated_at=?4
WHERE publish_jobs.id=?5 AND publish_jobs.user_id=?6
  AND publish_jobs.agent_id=?7 AND publish_jobs.status='running'
  AND publish_jobs.lease_token_hash=?8
  AND publish_jobs.lease_expires_at>?9
  AND publish_jobs.stage=?10
  AND publish_jobs.progress_seq=?11
  AND publish_jobs.progress_seq<?2
  AND EXISTS (
    SELECT 1 FROM publishing_agents AS active_agent
    WHERE active_agent.id=publish_jobs.agent_id
      AND active_agent.user_id=publish_jobs.user_id
      AND active_agent.revoked_at IS NULL
  )
`

type UpdatePublishProgressParams struct {
	NextStage      string
	NextSeq        int64
	CommittedAt    sql.NullString
	UpdatedAt      string
	ID             string
	UserID         string
	AgentID        string
	LeaseTokenHash sql.NullString
	Now            sql.NullString
	CurrentStage   string
	CurrentSeq     int64
}

func (q *Queries) UpdatePublishProgress(ctx context.Context, arg UpdatePublishProgressParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePublishProgress,
		arg.NextStage,
		arg.NextSeq,
		arg.CommittedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
		arg.AgentID,
		arg.LeaseTokenHash,
		arg.Now,
		arg.CurrentStage,
		arg.CurrentSeq,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
