// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog_models.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addCatalogModelPurpose = `-- name: AddCatalogModelPurpose :exec
INSERT OR IGNORE INTO catalog_model_purposes (model_id, purpose, created_at)
VALUES (?, ?, ?)
`

type AddCatalogModelPurposeParams struct {
	ModelID   string
	Purpose   string
	CreatedAt string
}

// Registration is idempotent per (model, purpose): re-checking an already-checked box is
// not an error, and the join row keeps its own created_at.
func (q *Queries) AddCatalogModelPurpose(ctx context.Context, arg AddCatalogModelPurposeParams) error {
	_, err := q.db.ExecContext(ctx, addCatalogModelPurpose, arg.ModelID, arg.Purpose, arg.CreatedAt)
	return err
}

const getCatalogModel = `-- name: GetCatalogModel :one
SELECT model_id, provider_slug, label, vision, structured_output, image_output, video_output,
       context_tokens, input_usd_per_million, output_usd_per_million, pricing_checked_at,
       listed, last_seen_at, created_at, updated_at
FROM catalog_models
WHERE model_id = ?
`

type GetCatalogModelRow struct {
	ModelID             string
	ProviderSlug        string
	Label               string
	Vision              int64
	StructuredOutput    int64
	ImageOutput         int64
	VideoOutput         int64
	ContextTokens       sql.NullInt64
	InputUsdPerMillion  sql.NullString
	OutputUsdPerMillion sql.NullString
	PricingCheckedAt    sql.NullString
	Listed              int64
	LastSeenAt          sql.NullString
	CreatedAt           string
	UpdatedAt           string
}

func (q *Queries) GetCatalogModel(ctx context.Context, modelID string) (GetCatalogModelRow, error) {
	row := q.db.QueryRowContext(ctx, getCatalogModel, modelID)
	var i GetCatalogModelRow
	err := row.Scan(
		&i.ModelID,
		&i.ProviderSlug,
		&i.Label,
		&i.Vision,
		&i.StructuredOutput,
		&i.ImageOutput,
		&i.VideoOutput,
		&i.ContextTokens,
		&i.InputUsdPerMillion,
		&i.OutputUsdPerMillion,
		&i.PricingCheckedAt,
		&i.Listed,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCatalogModelPurposes = `-- name: GetCatalogModelPurposes :many
SELECT purpose, reasoning_effort
FROM catalog_model_purposes
WHERE model_id = ?
ORDER BY purpose
`

type GetCatalogModelPurposesRow struct {
	Purpose         string
	ReasoningEffort sql.NullString
}

func (q *Queries) GetCatalogModelPurposes(ctx context.Context, modelID string) ([]GetCatalogModelPurposesRow, error) {
	rows, err := q.db.QueryContext(ctx, getCatalogModelPurposes, modelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCatalogModelPurposesRow
	for rows.Next() {
		var i GetCatalogModelPurposesRow
		if err := rows.Scan(&i.Purpose, &i.ReasoningEffort); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogModelPurposes = `-- name: ListCatalogModelPurposes :many
SELECT model_id, purpose, reasoning_effort
FROM catalog_model_purposes
ORDER BY model_id, purpose
`

type ListCatalogModelPurposesRow struct {
	ModelID         string
	Purpose         string
	ReasoningEffort sql.NullString
}

func (q *Queries) ListCatalogModelPurposes(ctx context.Context) ([]ListCatalogModelPurposesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCatalogModelPurposes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCatalogModelPurposesRow
	for rows.Next() {
		var i ListCatalogModelPurposesRow
		if err := rows.Scan(&i.ModelID, &i.Purpose, &i.ReasoningEffort); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogModels = `-- name: ListCatalogModels :many

SELECT model_id, provider_slug, label, vision, structured_output, image_output, video_output,
       context_tokens, input_usd_per_million, output_usd_per_million, pricing_checked_at,
       listed, last_seen_at, created_at, updated_at
FROM catalog_models
ORDER BY provider_slug, model_id
`

type ListCatalogModelsRow struct {
	ModelID             string
	ProviderSlug        string
	Label               string
	Vision              int64
	StructuredOutput    int64
	ImageOutput         int64
	VideoOutput         int64
	ContextTokens       sql.NullInt64
	InputUsdPerMillion  sql.NullString
	OutputUsdPerMillion sql.NullString
	PricingCheckedAt    sql.NullString
	Listed              int64
	LastSeenAt          sql.NullString
	CreatedAt           string
	UpdatedAt           string
}

// ASCII only: sqlc slices these statements by byte offset but counts in runes, so a
// multi-byte character anywhere above rotates every generated query text.
//
// The curated model catalog. The table is global, not per-account: what an installation
// offers is an operator decision.
//
// Two groups of columns with different owners. The curation values (the
// catalog_model_purposes rows and their reasoning_effort) are only ever written by an
// operator edit. The snapshot
// columns (label, flags, context, pricing) and the availability columns (listed,
// last_seen_at) are only ever written from a successful upstream read. updated_at tracks
// the first group alone, so a refresh does not make every row look freshly curated.
func (q *Queries) ListCatalogModels(ctx context.Context) ([]ListCatalogModelsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCatalogModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCatalogModelsRow
	for rows.Next() {
		var i ListCatalogModelsRow
		if err := rows.Scan(
			&i.ModelID,
			&i.ProviderSlug,
			&i.Label,
			&i.Vision,
			&i.StructuredOutput,
			&i.ImageOutput,
			&i.VideoOutput,
			&i.ContextTokens,
			&i.InputUsdPerMillion,
			&i.OutputUsdPerMillion,
			&i.PricingCheckedAt,
			&i.Listed,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCatalogModelSeen = `-- name: MarkCatalogModelSeen :exec
UPDATE catalog_models
SET provider_slug = ?, label = ?, vision = ?, structured_output = ?,
    image_output = ?, video_output = ?,
    context_tokens = ?, input_usd_per_million = ?, output_usd_per_million = ?,
    pricing_checked_at = ?, listed = 1, last_seen_at = ?
WHERE model_id = ?
`

type MarkCatalogModelSeenParams struct {
	ProviderSlug        string
	Label               string
	Vision              int64
	StructuredOutput    int64
	ImageOutput         int64
	VideoOutput         int64
	ContextTokens       sql.NullInt64
	InputUsdPerMillion  sql.NullString
	OutputUsdPerMillion sql.NullString
	PricingCheckedAt    sql.NullString
	LastSeenAt          sql.NullString
	ModelID             string
}

func (q *Queries) MarkCatalogModelSeen(ctx context.Context, arg MarkCatalogModelSeenParams) error {
	_, err := q.db.ExecContext(ctx, markCatalogModelSeen,
		arg.ProviderSlug,
		arg.Label,
		arg.Vision,
		arg.StructuredOutput,
		arg.ImageOutput,
		arg.VideoOutput,
		arg.ContextTokens,
		arg.InputUsdPerMillion,
		arg.OutputUsdPerMillion,
		arg.PricingCheckedAt,
		arg.LastSeenAt,
		arg.ModelID,
	)
	return err
}

const removeCatalogModelPurpose = `-- name: RemoveCatalogModelPurpose :exec
DELETE FROM catalog_model_purposes
WHERE model_id = ? AND purpose = ?
`

type RemoveCatalogModelPurposeParams struct {
	ModelID string
	Purpose string
}

func (q *Queries) RemoveCatalogModelPurpose(ctx context.Context, arg RemoveCatalogModelPurposeParams) error {
	_, err := q.db.ExecContext(ctx, removeCatalogModelPurpose, arg.ModelID, arg.Purpose)
	return err
}

const touchCatalogModelCuration = `-- name: TouchCatalogModelCuration :exec
UPDATE catalog_models
SET updated_at = ?
WHERE model_id = ?
`

type TouchCatalogModelCurationParams struct {
	UpdatedAt string
	ModelID   string
}

// A deregistration is a curation edit, so it stamps updated_at without touching the
// curation values themselves.
func (q *Queries) TouchCatalogModelCuration(ctx context.Context, arg TouchCatalogModelCurationParams) error {
	_, err := q.db.ExecContext(ctx, touchCatalogModelCuration, arg.UpdatedAt, arg.ModelID)
	return err
}

const unlistAllCatalogModels = `-- name: UnlistAllCatalogModels :exec
UPDATE catalog_models SET listed = 0
`

// Availability, step 1: assume nothing is offered any more. Step 2 puts back everything the
// provider actually listed, in the same transaction, so no reader sees the gap. updated_at
// is untouched: an availability sweep is not a curation edit.
func (q *Queries) UnlistAllCatalogModels(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, unlistAllCatalogModels)
	return err
}

const updateCatalogModelPurposeReasoning = `-- name: UpdateCatalogModelPurposeReasoning :execrows

UPDATE catalog_model_purposes
SET reasoning_effort = ?
WHERE model_id = ? AND purpose = ?
`

type UpdateCatalogModelPurposeReasoningParams struct {
	ReasoningEffort sql.NullString
	ModelID         string
	Purpose         string
}

// created_at is absent from the DO UPDATE list on purpose: the row keeps the moment it
// entered the catalog, so only the insert may set it.
// The effort is a property of the REGISTRATION, so it is written on the join row and only
// for a purpose the model actually serves: the WHERE matching zero rows IS the refusal.
func (q *Queries) UpdateCatalogModelPurposeReasoning(ctx context.Context, arg UpdateCatalogModelPurposeReasoningParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCatalogModelPurposeReasoning, arg.ReasoningEffort, arg.ModelID, arg.Purpose)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertCatalogModel = `-- name: UpsertCatalogModel :exec
INSERT INTO catalog_models (
    model_id, provider_slug, label, vision, structured_output, image_output, video_output,
    context_tokens, input_usd_per_million, output_usd_per_million, pricing_checked_at,
    listed, last_seen_at, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(model_id) DO UPDATE SET
    provider_slug = excluded.provider_slug,
    label = excluded.label,
    vision = excluded.vision,
    structured_output = excluded.structured_output,
    image_output = excluded.image_output,
    video_output = excluded.video_output,
    context_tokens = excluded.context_tokens,
    input_usd_per_million = excluded.input_usd_per_million,
    output_usd_per_million = excluded.output_usd_per_million,
    pricing_checked_at = excluded.pricing_checked_at,
    listed = excluded.listed,
    last_seen_at = excluded.last_seen_at,
    updated_at = excluded.updated_at
`

type UpsertCatalogModelParams struct {
	ModelID             string
	ProviderSlug        string
	Label               string
	Vision              int64
	StructuredOutput    int64
	ImageOutput         int64
	VideoOutput         int64
	ContextTokens       sql.NullInt64
	InputUsdPerMillion  sql.NullString
	OutputUsdPerMillion sql.NullString
	PricingCheckedAt    sql.NullString
	Listed              int64
	LastSeenAt          sql.NullString
	CreatedAt           string
	UpdatedAt           string
}

func (q *Queries) UpsertCatalogModel(ctx context.Context, arg UpsertCatalogModelParams) error {
	_, err := q.db.ExecContext(ctx, upsertCatalogModel,
		arg.ModelID,
		arg.ProviderSlug,
		arg.Label,
		arg.Vision,
		arg.StructuredOutput,
		arg.ImageOutput,
		arg.VideoOutput,
		arg.ContextTokens,
		arg.InputUsdPerMillion,
		arg.OutputUsdPerMillion,
		arg.PricingCheckedAt,
		arg.Listed,
		arg.LastSeenAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
