// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recommendation_sets.sql

package sqlc

import (
	"context"
)

const countRecommendationSets = `-- name: CountRecommendationSets :one
SELECT count(*) FROM recommendation_sets
`

func (q *Queries) CountRecommendationSets(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecommendationSets)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRecommendationSet = `-- name: DeleteRecommendationSet :execrows
DELETE FROM recommendation_sets WHERE id = ?
`

func (q *Queries) DeleteRecommendationSet(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRecommendationSet, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRecommendationSetSlots = `-- name: DeleteRecommendationSetSlots :exec
DELETE FROM recommendation_set_slots WHERE set_id = ?
`

func (q *Queries) DeleteRecommendationSetSlots(ctx context.Context, setID string) error {
	_, err := q.db.ExecContext(ctx, deleteRecommendationSetSlots, setID)
	return err
}

const insertRecommendationSet = `-- name: InsertRecommendationSet :exec
INSERT INTO recommendation_sets (id, label, position, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertRecommendationSetParams struct {
	ID        string
	Label     string
	Position  int64
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) InsertRecommendationSet(ctx context.Context, arg InsertRecommendationSetParams) error {
	_, err := q.db.ExecContext(ctx, insertRecommendationSet,
		arg.ID,
		arg.Label,
		arg.Position,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertRecommendationSetSlot = `-- name: InsertRecommendationSetSlot :exec
INSERT INTO recommendation_set_slots (set_id, stage, slot, provider_id, model_id)
VALUES (?, ?, ?, ?, ?)
`

type InsertRecommendationSetSlotParams struct {
	SetID      string
	Stage      string
	Slot       string
	ProviderID string
	ModelID    string
}

func (q *Queries) InsertRecommendationSetSlot(ctx context.Context, arg InsertRecommendationSetSlotParams) error {
	_, err := q.db.ExecContext(ctx, insertRecommendationSetSlot,
		arg.SetID,
		arg.Stage,
		arg.Slot,
		arg.ProviderID,
		arg.ModelID,
	)
	return err
}

const listRecommendationSetSlots = `-- name: ListRecommendationSetSlots :many
SELECT set_id, stage, slot, provider_id, model_id
FROM recommendation_set_slots
ORDER BY set_id, stage, slot
`

func (q *Queries) ListRecommendationSetSlots(ctx context.Context) ([]RecommendationSetSlot, error) {
	rows, err := q.db.QueryContext(ctx, listRecommendationSetSlots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecommendationSetSlot
	for rows.Next() {
		var i RecommendationSetSlot
		if err := rows.Scan(
			&i.SetID,
			&i.Stage,
			&i.Slot,
			&i.ProviderID,
			&i.ModelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecommendationSets = `-- name: ListRecommendationSets :many

SELECT id, label, position
FROM recommendation_sets
ORDER BY position, created_at, id
`

type ListRecommendationSetsRow struct {
	ID       string
	Label    string
	Position int64
}

// Queries for the provider context's recommendation sets (MODEL-69). ASCII only: sqlc
// rewrites named parameters by byte offset, so a multi-byte comment breaks the whole file.
func (q *Queries) ListRecommendationSets(ctx context.Context) ([]ListRecommendationSetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecommendationSets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecommendationSetsRow
	for rows.Next() {
		var i ListRecommendationSetsRow
		if err := rows.Scan(&i.ID, &i.Label, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextRecommendationSetPosition = `-- name: NextRecommendationSetPosition :one
SELECT CAST(COALESCE(MAX(position), 0) + 1 AS INTEGER) FROM recommendation_sets
`

func (q *Queries) NextRecommendationSetPosition(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextRecommendationSetPosition)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const setRecommendationSetPosition = `-- name: SetRecommendationSetPosition :exec
UPDATE recommendation_sets SET position = ? WHERE id = ?
`

type SetRecommendationSetPositionParams struct {
	Position int64
	ID       string
}

func (q *Queries) SetRecommendationSetPosition(ctx context.Context, arg SetRecommendationSetPositionParams) error {
	_, err := q.db.ExecContext(ctx, setRecommendationSetPosition, arg.Position, arg.ID)
	return err
}

const updateRecommendationSetLabel = `-- name: UpdateRecommendationSetLabel :execrows
UPDATE recommendation_sets SET label = ?, updated_at = ? WHERE id = ?
`

type UpdateRecommendationSetLabelParams struct {
	Label     string
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateRecommendationSetLabel(ctx context.Context, arg UpdateRecommendationSetLabelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRecommendationSetLabel, arg.Label, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
