// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: selections.sql

package sqlc

import (
	"context"
)

const deleteLabExtraSlots = `-- name: DeleteLabExtraSlots :exec
DELETE FROM model_selections
WHERE user_id = ? AND stage = ? AND slot IN ('candidate_c', 'candidate_d', 'candidate_e')
`

type DeleteLabExtraSlotsParams struct {
	UserID string
	Stage  string
}

func (q *Queries) DeleteLabExtraSlots(ctx context.Context, arg DeleteLabExtraSlotsParams) error {
	_, err := q.db.ExecContext(ctx, deleteLabExtraSlots, arg.UserID, arg.Stage)
	return err
}

const deleteSelectionIfRef = `-- name: DeleteSelectionIfRef :exec
DELETE FROM model_selections
WHERE user_id = ? AND stage = ? AND slot = ? AND provider_id = ? AND model_id = ?
`

type DeleteSelectionIfRefParams struct {
	UserID     string
	Stage      string
	Slot       string
	ProviderID string
	ModelID    string
}

// Conditional on the ref: the clear of a vanished choice must not take a choice the
// user made in the meantime.
func (q *Queries) DeleteSelectionIfRef(ctx context.Context, arg DeleteSelectionIfRefParams) error {
	_, err := q.db.ExecContext(ctx, deleteSelectionIfRef,
		arg.UserID,
		arg.Stage,
		arg.Slot,
		arg.ProviderID,
		arg.ModelID,
	)
	return err
}

const insertDefaultSelection = `-- name: InsertDefaultSelection :exec
INSERT INTO model_selections (user_id, stage, slot, provider_id, model_id, updated_at)
VALUES (?, ?, 'active', ?, ?, ?)
ON CONFLICT(user_id, stage, slot) DO NOTHING
`

type InsertDefaultSelectionParams struct {
	UserID     string
	Stage      string
	ProviderID string
	ModelID    string
	UpdatedAt  string
}

// Defaults fill only absent active choices. A simultaneous manual save always wins,
// regardless of whether it happens before or after this insert.
func (q *Queries) InsertDefaultSelection(ctx context.Context, arg InsertDefaultSelectionParams) error {
	_, err := q.db.ExecContext(ctx, insertDefaultSelection,
		arg.UserID,
		arg.Stage,
		arg.ProviderID,
		arg.ModelID,
		arg.UpdatedAt,
	)
	return err
}

const listPairSlotsForExtraSave = `-- name: ListPairSlotsForExtraSave :many
SELECT slot, provider_id, model_id FROM model_selections
WHERE user_id = ? AND stage = ? AND slot IN ('candidate_a', 'candidate_b')
`

type ListPairSlotsForExtraSaveParams struct {
	UserID string
	Stage  string
}

type ListPairSlotsForExtraSaveRow struct {
	Slot       string
	ProviderID string
	ModelID    string
}

func (q *Queries) ListPairSlotsForExtraSave(ctx context.Context, arg ListPairSlotsForExtraSaveParams) ([]ListPairSlotsForExtraSaveRow, error) {
	rows, err := q.db.QueryContext(ctx, listPairSlotsForExtraSave, arg.UserID, arg.Stage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPairSlotsForExtraSaveRow
	for rows.Next() {
		var i ListPairSlotsForExtraSaveRow
		if err := rows.Scan(&i.Slot, &i.ProviderID, &i.ModelID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSelectionSlots = `-- name: ListSelectionSlots :many
SELECT user_id, stage, slot, provider_id, model_id, updated_at
FROM model_selections
WHERE user_id = ?
ORDER BY stage, slot
`

func (q *Queries) ListSelectionSlots(ctx context.Context, userID string) ([]ModelSelection, error) {
	rows, err := q.db.QueryContext(ctx, listSelectionSlots, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelSelection
	for rows.Next() {
		var i ModelSelection
		if err := rows.Scan(
			&i.UserID,
			&i.Stage,
			&i.Slot,
			&i.ProviderID,
			&i.ModelID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSelections = `-- name: ListSelections :many
SELECT user_id, stage, provider_id, model_id, updated_at
FROM model_selections
WHERE user_id = ? AND slot = 'active'
ORDER BY stage
`

type ListSelectionsRow struct {
	UserID     string
	Stage      string
	ProviderID string
	ModelID    string
	UpdatedAt  string
}

func (q *Queries) ListSelections(ctx context.Context, userID string) ([]ListSelectionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSelections, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSelectionsRow
	for rows.Next() {
		var i ListSelectionsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Stage,
			&i.ProviderID,
			&i.ModelID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSelection = `-- name: UpsertSelection :exec

INSERT INTO model_selections (user_id, stage, slot, provider_id, model_id, updated_at)
VALUES (?, ?, 'active', ?, ?, ?)
ON CONFLICT(user_id, stage, slot) DO UPDATE SET
    provider_id = excluded.provider_id,
    model_id    = excluded.model_id,
    updated_at  = excluded.updated_at
`

type UpsertSelectionParams struct {
	UserID     string
	Stage      string
	ProviderID string
	ModelID    string
	UpdatedAt  string
}

// Queries for the provider context (model_selections). sqlc compiles these into
// internal/provider/store/sqlc; internal/provider/store maps the rows to domain types.
func (q *Queries) UpsertSelection(ctx context.Context, arg UpsertSelectionParams) error {
	_, err := q.db.ExecContext(ctx, upsertSelection,
		arg.UserID,
		arg.Stage,
		arg.ProviderID,
		arg.ModelID,
		arg.UpdatedAt,
	)
	return err
}

const upsertSelectionSlot = `-- name: UpsertSelectionSlot :exec
INSERT INTO model_selections (user_id, stage, slot, provider_id, model_id, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(user_id, stage, slot) DO UPDATE SET
    provider_id = excluded.provider_id,
    model_id    = excluded.model_id,
    updated_at  = excluded.updated_at
`

type UpsertSelectionSlotParams struct {
	UserID     string
	Stage      string
	Slot       string
	ProviderID string
	ModelID    string
	UpdatedAt  string
}

func (q *Queries) UpsertSelectionSlot(ctx context.Context, arg UpsertSelectionSlotParams) error {
	_, err := q.db.ExecContext(ctx, upsertSelectionSlot,
		arg.UserID,
		arg.Stage,
		arg.Slot,
		arg.ProviderID,
		arg.ModelID,
		arg.UpdatedAt,
	)
	return err
}
