// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: test_publications.sql

package sqlc

import (
	"context"
)

const getTestModelPublication = `-- name: GetTestModelPublication :one
SELECT test_id,winner_candidate_id,request_key,fingerprint,stage,model_ref,receipt
FROM provider_test_publications
WHERE user_id=? AND ((test_id=? AND winner_candidate_id=? AND action='adopt_model') OR request_key=?)
`

type GetTestModelPublicationParams struct {
	UserID            string
	TestID            string
	WinnerCandidateID string
	RequestKey        string
}

type GetTestModelPublicationRow struct {
	TestID            string
	WinnerCandidateID string
	RequestKey        string
	Fingerprint       string
	Stage             string
	ModelRef          string
	Receipt           string
}

func (q *Queries) GetTestModelPublication(ctx context.Context, arg GetTestModelPublicationParams) (GetTestModelPublicationRow, error) {
	row := q.db.QueryRowContext(ctx, getTestModelPublication,
		arg.UserID,
		arg.TestID,
		arg.WinnerCandidateID,
		arg.RequestKey,
	)
	var i GetTestModelPublicationRow
	err := row.Scan(
		&i.TestID,
		&i.WinnerCandidateID,
		&i.RequestKey,
		&i.Fingerprint,
		&i.Stage,
		&i.ModelRef,
		&i.Receipt,
	)
	return i, err
}

const insertTestModelPublication = `-- name: InsertTestModelPublication :exec
INSERT INTO provider_test_publications(user_id,test_id,winner_candidate_id,action,request_key,fingerprint,stage,model_ref,receipt,created_at)
VALUES(?,?,?,'adopt_model',?,?,?,?,?,?)
`

type InsertTestModelPublicationParams struct {
	UserID            string
	TestID            string
	WinnerCandidateID string
	RequestKey        string
	Fingerprint       string
	Stage             string
	ModelRef          string
	Receipt           string
	CreatedAt         string
}

func (q *Queries) InsertTestModelPublication(ctx context.Context, arg InsertTestModelPublicationParams) error {
	_, err := q.db.ExecContext(ctx, insertTestModelPublication,
		arg.UserID,
		arg.TestID,
		arg.WinnerCandidateID,
		arg.RequestKey,
		arg.Fingerprint,
		arg.Stage,
		arg.ModelRef,
		arg.Receipt,
		arg.CreatedAt,
	)
	return err
}

const lockTestModelPublication = `-- name: LockTestModelPublication :exec
UPDATE model_selections SET updated_at=updated_at WHERE 0
`

func (q *Queries) LockTestModelPublication(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, lockTestModelPublication)
	return err
}
