// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: images.sql

package sqlc

import (
	"context"
)

const createImage = `-- name: CreateImage :exec

INSERT INTO images (id, post_slug, filename, r2_key, width, height, bytes, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateImageParams struct {
	ID        string
	PostSlug  string
	Filename  string
	R2Key     string
	Width     int64
	Height    int64
	Bytes     int64
	CreatedAt string
}

// Photos attached to a post. The row is created only after the object is known to
// exist in storage.
func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) error {
	_, err := q.db.ExecContext(ctx, createImage,
		arg.ID,
		arg.PostSlug,
		arg.Filename,
		arg.R2Key,
		arg.Width,
		arg.Height,
		arg.Bytes,
		arg.CreatedAt,
	)
	return err
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM images WHERE id = ?
`

func (q *Queries) DeleteImage(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteImage, id)
	return err
}

const getImage = `-- name: GetImage :one
SELECT id, post_slug, filename, r2_key, width, height, bytes, created_at
FROM images WHERE id = ?
`

func (q *Queries) GetImage(ctx context.Context, id string) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImage, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.PostSlug,
		&i.Filename,
		&i.R2Key,
		&i.Width,
		&i.Height,
		&i.Bytes,
		&i.CreatedAt,
	)
	return i, err
}

const imageFilenameTaken = `-- name: ImageFilenameTaken :one
SELECT EXISTS (SELECT 1 FROM images WHERE post_slug = ? AND filename = ?)
`

type ImageFilenameTakenParams struct {
	PostSlug string
	Filename string
}

func (q *Queries) ImageFilenameTaken(ctx context.Context, arg ImageFilenameTakenParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, imageFilenameTaken, arg.PostSlug, arg.Filename)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const imageKeyInUse = `-- name: ImageKeyInUse :one
SELECT EXISTS (SELECT 1 FROM images WHERE r2_key = ?)
`

func (q *Queries) ImageKeyInUse(ctx context.Context, r2Key string) (bool, error) {
	row := q.db.QueryRowContext(ctx, imageKeyInUse, r2Key)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAllImageKeys = `-- name: ListAllImageKeys :many
SELECT r2_key FROM images
`

func (q *Queries) ListAllImageKeys(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAllImageKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var r2_key string
		if err := rows.Scan(&r2_key); err != nil {
			return nil, err
		}
		items = append(items, r2_key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesByPost = `-- name: ListImagesByPost :many
SELECT id, post_slug, filename, r2_key, width, height, bytes, created_at
FROM images WHERE post_slug = ? ORDER BY created_at, id
`

func (q *Queries) ListImagesByPost(ctx context.Context, postSlug string) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImagesByPost, postSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.PostSlug,
			&i.Filename,
			&i.R2Key,
			&i.Width,
			&i.Height,
			&i.Bytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
