// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type Image struct {
	ID              string
	PostSlug        string
	Filename        string
	R2Key           string
	Width           int64
	Height          int64
	Bytes           int64
	CreatedAt       string
	Rotation        int64
	RotationByOwner int64
}

type Post struct {
	Slug                    string
	UserID                  string
	VoiceID                 sql.NullString
	Title                   string
	Memo                    string
	Observations            sql.NullString
	Content                 sql.NullString
	Status                  string
	CreatedAt               string
	UpdatedAt               string
	ContentRevision         int64
	MachineBaseline         sql.NullString
	MachineBaselineRevision int64
	TargetLength            sql.NullInt64
	FinalizedRevision       sql.NullInt64
	FinalizedAt             sql.NullString
	TemplateID              sql.NullString
	TargetLanguage          string
	ContentLanguage         sql.NullString
	TagCount                sql.NullInt64
	UseMemory               int64
	PublishedUrl            sql.NullString
	PublishedAt             sql.NullString
	Field                   sql.NullString
	ContentNouns            sql.NullString
	QualityRules            sql.NullString
	Storyline               sql.NullString
	InputRevision           int64
}

type Upload struct {
	ID          string
	PostSlug    string
	Filename    string
	R2Key       string
	ExpiresAt   string
	CreatedAt   string
	Kind        string
	ContentType string
}

type Video struct {
	ID          string
	PostSlug    string
	Filename    string
	R2Key       string
	ContentType string
	Bytes       int64
	DurationMs  int64
	Width       int64
	Height      int64
	CreatedAt   string
}
