// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type Image struct {
	ID        string
	PostSlug  string
	Filename  string
	R2Key     string
	Width     int64
	Height    int64
	Bytes     int64
	CreatedAt string
}

type Post struct {
	Slug         string
	UserID       string
	Title        string
	Memo         string
	Observations sql.NullString
	Content      sql.NullString
	Status       string
	CreatedAt    string
	UpdatedAt    string
}

type Upload struct {
	ID        string
	PostSlug  string
	Filename  string
	R2Key     string
	ExpiresAt string
	CreatedAt string
}
