// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package sqlc

import (
	"context"
	"database/sql"
)

const assignPostTemplate = `-- name: AssignPostTemplate :execrows
UPDATE posts SET template_id = ?, updated_at = ?
WHERE slug = ? AND user_id = ?
`

type AssignPostTemplateParams struct {
	TemplateID sql.NullString
	UpdatedAt  string
	Slug       string
	UserID     string
}

// Assignment is not a reassignment: unlike the voice, a template is never learned from, so
// this touches no content, revision, machine baseline or finalization column and is allowed
// in every status. NULL is the clear.
func (q *Queries) AssignPostTemplate(ctx context.Context, arg AssignPostTemplateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, assignPostTemplate,
		arg.TemplateID,
		arg.UpdatedAt,
		arg.Slug,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countPostsByVoice = `-- name: CountPostsByVoice :one
SELECT count(*) FROM posts WHERE voice_id = ? AND user_id = ?
`

type CountPostsByVoiceParams struct {
	VoiceID string
	UserID  string
}

func (q *Queries) CountPostsByVoice(ctx context.Context, arg CountPostsByVoiceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPostsByVoice, arg.VoiceID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPost = `-- name: CreatePost :exec

INSERT INTO posts (slug, user_id, voice_id, template_id, title, memo, target_language, status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, 'draft', ?, ?)
`

type CreatePostParams struct {
	Slug           string
	UserID         string
	VoiceID        string
	TemplateID     sql.NullString
	Title          string
	Memo           string
	TargetLanguage string
	CreatedAt      string
	UpdatedAt      string
}

// Posts. Every query is scoped by user_id: ownership is enforced in SQL, not by a
// caller remembering to check it.
func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.ExecContext(ctx, createPost,
		arg.Slug,
		arg.UserID,
		arg.VoiceID,
		arg.TemplateID,
		arg.Title,
		arg.Memo,
		arg.TargetLanguage,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deletePost = `-- name: DeletePost :execrows
DELETE FROM posts WHERE slug = ? AND user_id = ?
`

type DeletePostParams struct {
	Slug   string
	UserID string
}

func (q *Queries) DeletePost(ctx context.Context, arg DeletePostParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePost, arg.Slug, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finalizePost = `-- name: FinalizePost :execrows
UPDATE posts SET status = 'finalized', finalized_revision = content_revision,
    title = ?, finalized_at = ?, updated_at = ?
WHERE slug = ? AND user_id = ? AND content_revision = ?
  AND content IS NOT NULL
`

type FinalizePostParams struct {
	Title           string
	FinalizedAt     sql.NullString
	UpdatedAt       string
	Slug            string
	UserID          string
	ContentRevision int64
}

// Finalizing also copies the confirmed AI title into posts.title (spec/policy/posts.md). ONE
// statement, still guarded by the exact revision, so the copy is atomic with the finalization and
// a concurrent content save simply matches zero rows. The caller resolves which title to write: an
// empty content title leaves the user's working title in place. The slug is never re-minted.
func (q *Queries) FinalizePost(ctx context.Context, arg FinalizePostParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finalizePost,
		arg.Title,
		arg.FinalizedAt,
		arg.UpdatedAt,
		arg.Slug,
		arg.UserID,
		arg.ContentRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLearningSnapshot = `-- name: GetLearningSnapshot :one
SELECT slug, user_id, voice_id, content, content_revision, machine_baseline, machine_baseline_revision,
       machine_baseline_voice_id, target_length, status, finalized_revision, finalized_at, updated_at,
       target_language, content_language
FROM posts WHERE slug = ? AND user_id = ?
`

type GetLearningSnapshotParams struct {
	Slug   string
	UserID string
}

type GetLearningSnapshotRow struct {
	Slug                    string
	UserID                  string
	VoiceID                 string
	Content                 sql.NullString
	ContentRevision         int64
	MachineBaseline         sql.NullString
	MachineBaselineRevision int64
	MachineBaselineVoiceID  sql.NullString
	TargetLength            sql.NullInt64
	Status                  string
	FinalizedRevision       sql.NullInt64
	FinalizedAt             sql.NullString
	UpdatedAt               string
	TargetLanguage          string
	ContentLanguage         sql.NullString
}

func (q *Queries) GetLearningSnapshot(ctx context.Context, arg GetLearningSnapshotParams) (GetLearningSnapshotRow, error) {
	row := q.db.QueryRowContext(ctx, getLearningSnapshot, arg.Slug, arg.UserID)
	var i GetLearningSnapshotRow
	err := row.Scan(
		&i.Slug,
		&i.UserID,
		&i.VoiceID,
		&i.Content,
		&i.ContentRevision,
		&i.MachineBaseline,
		&i.MachineBaselineRevision,
		&i.MachineBaselineVoiceID,
		&i.TargetLength,
		&i.Status,
		&i.FinalizedRevision,
		&i.FinalizedAt,
		&i.UpdatedAt,
		&i.TargetLanguage,
		&i.ContentLanguage,
	)
	return i, err
}

const getPost = `-- name: GetPost :one
SELECT slug, user_id, voice_id, title, memo, observations, content, status, created_at, updated_at,
       content_revision, machine_baseline, machine_baseline_revision, machine_baseline_voice_id,
       target_length, finalized_revision, finalized_at, template_id, target_language, content_language
FROM posts WHERE slug = ?
`

func (q *Queries) GetPost(ctx context.Context, slug string) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPost, slug)
	var i Post
	err := row.Scan(
		&i.Slug,
		&i.UserID,
		&i.VoiceID,
		&i.Title,
		&i.Memo,
		&i.Observations,
		&i.Content,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentRevision,
		&i.MachineBaseline,
		&i.MachineBaselineRevision,
		&i.MachineBaselineVoiceID,
		&i.TargetLength,
		&i.FinalizedRevision,
		&i.FinalizedAt,
		&i.TemplateID,
		&i.TargetLanguage,
		&i.ContentLanguage,
	)
	return i, err
}

const listPostsByUser = `-- name: ListPostsByUser :many
SELECT slug, title, content, status, updated_at, voice_id, template_id, target_language, content_language
FROM posts WHERE user_id = ? ORDER BY updated_at DESC, slug DESC
`

type ListPostsByUserRow struct {
	Slug            string
	Title           string
	Content         sql.NullString
	Status          string
	UpdatedAt       string
	VoiceID         string
	TemplateID      sql.NullString
	TargetLanguage  string
	ContentLanguage sql.NullString
}

func (q *Queries) ListPostsByUser(ctx context.Context, userID string) ([]ListPostsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listPostsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsByUserRow
	for rows.Next() {
		var i ListPostsByUserRow
		if err := rows.Scan(
			&i.Slug,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.UpdatedAt,
			&i.VoiceID,
			&i.TemplateID,
			&i.TargetLanguage,
			&i.ContentLanguage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const postSlugExists = `-- name: PostSlugExists :one
SELECT EXISTS (SELECT 1 FROM posts WHERE slug = ?)
`

func (q *Queries) PostSlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRowContext(ctx, postSlugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const reassignPostVoice = `-- name: ReassignPostVoice :execrows
UPDATE posts SET voice_id = ?, machine_baseline = NULL, machine_baseline_revision = 0,
    machine_baseline_voice_id = NULL,
    updated_at = ?
WHERE slug = ? AND user_id = ? AND voice_id <> ?
`

type ReassignPostVoiceParams struct {
	VoiceID   string
	UpdatedAt string
	Slug      string
	UserID    string
	VoiceID_2 string
}

// The reassignment keeps every byte of the post and drops only what belonged to the old
// voice: the machine baseline, and with it the eligibility to learn from this post until a
// fresh machine result is written under the new voice.
func (q *Queries) ReassignPostVoice(ctx context.Context, arg ReassignPostVoiceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reassignPostVoice,
		arg.VoiceID,
		arg.UpdatedAt,
		arg.Slug,
		arg.UserID,
		arg.VoiceID_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const savePostContent = `-- name: SavePostContent :execrows
UPDATE posts SET content = ?, content_revision = content_revision + 1,
    status = 'review', finalized_revision = NULL, finalized_at = NULL, updated_at = ?
WHERE slug = ? AND user_id = ? AND content_revision = ?
`

type SavePostContentParams struct {
	Content         sql.NullString
	UpdatedAt       string
	Slug            string
	UserID          string
	ContentRevision int64
}

func (q *Queries) SavePostContent(ctx context.Context, arg SavePostContentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, savePostContent,
		arg.Content,
		arg.UpdatedAt,
		arg.Slug,
		arg.UserID,
		arg.ContentRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const savePostGenerationOptions = `-- name: SavePostGenerationOptions :execrows
UPDATE posts SET target_length = ?, updated_at = ?
WHERE slug = ? AND user_id = ?
`

type SavePostGenerationOptionsParams struct {
	TargetLength sql.NullInt64
	UpdatedAt    string
	Slug         string
	UserID       string
}

func (q *Queries) SavePostGenerationOptions(ctx context.Context, arg SavePostGenerationOptionsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, savePostGenerationOptions,
		arg.TargetLength,
		arg.UpdatedAt,
		arg.Slug,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateGeneratedContent = `-- name: UpdateGeneratedContent :execrows
UPDATE posts SET content = ?1, machine_baseline = ?2, machine_baseline_voice_id = voice_id,
    content_language = ?3,
    content_revision = content_revision + 1,
    machine_baseline_revision = content_revision + 1,
    status = 'review', finalized_revision = NULL, finalized_at = NULL, updated_at = ?4
WHERE slug = ?5 AND user_id = ?6
  AND (content IS NULL OR content <> ?1 OR status <> 'review'
       OR machine_baseline_revision <> content_revision
       OR content_language IS NULL OR content_language <> ?3)
`

type UpdateGeneratedContentParams struct {
	Content         sql.NullString
	MachineBaseline sql.NullString
	ContentLanguage sql.NullString
	UpdatedAt       string
	Slug            string
	UserID          string
}

func (q *Queries) UpdateGeneratedContent(ctx context.Context, arg UpdateGeneratedContentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateGeneratedContent,
		arg.Content,
		arg.MachineBaseline,
		arg.ContentLanguage,
		arg.UpdatedAt,
		arg.Slug,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePostDraft = `-- name: UpdatePostDraft :execrows
UPDATE posts SET title = ?1, memo = ?2,
    target_language = COALESCE(?3, target_language),
    updated_at = ?4
WHERE slug = ?5 AND user_id = ?6
`

type UpdatePostDraftParams struct {
	Title          string
	Memo           string
	TargetLanguage sql.NullString
	UpdatedAt      string
	Slug           string
	UserID         string
}

func (q *Queries) UpdatePostDraft(ctx context.Context, arg UpdatePostDraftParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePostDraft,
		arg.Title,
		arg.Memo,
		arg.TargetLanguage,
		arg.UpdatedAt,
		arg.Slug,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePostObservations = `-- name: UpdatePostObservations :execrows
UPDATE posts SET observations = ?, updated_at = ?
WHERE slug = ? AND user_id = ?
`

type UpdatePostObservationsParams struct {
	Observations sql.NullString
	UpdatedAt    string
	Slug         string
	UserID       string
}

func (q *Queries) UpdatePostObservations(ctx context.Context, arg UpdatePostObservationsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePostObservations,
		arg.Observations,
		arg.UpdatedAt,
		arg.Slug,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
