// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package sqlc

import (
	"context"
)

const createPost = `-- name: CreatePost :exec

INSERT INTO posts (slug, user_id, title, memo, status, created_at, updated_at)
VALUES (?, ?, ?, ?, 'draft', ?, ?)
`

type CreatePostParams struct {
	Slug      string
	UserID    string
	Title     string
	Memo      string
	CreatedAt string
	UpdatedAt string
}

// Posts. Every query is scoped by user_id: ownership is enforced in SQL, not by a
// caller remembering to check it.
func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.ExecContext(ctx, createPost,
		arg.Slug,
		arg.UserID,
		arg.Title,
		arg.Memo,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getPost = `-- name: GetPost :one
SELECT slug, user_id, title, memo, observations, content, status, created_at, updated_at
FROM posts WHERE slug = ?
`

func (q *Queries) GetPost(ctx context.Context, slug string) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPost, slug)
	var i Post
	err := row.Scan(
		&i.Slug,
		&i.UserID,
		&i.Title,
		&i.Memo,
		&i.Observations,
		&i.Content,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPostsByUser = `-- name: ListPostsByUser :many
SELECT slug, title, status, updated_at
FROM posts WHERE user_id = ? ORDER BY updated_at DESC, slug DESC
`

type ListPostsByUserRow struct {
	Slug      string
	Title     string
	Status    string
	UpdatedAt string
}

func (q *Queries) ListPostsByUser(ctx context.Context, userID string) ([]ListPostsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listPostsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsByUserRow
	for rows.Next() {
		var i ListPostsByUserRow
		if err := rows.Scan(
			&i.Slug,
			&i.Title,
			&i.Status,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const postSlugExists = `-- name: PostSlugExists :one
SELECT EXISTS (SELECT 1 FROM posts WHERE slug = ?)
`

func (q *Queries) PostSlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRowContext(ctx, postSlugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updatePostDraft = `-- name: UpdatePostDraft :execrows
UPDATE posts SET title = ?, memo = ?, updated_at = ?
WHERE slug = ? AND user_id = ?
`

type UpdatePostDraftParams struct {
	Title     string
	Memo      string
	UpdatedAt string
	Slug      string
	UserID    string
}

func (q *Queries) UpdatePostDraft(ctx context.Context, arg UpdatePostDraftParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePostDraft,
		arg.Title,
		arg.Memo,
		arg.UpdatedAt,
		arg.Slug,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
