// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: request_captures.sql

package sqlc

import (
	"context"
	"database/sql"
)

const bindPostRequestCapture = `-- name: BindPostRequestCapture :execrows
UPDATE post_request_captures SET result_revision = ?1,
 result_hash = ?2, plan_fingerprint = ?3
WHERE post_slug = ?4 AND user_id = ?5 AND job_id = ?6
 AND content_revision = ?7 AND source_fingerprint = ?8
`

type BindPostRequestCaptureParams struct {
	ResultRevision    sql.NullInt64
	ResultHash        sql.NullString
	PlanFingerprint   sql.NullString
	PostSlug          string
	UserID            string
	JobID             string
	ContentRevision   int64
	SourceFingerprint string
}

func (q *Queries) BindPostRequestCapture(ctx context.Context, arg BindPostRequestCaptureParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, bindPostRequestCapture,
		arg.ResultRevision,
		arg.ResultHash,
		arg.PlanFingerprint,
		arg.PostSlug,
		arg.UserID,
		arg.JobID,
		arg.ContentRevision,
		arg.SourceFingerprint,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteOtherPostStageCaptures = `-- name: DeleteOtherPostStageCaptures :exec
DELETE FROM post_request_captures WHERE post_slug = ? AND stage = ? AND job_id <> ?
`

type DeleteOtherPostStageCapturesParams struct {
	PostSlug string
	Stage    string
	JobID    string
}

func (q *Queries) DeleteOtherPostStageCaptures(ctx context.Context, arg DeleteOtherPostStageCapturesParams) error {
	_, err := q.db.ExecContext(ctx, deleteOtherPostStageCaptures, arg.PostSlug, arg.Stage, arg.JobID)
	return err
}

const deletePostStageCaptures = `-- name: DeletePostStageCaptures :exec
DELETE FROM post_request_captures WHERE post_slug = ? AND user_id = ? AND stage = ?
`

type DeletePostStageCapturesParams struct {
	PostSlug string
	UserID   string
	Stage    string
}

func (q *Queries) DeletePostStageCaptures(ctx context.Context, arg DeletePostStageCapturesParams) error {
	_, err := q.db.ExecContext(ctx, deletePostStageCaptures, arg.PostSlug, arg.UserID, arg.Stage)
	return err
}

const fencePostRequestCapturePurge = `-- name: FencePostRequestCapturePurge :exec
INSERT INTO post_request_capture_purges(post_slug, user_id, job_id)
SELECT c.post_slug, c.user_id, c.job_id FROM post_request_captures c WHERE c.post_slug = ? AND c.user_id = ?
ON CONFLICT(post_slug, job_id) DO NOTHING
`

type FencePostRequestCapturePurgeParams struct {
	PostSlug string
	UserID   string
}

func (q *Queries) FencePostRequestCapturePurge(ctx context.Context, arg FencePostRequestCapturePurgeParams) error {
	_, err := q.db.ExecContext(ctx, fencePostRequestCapturePurge, arg.PostSlug, arg.UserID)
	return err
}

const listPostRequestCaptures = `-- name: ListPostRequestCaptures :many
SELECT post_slug, user_id, job_id, call_id, call_sequence, attachment_id, stage, input_revision, content_revision, source_fingerprint, source_plan_fingerprint, result_revision, result_hash, plan_fingerprint, payload FROM post_request_captures WHERE post_slug = ? AND user_id = ? AND stage = ? ORDER BY call_sequence, call_id
`

type ListPostRequestCapturesParams struct {
	PostSlug string
	UserID   string
	Stage    string
}

func (q *Queries) ListPostRequestCaptures(ctx context.Context, arg ListPostRequestCapturesParams) ([]PostRequestCapture, error) {
	rows, err := q.db.QueryContext(ctx, listPostRequestCaptures, arg.PostSlug, arg.UserID, arg.Stage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostRequestCapture
	for rows.Next() {
		var i PostRequestCapture
		if err := rows.Scan(
			&i.PostSlug,
			&i.UserID,
			&i.JobID,
			&i.CallID,
			&i.CallSequence,
			&i.AttachmentID,
			&i.Stage,
			&i.InputRevision,
			&i.ContentRevision,
			&i.SourceFingerprint,
			&i.SourcePlanFingerprint,
			&i.ResultRevision,
			&i.ResultHash,
			&i.PlanFingerprint,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const postRequestCapturePurged = `-- name: PostRequestCapturePurged :one
SELECT EXISTS(SELECT 1 FROM post_request_capture_purges WHERE post_slug = ? AND user_id = ? AND job_id = ?)
`

type PostRequestCapturePurgedParams struct {
	PostSlug string
	UserID   string
	JobID    string
}

func (q *Queries) PostRequestCapturePurged(ctx context.Context, arg PostRequestCapturePurgedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, postRequestCapturePurged, arg.PostSlug, arg.UserID, arg.JobID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const purgePostRequestCaptures = `-- name: PurgePostRequestCaptures :exec
DELETE FROM post_request_captures WHERE post_slug = ? AND user_id = ?
`

type PurgePostRequestCapturesParams struct {
	PostSlug string
	UserID   string
}

func (q *Queries) PurgePostRequestCaptures(ctx context.Context, arg PurgePostRequestCapturesParams) error {
	_, err := q.db.ExecContext(ctx, purgePostRequestCaptures, arg.PostSlug, arg.UserID)
	return err
}

const purgeWithdrawnPostRequestCaptures = `-- name: PurgeWithdrawnPostRequestCaptures :exec
DELETE FROM post_request_captures WHERE post_slug = ?
`

func (q *Queries) PurgeWithdrawnPostRequestCaptures(ctx context.Context, postSlug string) error {
	_, err := q.db.ExecContext(ctx, purgeWithdrawnPostRequestCaptures, postSlug)
	return err
}

const writePostRequestCapture = `-- name: WritePostRequestCapture :exec
INSERT INTO post_request_captures (
 post_slug, user_id, job_id, call_id, call_sequence, attachment_id, stage,
 input_revision, content_revision, source_fingerprint, source_plan_fingerprint, payload
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(post_slug, job_id, call_id) DO NOTHING
`

type WritePostRequestCaptureParams struct {
	PostSlug              string
	UserID                string
	JobID                 string
	CallID                string
	CallSequence          int64
	AttachmentID          string
	Stage                 string
	InputRevision         int64
	ContentRevision       int64
	SourceFingerprint     string
	SourcePlanFingerprint string
	Payload               string
}

func (q *Queries) WritePostRequestCapture(ctx context.Context, arg WritePostRequestCaptureParams) error {
	_, err := q.db.ExecContext(ctx, writePostRequestCapture,
		arg.PostSlug,
		arg.UserID,
		arg.JobID,
		arg.CallID,
		arg.CallSequence,
		arg.AttachmentID,
		arg.Stage,
		arg.InputRevision,
		arg.ContentRevision,
		arg.SourceFingerprint,
		arg.SourcePlanFingerprint,
		arg.Payload,
	)
	return err
}
