// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: test_publications.sql

package sqlc

import (
	"context"
	"database/sql"
)

const applyPostTestOutput = `-- name: ApplyPostTestOutput :execrows
UPDATE posts SET content_origins = ?1,
    content = ?2, machine_baseline = ?3,
    content_language = ?4, content_nouns = ?5,
    storyline = ?6, storyline_origins = ?7,
    input_revision = input_revision + CASE WHEN storyline IS NOT ?6 THEN 1 ELSE 0 END,
    content_revision = content_revision + 1, machine_baseline_revision = content_revision + 1,
    status = 'review', finalized_revision = NULL, finalized_at = NULL, updated_at = ?8
WHERE slug = ?9 AND user_id = ?10
  AND input_revision = ?11
  AND content_revision = ?12
  AND status IN ('draft', 'review') AND status <> 'published'
`

type ApplyPostTestOutputParams struct {
	ContentOrigins          sql.NullString
	Content                 sql.NullString
	MachineBaseline         sql.NullString
	ContentLanguage         sql.NullString
	ContentNouns            sql.NullString
	Storyline               sql.NullString
	StorylineOrigins        sql.NullString
	UpdatedAt               string
	Slug                    string
	UserID                  string
	ExpectedInputRevision   int64
	ExpectedContentRevision int64
}

func (q *Queries) ApplyPostTestOutput(ctx context.Context, arg ApplyPostTestOutputParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, applyPostTestOutput,
		arg.ContentOrigins,
		arg.Content,
		arg.MachineBaseline,
		arg.ContentLanguage,
		arg.ContentNouns,
		arg.Storyline,
		arg.StorylineOrigins,
		arg.UpdatedAt,
		arg.Slug,
		arg.UserID,
		arg.ExpectedInputRevision,
		arg.ExpectedContentRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createPostTestPublication = `-- name: CreatePostTestPublication :exec
INSERT INTO post_test_publications
    (user_id, test_id, winner_candidate_id, action, request_key, fingerprint,
     post_slug, resulting_content_revision, receipt, created_at)
VALUES (?1, ?2, ?3, 'apply_output',
    ?4, ?5, ?6,
    ?7, ?8, ?9)
`

type CreatePostTestPublicationParams struct {
	UserID                   string
	TestID                   string
	WinnerCandidateID        string
	RequestKey               string
	Fingerprint              string
	PostSlug                 string
	ResultingContentRevision int64
	Receipt                  string
	CreatedAt                string
}

func (q *Queries) CreatePostTestPublication(ctx context.Context, arg CreatePostTestPublicationParams) error {
	_, err := q.db.ExecContext(ctx, createPostTestPublication,
		arg.UserID,
		arg.TestID,
		arg.WinnerCandidateID,
		arg.RequestKey,
		arg.Fingerprint,
		arg.PostSlug,
		arg.ResultingContentRevision,
		arg.Receipt,
		arg.CreatedAt,
	)
	return err
}

const getPostTestPublications = `-- name: GetPostTestPublications :many
SELECT fingerprint, receipt FROM post_test_publications
WHERE user_id = ?1
  AND ((test_id = ?2 AND winner_candidate_id = ?3 AND action = 'apply_output')
       OR request_key = ?4)
`

type GetPostTestPublicationsParams struct {
	UserID            string
	TestID            string
	WinnerCandidateID string
	RequestKey        string
}

type GetPostTestPublicationsRow struct {
	Fingerprint string
	Receipt     string
}

// Post-owned winner application and receipt. No test or job tables are read here.
func (q *Queries) GetPostTestPublications(ctx context.Context, arg GetPostTestPublicationsParams) ([]GetPostTestPublicationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostTestPublications,
		arg.UserID,
		arg.TestID,
		arg.WinnerCandidateID,
		arg.RequestKey,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostTestPublicationsRow
	for rows.Next() {
		var i GetPostTestPublicationsRow
		if err := rows.Scan(&i.Fingerprint, &i.Receipt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readTestPublicationReceipt = `-- name: ReadTestPublicationReceipt :one
SELECT receipt FROM post_test_publications WHERE user_id=? AND test_id=? AND winner_candidate_id=? AND action='apply_output'
`

type ReadTestPublicationReceiptParams struct {
	UserID            string
	TestID            string
	WinnerCandidateID string
}

func (q *Queries) ReadTestPublicationReceipt(ctx context.Context, arg ReadTestPublicationReceiptParams) (string, error) {
	row := q.db.QueryRowContext(ctx, readTestPublicationReceipt, arg.UserID, arg.TestID, arg.WinnerCandidateID)
	var receipt string
	err := row.Scan(&receipt)
	return receipt, err
}
