// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uploads.sql

package sqlc

import (
	"context"
)

const createUpload = `-- name: CreateUpload :exec

INSERT INTO uploads (id, post_slug, filename, r2_key, expires_at, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateUploadParams struct {
	ID        string
	PostSlug  string
	Filename  string
	R2Key     string
	ExpiresAt string
	CreatedAt string
}

// Uploads presigned but not yet confirmed. A row dies on confirm or by the sweep.
func (q *Queries) CreateUpload(ctx context.Context, arg CreateUploadParams) error {
	_, err := q.db.ExecContext(ctx, createUpload,
		arg.ID,
		arg.PostSlug,
		arg.Filename,
		arg.R2Key,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteUpload = `-- name: DeleteUpload :exec
DELETE FROM uploads WHERE id = ?
`

func (q *Queries) DeleteUpload(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUpload, id)
	return err
}

const getUpload = `-- name: GetUpload :one
SELECT id, post_slug, filename, r2_key, expires_at, created_at
FROM uploads WHERE id = ?
`

func (q *Queries) GetUpload(ctx context.Context, id string) (Upload, error) {
	row := q.db.QueryRowContext(ctx, getUpload, id)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.PostSlug,
		&i.Filename,
		&i.R2Key,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUploadByFilename = `-- name: GetUploadByFilename :one
SELECT id, post_slug, filename, r2_key, expires_at, created_at
FROM uploads WHERE post_slug = ? AND filename = ?
`

type GetUploadByFilenameParams struct {
	PostSlug string
	Filename string
}

func (q *Queries) GetUploadByFilename(ctx context.Context, arg GetUploadByFilenameParams) (Upload, error) {
	row := q.db.QueryRowContext(ctx, getUploadByFilename, arg.PostSlug, arg.Filename)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.PostSlug,
		&i.Filename,
		&i.R2Key,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAllUploadKeys = `-- name: ListAllUploadKeys :many
SELECT r2_key FROM uploads
`

func (q *Queries) ListAllUploadKeys(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAllUploadKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var r2_key string
		if err := rows.Scan(&r2_key); err != nil {
			return nil, err
		}
		items = append(items, r2_key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUploadsExpiredBefore = `-- name: ListUploadsExpiredBefore :many
SELECT id, post_slug, filename, r2_key, expires_at, created_at
FROM uploads WHERE expires_at < ?
`

func (q *Queries) ListUploadsExpiredBefore(ctx context.Context, expiresAt string) ([]Upload, error) {
	rows, err := q.db.QueryContext(ctx, listUploadsExpiredBefore, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Upload
	for rows.Next() {
		var i Upload
		if err := rows.Scan(
			&i.ID,
			&i.PostSlug,
			&i.Filename,
			&i.R2Key,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const uploadFilenameTaken = `-- name: UploadFilenameTaken :one
SELECT EXISTS (SELECT 1 FROM uploads WHERE post_slug = ? AND filename = ?)
`

type UploadFilenameTakenParams struct {
	PostSlug string
	Filename string
}

func (q *Queries) UploadFilenameTaken(ctx context.Context, arg UploadFilenameTakenParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, uploadFilenameTaken, arg.PostSlug, arg.Filename)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
